import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const crossBorderGdprStages: Stage[] = [
  {
    id: 1,
    slug: 'tag-data-origin',
    title: 'Tag data origin',
    description:
      'Record the EU region, source country, database, and extraction time before any field changes.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"customer_name": "Anneliese Vogel",',
        indent: 1,
        key: 'customer_name',
        valueType: 'string',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
      },
      {
        content: '"customer_dob": "1987-04-12",',
        indent: 1,
        key: 'customer_dob',
        valueType: 'string',
      },
      {
        content: '"customer_address": "Lindenstrasse 14, 10969 Berlin",',
        indent: 1,
        key: 'customer_address',
        valueType: 'string',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z",',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '"ip_address": "85.214.132.117"',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
        type: 'added',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '},',
        indent: 1,
        type: 'added',
      },
      {
        content: '"customer_address": "Lindenstrasse 14, 10969 Berlin",',
        indent: 1,
        key: 'customer_address',
        valueType: 'string',
      },
      {
        content: '"customer_dob": "1987-04-12",',
        indent: 1,
        key: 'customer_dob',
        valueType: 'string',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"customer_name": "Anneliese Vogel",',
        indent: 1,
        key: 'customer_name',
        valueType: 'string',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
      },
      {
        content: '"ip_address": "85.214.132.117",',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 2,
    slug: 'create-a-transformation-record',
    title: 'Create a transformation record',
    description:
      'Write the legal basis, original PII fields, and transfer type into a GDPR transfer record.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"customer_address": "Lindenstrasse 14, 10969 Berlin",',
        indent: 1,
        key: 'customer_address',
        valueType: 'string',
      },
      {
        content: '"customer_dob": "1987-04-12",',
        indent: 1,
        key: 'customer_dob',
        valueType: 'string',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"customer_name": "Anneliese Vogel",',
        indent: 1,
        key: 'customer_name',
        valueType: 'string',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
      },
      {
        content: '"ip_address": "85.214.132.117",',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
        type: 'added',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
        type: 'added',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
        type: 'added',
      },
      {
        content: '"customer_id",',
        indent: 3,
        type: 'added',
      },
      {
        content: '"customer_name",',
        indent: 3,
        type: 'added',
      },
      {
        content: '"customer_email",',
        indent: 3,
        type: 'added',
      },
      {
        content: '"customer_dob",',
        indent: 3,
        type: 'added',
      },
      {
        content: '"customer_address",',
        indent: 3,
        type: 'added',
      },
      {
        content: '"iban",',
        indent: 3,
        type: 'added',
      },
      {
        content: '"ip_address"',
        indent: 3,
        type: 'added',
      },
      {
        content: '],',
        indent: 2,
        type: 'added',
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '},',
        indent: 1,
        type: 'added',
      },
      {
        content: '"customer_address": "Lindenstrasse 14, 10969 Berlin",',
        indent: 1,
        key: 'customer_address',
        valueType: 'string',
      },
      {
        content: '"customer_dob": "1987-04-12",',
        indent: 1,
        key: 'customer_dob',
        valueType: 'string',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"customer_name": "Anneliese Vogel",',
        indent: 1,
        key: 'customer_name',
        valueType: 'string',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
      },
      {
        content: '"ip_address": "85.214.132.117",',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 3,
    slug: 'delete-high-risk-fields',
    title: 'Delete high-risk fields',
    description:
      'Drop the name and address, and replace the date of birth with an age bucket.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"customer_address": "Lindenstrasse 14, 10969 Berlin",',
        indent: 1,
        key: 'customer_address',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"customer_dob": "1987-04-12",',
        indent: 1,
        key: 'customer_dob',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"customer_name": "Anneliese Vogel",',
        indent: 1,
        key: 'customer_name',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
      },
      {
        content: '"ip_address": "85.214.132.117",',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'customer_age_bucket',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
      },
      {
        content: '"ip_address": "85.214.132.117",',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 4,
    slug: 'hash-identifiers',
    title: 'Hash identifiers',
    description:
      'Salt and hash the customer id, and reduce the email, IBAN, and IP address to coarse values.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'customer_age_bucket',
        valueType: 'string',
      },
      {
        content: '"customer_email": "anneliese.vogel@example.de",',
        indent: 1,
        key: 'customer_email',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"customer_id": 50231,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
        type: 'removed',
      },
      {
        content: '"iban": "DE89370400440532013000",',
        indent: 1,
        key: 'iban',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"ip_address": "85.214.132.117",',
        indent: 1,
        key: 'ip_address',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"anonymized_customer_id": "2c3bff82c8f5",',
        indent: 1,
        key: 'anonymized_customer_id',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"bank_country": "DE",',
        indent: 1,
        key: 'bank_country',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'customer_age_bucket',
        valueType: 'string',
      },
      {
        content: '"email_domain": "example.de",',
        indent: 1,
        key: 'email_domain',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"ip_subnet": "85.214.0.0/16",',
        indent: 1,
        key: 'ip_subnet',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 5,
    slug: 'generalize-values',
    title: 'Generalize values',
    description:
      'Bucket the amount and truncate the timestamp to the hour while keeping the exact amount for sums.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"anonymized_customer_id": "2c3bff82c8f5",',
        indent: 1,
        key: 'anonymized_customer_id',
        valueType: 'string',
      },
      {
        content: '"bank_country": "DE",',
        indent: 1,
        key: 'bank_country',
        valueType: 'string',
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'customer_age_bucket',
        valueType: 'string',
      },
      {
        content: '"email_domain": "example.de",',
        indent: 1,
        key: 'email_domain',
        valueType: 'string',
      },
      {
        content: '"ip_subnet": "85.214.0.0/16",',
        indent: 1,
        key: 'ip_subnet',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"amount_bucket": "100-500",',
        indent: 1,
        key: 'amount_bucket',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"anonymized_customer_id": "2c3bff82c8f5",',
        indent: 1,
        key: 'anonymized_customer_id',
        valueType: 'string',
      },
      {
        content: '"bank_country": "DE",',
        indent: 1,
        key: 'bank_country',
        valueType: 'string',
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'customer_age_bucket',
        valueType: 'string',
      },
      {
        content: '"email_domain": "example.de",',
        indent: 1,
        key: 'email_domain',
        valueType: 'string',
      },
      {
        content: '"ip_subnet": "85.214.0.0/16",',
        indent: 1,
        key: 'ip_subnet',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_hour": "2024-01-15T13:00:00Z",',
        indent: 1,
        key: 'transaction_hour',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 6,
    slug: 'validate-anonymization',
    title: 'Validate anonymization',
    description:
      'Fail if any original PII field remains, then attest the verification in the transfer record.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '"customer_id",',
        indent: 3,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
      },
      {
        content: '"customer_dob",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"iban",',
        indent: 3,
      },
      {
        content: '"ip_address"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global"',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"amount_bucket": "100-500",',
        indent: 1,
        key: 'amount_bucket',
        valueType: 'string',
      },
      {
        content: '"anonymized_customer_id": "2c3bff82c8f5",',
        indent: 1,
        key: 'anonymized_customer_id',
        valueType: 'string',
      },
      {
        content: '"bank_country": "DE",',
        indent: 1,
        key: 'bank_country',
        valueType: 'string',
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'customer_age_bucket',
        valueType: 'string',
      },
      {
        content: '"email_domain": "example.de",',
        indent: 1,
        key: 'email_domain',
        valueType: 'string',
      },
      {
        content: '"ip_subnet": "85.214.0.0/16",',
        indent: 1,
        key: 'ip_subnet',
        valueType: 'string',
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_hour": "2024-01-15T13:00:00Z",',
        indent: 1,
        key: 'transaction_hour',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_data_origin": {',
        indent: 1,
        key: '_data_origin',
        valueType: 'object',
      },
      {
        content: '"country": "DE",',
        indent: 2,
        key: 'country',
        valueType: 'string',
      },
      {
        content: '"database": "transactions_eu",',
        indent: 2,
        key: 'database',
        valueType: 'string',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:42.064376-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"pipeline": "eu-cross-border-transfer",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"region": "EU"',
        indent: 2,
        key: 'region',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_gdpr_compliance": {',
        indent: 1,
        key: '_gdpr_compliance',
        valueType: 'object',
      },
      {
        content: '"anonymization_applied": true,',
        indent: 2,
        key: 'anonymization_applied',
        valueType: 'boolean',
      },
      {
        content: '"anonymization_verified": true,',
        indent: 2,
        key: 'anonymization_verified',
        valueType: 'boolean',
        type: 'added',
      },
      {
        content: '"fields_hashed": [',
        indent: 2,
        key: 'fields_hashed',
        valueType: 'array',
        type: 'added',
      },
      {
        content: '"customer_id",',
        indent: 3,
        key: 'fields_removed',
        valueType: 'array',
        type: 'added',
      },
      {
        content: '"customer_email",',
        indent: 3,
        key: 'gdpr_article',
        valueType: 'string',
      },
      {
        content: '"iban",',
        indent: 3,
        key: 'legal_basis',
        valueType: 'string',
      },
      {
        content: '"ip_address"',
        indent: 3,
        key: 'original_pii_fields',
        valueType: 'array',
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content: '"fields_removed": [',
        indent: 2,
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_address",',
        indent: 3,
      },
      {
        content: '"customer_dob"',
        indent: 3,
      },
      {
        content: '],',
        indent: 2,
      },
      {
        content:
          '"gdpr_article": "Article 44 - General principle for transfers",',
        indent: 2,
      },
      {
        content: '"legal_basis": "legitimate_interest_analytics",',
        indent: 2,
      },
      {
        content: '"original_pii_fields": [',
        indent: 2,
        key: 'transfer_type',
        valueType: 'string',
      },
      {
        content: '"customer_id",',
        indent: 3,
        key: 'verification_timestamp',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"customer_name",',
        indent: 3,
      },
      {
        content: '"customer_email",',
        indent: 3,
        key: 'amount_bucket',
        valueType: 'string',
      },
      {
        content: '"customer_dob",',
        indent: 3,
        key: 'anonymized_customer_id',
        valueType: 'string',
      },
      {
        content: '"customer_address",',
        indent: 3,
        key: 'bank_country',
        valueType: 'string',
      },
      {
        content: '"iban",',
        indent: 3,
        key: 'customer_age_bucket',
        valueType: 'string',
      },
      {
        content: '"ip_address"',
        indent: 3,
        key: 'email_domain',
        valueType: 'string',
      },
      {
        content: '],',
        indent: 2,
        key: 'ip_subnet',
        valueType: 'string',
      },
      {
        content: '"transfer_type": "cross_border_eu_to_global",',
        indent: 2,
        key: 'merchant_country',
        valueType: 'string',
      },
      {
        content: '"verification_timestamp": "2026-10-05T18:24:42.158584-07:00"',
        indent: 2,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
        key: 'transaction_amount',
        valueType: 'number',
      },
      {
        content: '"amount_bucket": "100-500",',
        indent: 1,
        key: 'transaction_currency',
        valueType: 'string',
      },
      {
        content: '"anonymized_customer_id": "2c3bff82c8f5",',
        indent: 1,
        key: 'transaction_hour',
        valueType: 'string',
      },
      {
        content: '"bank_country": "DE",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"customer_age_bucket": "35-44",',
        indent: 1,
        key: 'transaction_timestamp',
        valueType: 'string',
      },
      {
        content: '"email_domain": "example.de",',
        indent: 1,
      },
      {
        content: '"ip_subnet": "85.214.0.0/16",',
        indent: 1,
      },
      {
        content: '"merchant_country": "DE",',
        indent: 1,
      },
      {
        content: '"merchant_name": "Kaufhaus Nord",',
        indent: 1,
      },
      {
        content: '"transaction_amount": 249.9,',
        indent: 1,
      },
      {
        content: '"transaction_currency": "EUR",',
        indent: 1,
      },
      {
        content: '"transaction_hour": "2024-01-15T13:00:00Z",',
        indent: 1,
      },
      {
        content: '"transaction_id": "TXN-EU-2024-001842",',
        indent: 1,
      },
      {
        content: '"transaction_timestamp": "2024-01-15T13:42:07Z"',
        indent: 1,
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
];
