import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const encryptionPatternsStages: Stage[] = [
  {
    id: 1,
    slug: 'original-sensitive-data',
    title: 'Original Sensitive Data',
    description:
      'Synthetic payment and customer fields before the example applies field-level encryption patterns.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"transaction_id": "txn-12345",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      { content: '"payment": {', indent: 1 },
      {
        content: '"card_number": "4532-1234-5678-9010",',
        indent: 2,
        key: 'card_number',
        valueType: 'string',
      },
      { content: '"cvv": "123",', indent: 2, key: 'cvv', valueType: 'string' },
      {
        content: '"cardholder_name": "Sarah Johnson"',
        indent: 2,
        key: 'cardholder_name',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"customer": {', indent: 1 },
      {
        content: '"email": "sarah.johnson@example.com",',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      {
        content: '"ssn": "123-45-6789"',
        indent: 2,
        key: 'ssn',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"transaction_id": "txn-12345",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      { content: '"payment": {', indent: 1 },
      {
        content: '"card_number": "4532-1234-5678-9010",',
        indent: 2,
        key: 'card_number',
        valueType: 'string',
      },
      { content: '"cvv": "123",', indent: 2, key: 'cvv', valueType: 'string' },
      {
        content: '"cardholder_name": "Sarah Johnson"',
        indent: 2,
        key: 'cardholder_name',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"customer": {', indent: 1 },
      {
        content: '"email": "sarah.johnson@example.com",',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      {
        content: '"ssn": "123-45-6789"',
        indent: 2,
        key: 'ssn',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'payment-field-encryption',
    title: 'Payment Field Encryption',
    description:
      'Select synthetic card fields for the configured encryption processor and retain authored display fields.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"transaction_id": "txn-12345",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      { content: '"payment": {', indent: 1 },
      {
        content: '"card_number": "4532-1234-5678-9010",',
        indent: 2,
        key: 'card_number',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"cvv": "123",',
        indent: 2,
        key: 'cvv',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"cardholder_name": "Sarah Johnson"',
        indent: 2,
        key: 'cardholder_name',
        valueType: 'string',
        type: 'removed',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"transaction_id": "txn-12345",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      { content: '"payment": {', indent: 1, type: 'highlighted' },
      {
        content: '"card_number_encrypted": "AES256GCM:v1:Y2FyZGRhdGE=...",',
        indent: 2,
        key: 'card_number_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"cvv_encrypted": "AES256GCM:v1:Y3Z2ZGF0YQ==...",',
        indent: 2,
        key: 'cvv_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"cardholder_name_encrypted": "AES256GCM:v1:bmFtZWRhdGE=...",',
        indent: 2,
        key: 'cardholder_name_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"card_brand": "visa",',
        indent: 2,
        key: 'card_brand',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"card_last_four": "9010",',
        indent: 2,
        key: 'card_last_four',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"card_bin": "453212"',
        indent: 2,
        key: 'card_bin',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'identity-field-encryption',
    title: 'Identity Field Encryption',
    description:
      'Select synthetic identity fields for encryption and retain authored derived fields.',
    inputLines: [
      { content: '{', indent: 0 },
      { content: '"customer": {', indent: 1 },
      {
        content: '"first_name": "Sarah",',
        indent: 2,
        key: 'first_name',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"last_name": "Johnson",',
        indent: 2,
        key: 'last_name',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"email": "sarah.johnson@example.com",',
        indent: 2,
        key: 'email',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"phone": "+1-415-555-0123",',
        indent: 2,
        key: 'phone',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"ssn": "123-45-6789"',
        indent: 2,
        key: 'ssn',
        valueType: 'string',
        type: 'removed',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      { content: '"customer": {', indent: 1, type: 'highlighted' },
      {
        content: '"first_name_encrypted": "AES256GCM:v1:Zmlyc3ROYW1l...",',
        indent: 2,
        key: 'first_name_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"last_name_encrypted": "AES256GCM:v1:bGFzdE5hbWU=...",',
        indent: 2,
        key: 'last_name_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"email_encrypted": "AES256GCM:v1:ZW1haWxkYXRh...",',
        indent: 2,
        key: 'email_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"email_domain": "example.com",',
        indent: 2,
        key: 'email_domain',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"phone_encrypted": "AES256GCM:v1:cGhvbmVkYXRh...",',
        indent: 2,
        key: 'phone_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"phone_area_code": "415",',
        indent: 2,
        key: 'phone_area_code',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"ssn_encrypted": "AES256GCM:v1:c3NuZGF0YQ==...",',
        indent: 2,
        key: 'ssn_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"ssn_last_four": "6789"',
        indent: 2,
        key: 'ssn_last_four',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'address-data-encryption-location-privacy',
    title: 'Address Data Encryption (Location Privacy)',
    description:
      'Encrypt street addresses and detailed ZIP codes while preserving city, state, and ZIP prefix for demographic analytics.',
    inputLines: [
      { content: '{', indent: 0 },
      { content: '"billing_address": {', indent: 1 },
      {
        content: '"street": "123 Main St, Apt 4B",',
        indent: 2,
        key: 'street',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"city": "San Francisco",',
        indent: 2,
        key: 'city',
        valueType: 'string',
      },
      {
        content: '"state": "CA",',
        indent: 2,
        key: 'state',
        valueType: 'string',
      },
      {
        content: '"zip": "94102-1234"',
        indent: 2,
        key: 'zip',
        valueType: 'string',
        type: 'removed',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      { content: '"billing_address": {', indent: 1, type: 'highlighted' },
      {
        content: '"street_encrypted": "AES256GCM:v1:c3RyZWV0ZGF0YQ==...",',
        indent: 2,
        key: 'street_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"zip_encrypted": "AES256GCM:v1:emlwZGF0YWhlcmU=...",',
        indent: 2,
        key: 'zip_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"city": "San Francisco",',
        indent: 2,
        key: 'city',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"state": "CA",',
        indent: 2,
        key: 'state',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"zip_prefix": "941",',
        indent: 2,
        key: 'zip_prefix',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"metro_area": "sf_bay_area"',
        indent: 2,
        key: 'metro_area',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '},', indent: 1, type: 'highlighted' },
      { content: '"address_analysis": {', indent: 1, type: 'highlighted' },
      {
        content: '"same_city": false,',
        indent: 2,
        key: 'same_city',
        valueType: 'boolean',
        type: 'highlighted',
      },
      {
        content: '"same_state": true,',
        indent: 2,
        key: 'same_state',
        valueType: 'boolean',
        type: 'highlighted',
      },
      {
        content: '"same_metro": true',
        indent: 2,
        key: 'same_metro',
        valueType: 'boolean',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 5,
    slug: 'temporal-field-encryption',
    title: 'Temporal Field Encryption',
    description:
      'Encrypt selected source dates while retaining authored cohort and season fields for inspection.',
    inputLines: [
      { content: '{', indent: 0 },
      { content: '"customer": {', indent: 1 },
      {
        content: '"date_of_birth": "1985-03-15"',
        indent: 2,
        key: 'date_of_birth',
        valueType: 'string',
        type: 'removed',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      { content: '"customer": {', indent: 1, type: 'highlighted' },
      {
        content:
          '"date_of_birth_encrypted": "AES256GCM:v1:ZGF0ZW9mYmlydGg=...",',
        indent: 2,
        key: 'date_of_birth_encrypted',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"birth_year": 1985,',
        indent: 2,
        key: 'birth_year',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"current_age": 40,',
        indent: 2,
        key: 'current_age',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"age_range": "35_to_44",',
        indent: 2,
        key: 'age_range',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"birth_decade": "1980s",',
        indent: 2,
        key: 'birth_decade',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"birth_season": "spring"',
        indent: 2,
        key: 'birth_season',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 6,
    slug: 'illustrative-key-version-metadata',
    title: 'Illustrative Key-Version Metadata',
    description:
      'Combined authored field-selection patterns with illustrative key-version and transformation metadata.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"transaction_id": "txn-12345",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      { content: '"payment": {', indent: 1 },
      {
        content: '"card_number_encrypted": "AES256GCM:v1:...",',
        indent: 2,
        key: 'card_number_encrypted',
        valueType: 'string',
      },
      {
        content: '"card_last_four": "9010"',
        indent: 2,
        key: 'card_last_four',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"customer": {', indent: 1 },
      {
        content: '"email_encrypted": "AES256GCM:v1:..."',
        indent: 2,
        key: 'email_encrypted',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"transaction_id": "txn-12345",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      { content: '"payment": {', indent: 1 },
      {
        content: '"card_number_encrypted": "AES256GCM:v1:...",',
        indent: 2,
        key: 'card_number_encrypted',
        valueType: 'string',
      },
      {
        content: '"card_last_four": "9010"',
        indent: 2,
        key: 'card_last_four',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"customer": {', indent: 1 },
      {
        content: '"email_encrypted": "AES256GCM:v1:..."',
        indent: 2,
        key: 'email_encrypted',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"multi_key_metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"encryption_architecture": "multi_tier_risk_based",',
        indent: 2,
        key: 'encryption_architecture',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"key_tiers_used": { ... }',
        indent: 2,
        key: 'key_tiers_used',
        valueType: 'object',
        type: 'highlighted',
      },
      { content: '},', indent: 1, type: 'highlighted' },
      { content: '"operational_metrics": {', indent: 1, type: 'highlighted' },
      {
        content: '"selected_field_count": 11,',
        indent: 2,
        key: 'selected_field_count',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"fixture_status": "illustrative"',
        indent: 2,
        key: 'fixture_status',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
];
