pipeline:
  processors:
    # Parse CSV with named columns
    - csv:
        columns: [timestamp, metric_name, sensor_id, value, unit]
        delimiter: ","

    # Convert types and add sensor metadata
    - mapping: |
        root = this
        root.timestamp_unix = this.timestamp.parse_timestamp("2006-01-02").ts_unix()
        root.value_numeric = this.value.number()
        root.sensor_metadata = if this.sensor_id.has_prefix("temp-") {
          {"type": "temperature", "location": "warehouse"}
        } else {
          {"type": "unknown", "location": "unknown"}
        }
        root.alert = if this.metric_name == "temperature" && this.value_numeric > 30 {
          {"level": "critical", "message": "Temperature exceeds threshold"}
        }
