pipeline:
  processors:
    # Parse JSON documents
    - json_documents:
        parts: []

    # Normalize timestamp and add metadata
    - mapping: |
        root = this
        root.timestamp_unix = this.timestamp.parse_timestamp("2006-01-02T15:04:05.999Z07:00").ts_unix()
        root.level = this.level.or("INFO").uppercase()
        root.metadata = {
          "parsed_by": "json-parser",
          "parsed_at": now().ts_unix(),
          "source_format": "json"
        }
