import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  examples: [
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'getting-started/local-development',
      ],
    },
    {
      type: 'category',
      label: 'Data Routing',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Content Routing',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/content-routing/index',
            'data-routing/content-routing/explorer',
            'data-routing/content-routing/setup',
            'data-routing/content-routing/step-1-route-by-severity',
            'data-routing/content-routing/step-2-route-by-region',
            'data-routing/content-routing/step-3-route-by-event-type',
            'data-routing/content-routing/step-4-advanced-patterns',
            'data-routing/content-routing/complete-content-routing',
            'data-routing/content-routing/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Circuit Breakers',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/circuit-breakers/index',
            'data-routing/circuit-breakers/explorer',
            'data-routing/circuit-breakers/setup',
            'data-routing/circuit-breakers/step-1-http-circuit-breakers',
            'data-routing/circuit-breakers/step-2-database-circuit-breakers',
            'data-routing/circuit-breakers/step-3-multi-level-fallback',
            'data-routing/circuit-breakers/step-4-advanced-patterns',
            'data-routing/circuit-breakers/complete-circuit-breakers',
            'data-routing/circuit-breakers/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Priority Queues',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/priority-queues/index',
            'data-routing/priority-queues/explorer',
            'data-routing/priority-queues/setup',
            'data-routing/priority-queues/step-1-severity-routing',
            'data-routing/priority-queues/step-2-customer-tier-routing',
            'data-routing/priority-queues/step-3-multi-criteria-scoring',
            'data-routing/priority-queues/step-4-prevent-starvation',
            'data-routing/priority-queues/step-5-advanced-patterns',
            'data-routing/priority-queues/complete-priority-pipeline',
            'data-routing/priority-queues/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Fan-Out Pattern',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/fan-out-pattern/index',
            'data-routing/fan-out-pattern/explorer',
            'data-routing/fan-out-pattern/setup',
            'data-routing/fan-out-pattern/step-1-configure-broker',
            'data-routing/fan-out-pattern/step-2-add-kafka',
            'data-routing/fan-out-pattern/step-3-add-s3',
            'data-routing/fan-out-pattern/step-4-add-elasticsearch',
            'data-routing/fan-out-pattern/step-5-advanced-patterns',
            'data-routing/fan-out-pattern/complete-fan-out-pipeline',
            'data-routing/fan-out-pattern/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Content Splitting',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/content-splitting/index',
            'data-routing/content-splitting/explorer',
            'data-routing/content-splitting/setup',
            'data-routing/content-splitting/step-1-split-json-arrays',
            'data-routing/content-splitting/step-2-split-csv-batches',
            'data-routing/content-splitting/step-3-split-nested-structures',
            'data-routing/content-splitting/step-4-advanced-patterns',
            'data-routing/content-splitting/complete-content-splitting',
            'data-routing/content-splitting/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Security',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Field-Level Encryption Patterns',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/encryption-patterns/index',
            'data-security/encryption-patterns/explorer',
            'data-security/encryption-patterns/setup',
            'data-security/encryption-patterns/step-1-encrypt-payment-data',
            'data-security/encryption-patterns/step-2-encrypt-pii-fields',
            'data-security/encryption-patterns/step-3-encrypt-addresses',
            'data-security/encryption-patterns/step-4-encrypt-dates',
            'data-security/encryption-patterns/step-5-advanced-patterns',
            'data-security/encryption-patterns/complete-encryption-pipeline',
            'data-security/encryption-patterns/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Encrypt Sensitive Data',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/encrypt-data/index',
            'data-security/encrypt-data/explorer',
            'data-security/encrypt-data/setup',
            'data-security/encrypt-data/step-1-encrypt-payment-data',
            'data-security/encrypt-data/step-2-encrypt-customer-data',
            'data-security/encrypt-data/step-3-encrypt-location-data',
            'data-security/encrypt-data/step-4-advanced-patterns',
            'data-security/encrypt-data/complete-pipeline',
            'data-security/encrypt-data/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Remove PII',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/remove-pii/index',
            'data-security/remove-pii/explorer',
            'data-security/remove-pii/setup',
            'data-security/remove-pii/step-1-delete-payment-data',
            'data-security/remove-pii/step-2-hash-ip-address',
            'data-security/remove-pii/step-3-hash-email',
            'data-security/remove-pii/step-4-pseudonymize-user',
            'data-security/remove-pii/step-5-generalize-location',
            'data-security/remove-pii/step-6-advanced-patterns',
            'data-security/remove-pii/complete-pipeline',
            'data-security/remove-pii/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Delete Payment PII',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/delete-payment-pii/index',
            'data-security/delete-payment-pii/setup',
            'data-security/delete-payment-pii/step-1-identify-payment-pii',
            'data-security/delete-payment-pii/step-2-preserve-analytics-data',
            'data-security/delete-payment-pii/complete-payment-pipeline',
            'data-security/delete-payment-pii/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Enforce Schema Validation',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/enforce-schema/index',
            'data-security/enforce-schema/setup',
            'data-security/enforce-schema/step-1-define-json-schema',
            'data-security/enforce-schema/step-2-route-failures-dlq',
            'data-security/enforce-schema/step-3-advanced-patterns',
            'data-security/enforce-schema/complete-schema-validation',
            'data-security/enforce-schema/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Transformation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Aggregate Time Windows',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/aggregate-time-windows/index',
            'data-transformation/aggregate-time-windows/explorer',
            'data-transformation/aggregate-time-windows/setup',
            'data-transformation/aggregate-time-windows/step-1-tumbling-windows',
            'data-transformation/aggregate-time-windows/step-2-sliding-windows',
            'data-transformation/aggregate-time-windows/step-3-session-windows',
            'data-transformation/aggregate-time-windows/step-4-advanced-patterns',
            'data-transformation/aggregate-time-windows/complete-aggregation-pipeline',
            'data-transformation/aggregate-time-windows/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Deduplicate Events',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/deduplicate-events/index',
            'data-transformation/deduplicate-events/explorer',
            'data-transformation/deduplicate-events/setup',
            'data-transformation/deduplicate-events/step-1-hash-based-exact-duplicates',
            'data-transformation/deduplicate-events/step-2-fingerprint-semantic-duplicates',
            'data-transformation/deduplicate-events/step-3-id-based-unique-identifiers',
            'data-transformation/deduplicate-events/step-4-advanced-patterns',
            'data-transformation/deduplicate-events/complete-deduplication-pipeline',
            'data-transformation/deduplicate-events/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Normalize Timestamps',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/normalize-timestamps/index',
            'data-transformation/normalize-timestamps/setup',
            'data-transformation/normalize-timestamps/step-1-parse-formats',
            'data-transformation/normalize-timestamps/step-2-convert-timezones',
            'data-transformation/normalize-timestamps/step-3-enrich-metadata',
            'data-transformation/normalize-timestamps/step-4-advanced-patterns',
            'data-transformation/normalize-timestamps/complete-pipeline',
            'data-transformation/normalize-timestamps/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Parse Structured Logs',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/parse-logs/index',
            'data-transformation/parse-logs/explorer',
            'data-transformation/parse-logs/setup',
            'data-transformation/parse-logs/step-1-parse-json-logs',
            'data-transformation/parse-logs/step-2-parse-csv-data',
            'data-transformation/parse-logs/step-3-parse-syslog-messages',
            'data-transformation/parse-logs/step-4-multi-format-detection',
            'data-transformation/parse-logs/step-5-advanced-patterns',
            'data-transformation/parse-logs/complete-parser',
            'data-transformation/parse-logs/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Transform Formats',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/transform-formats/index',
            'data-transformation/transform-formats/setup',
            'data-transformation/transform-formats/step-1-convert-json-avro',
            'data-transformation/transform-formats/step-2-convert-avro-parquet',
            'data-transformation/transform-formats/step-3-convert-json-protobuf',
            'data-transformation/transform-formats/step-4-auto-detect-formats',
            'data-transformation/transform-formats/step-5-advanced-patterns',
            'data-transformation/transform-formats/complete-pipeline',
            'data-transformation/transform-formats/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Log Processing',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Filter by Severity',
          collapsible: true,
          collapsed: true,
          items: [
            'log-processing/filter-severity/index',
            'log-processing/filter-severity/setup',
            'log-processing/filter-severity/step-1-parse-json-add-metadata',
            'log-processing/filter-severity/step-2-filter-by-severity',
            'log-processing/filter-severity/step-4-advanced-patterns',
            'log-processing/filter-severity/complete-filter-severity',
            'log-processing/filter-severity/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Log Enrichment & S3 Export',
          collapsible: true,
          collapsed: true,
          items: [
            'log-processing/enrich-export/index',
            'log-processing/enrich-export/explorer',
            'log-processing/enrich-export/setup',
            'log-processing/enrich-export/step-1-generate-test-data',
            'log-processing/enrich-export/step-2-add-lineage-metadata',
            'log-processing/enrich-export/step-3-restructure-format',
            'log-processing/enrich-export/step-4-configure-batching',
            'log-processing/enrich-export/step-5-export-s3',
            'log-processing/enrich-export/step-6-advanced-patterns',
            'log-processing/enrich-export/complete-log-enrichment',
            'log-processing/enrich-export/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Production Pipeline',
          collapsible: true,
          collapsed: true,
          items: [
            'log-processing/production-pipeline/index',
            'log-processing/production-pipeline/setup',
            'log-processing/production-pipeline/step-1-configure-http-input',
            'log-processing/production-pipeline/step-2-parse-validate-logs',
            'log-processing/production-pipeline/step-3-enrich-with-metadata',
            'log-processing/production-pipeline/step-4-filter-score-logs',
            'log-processing/production-pipeline/step-5-redact-sensitive-data',
            'log-processing/production-pipeline/step-6-fan-out-destinations',
            'log-processing/production-pipeline/complete-production-pipeline',
            'log-processing/production-pipeline/troubleshooting',
          ],
        },
      ],
    },
  ],
};

export default sidebars;