import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  examples: [
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Home',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'getting-started/local-development',
        {
          type: 'category',
          label: 'Services',
          collapsible: true,
          collapsed: true,
          items: [
            'getting-started/services/kafka',
            'getting-started/services/postgres',
            'getting-started/services/redis',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Routing',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Content Routing',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/content-routing/index',
            'data-routing/content-routing/explorer',
            'data-routing/content-routing/setup',
            'data-routing/content-routing/step-1-route-by-severity',
            'data-routing/content-routing/step-2-route-by-region',
            'data-routing/content-routing/step-3-route-by-event-type',
            'data-routing/content-routing/step-4-advanced-patterns',
            'data-routing/content-routing/complete-content-routing',
            'data-routing/content-routing/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Circuit Breakers',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/circuit-breakers/index',
            'data-routing/circuit-breakers/explorer',
            'data-routing/circuit-breakers/setup',
            'data-routing/circuit-breakers/step-1-http-circuit-breakers',
            'data-routing/circuit-breakers/step-2-database-circuit-breakers',
            'data-routing/circuit-breakers/step-3-multi-level-fallback',
            'data-routing/circuit-breakers/step-4-advanced-patterns',
            'data-routing/circuit-breakers/complete-circuit-breakers',
            'data-routing/circuit-breakers/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Priority Queues',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/priority-queues/index',
            'data-routing/priority-queues/explorer',
            'data-routing/priority-queues/setup',
            'data-routing/priority-queues/step-1-severity-routing',
            'data-routing/priority-queues/step-2-customer-tier-routing',
            'data-routing/priority-queues/step-3-multi-criteria-scoring',
            'data-routing/priority-queues/step-4-prevent-starvation',
            'data-routing/priority-queues/step-5-advanced-patterns',
            'data-routing/priority-queues/complete-priority-pipeline',
            'data-routing/priority-queues/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Fan-Out Pattern',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/fan-out-pattern/index',
            'data-routing/fan-out-pattern/explorer',
            'data-routing/fan-out-pattern/setup',
            'data-routing/fan-out-pattern/step-1-configure-broker',
            'data-routing/fan-out-pattern/step-2-add-kafka',
            'data-routing/fan-out-pattern/step-3-add-s3',
            'data-routing/fan-out-pattern/step-4-add-elasticsearch',
            'data-routing/fan-out-pattern/step-5-advanced-patterns',
            'data-routing/fan-out-pattern/complete-fan-out-pipeline',
            'data-routing/fan-out-pattern/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Content Splitting',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/content-splitting/index',
            'data-routing/content-splitting/explorer',
            'data-routing/content-splitting/setup',
            'data-routing/content-splitting/step-1-split-json-arrays',
            'data-routing/content-splitting/step-2-split-csv-batches',
            'data-routing/content-splitting/step-3-split-nested-structures',
            'data-routing/content-splitting/step-4-advanced-patterns',
            'data-routing/content-splitting/complete-content-splitting',
            'data-routing/content-splitting/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Smart Buffering',
          collapsible: true,
          collapsed: true,
          items: [
            'data-routing/smart-buffering/index',
            'data-routing/smart-buffering/explorer',
            'data-routing/smart-buffering/setup',
            'data-routing/smart-buffering/step-1-classify-priority',
            'data-routing/smart-buffering/step-2-priority-scoring',
            'data-routing/smart-buffering/step-3-priority-output',
            'data-routing/smart-buffering/step-4-prevent-starvation',
            'data-routing/smart-buffering/complete-smart-buffering',
            'data-routing/smart-buffering/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Security',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Field-Level Encryption Patterns',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/encryption-patterns/index',
            'data-security/encryption-patterns/explorer',
            'data-security/encryption-patterns/setup',
            'data-security/encryption-patterns/step-1-encrypt-payment-data',
            'data-security/encryption-patterns/step-2-encrypt-pii-fields',
            'data-security/encryption-patterns/step-3-encrypt-addresses',
            'data-security/encryption-patterns/step-4-encrypt-dates',
            'data-security/encryption-patterns/step-5-advanced-patterns',
            'data-security/encryption-patterns/complete-encryption-pipeline',
            'data-security/encryption-patterns/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Encrypt Sensitive Data',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/encrypt-data/index',
            'data-security/encrypt-data/explorer',
            'data-security/encrypt-data/setup',
            'data-security/encrypt-data/step-1-encrypt-payment-data',
            'data-security/encrypt-data/step-2-encrypt-customer-data',
            'data-security/encrypt-data/step-3-encrypt-location-data',
            'data-security/encrypt-data/step-4-advanced-patterns',
            'data-security/encrypt-data/complete-pipeline',
            'data-security/encrypt-data/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Remove PII',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/remove-pii/index',
            'data-security/remove-pii/explorer',
            'data-security/remove-pii/setup',
            'data-security/remove-pii/step-1-delete-payment-data',
            'data-security/remove-pii/step-2-hash-ip-address',
            'data-security/remove-pii/step-3-hash-email',
            'data-security/remove-pii/step-4-pseudonymize-user',
            'data-security/remove-pii/step-5-generalize-location',
            'data-security/remove-pii/step-6-advanced-patterns',
            'data-security/remove-pii/complete-pipeline',
            'data-security/remove-pii/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Enforce Schema Validation',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/enforce-schema/index',
            'data-security/enforce-schema/explorer',
            'data-security/enforce-schema/setup',
            'data-security/enforce-schema/step-1-define-json-schema',
            'data-security/enforce-schema/step-2-route-failures-dlq',
            'data-security/enforce-schema/step-3-advanced-patterns',
            'data-security/enforce-schema/complete-schema-validation',
            'data-security/enforce-schema/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Cross-Border GDPR',
          collapsible: true,
          collapsed: true,
          items: [
            'data-security/cross-border-gdpr/index',
            'data-security/cross-border-gdpr/setup',
            'data-security/cross-border-gdpr/step-1-tag-data-origin',
            'data-security/cross-border-gdpr/step-2-create-gdpr-record',
            'data-security/cross-border-gdpr/step-3-delete-high-risk-fields',
            'data-security/cross-border-gdpr/step-4-hash-identifiers',
            'data-security/cross-border-gdpr/step-5-generalize-values',
            'data-security/cross-border-gdpr/step-6-validate-anonymization',
            'data-security/cross-border-gdpr/complete-pipeline',
            'data-security/cross-border-gdpr/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Transformation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Aggregate Time Windows',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/aggregate-time-windows/index',
            'data-transformation/aggregate-time-windows/explorer',
            'data-transformation/aggregate-time-windows/setup',
            'data-transformation/aggregate-time-windows/step-1-tumbling-windows',
            'data-transformation/aggregate-time-windows/step-2-sliding-windows',
            'data-transformation/aggregate-time-windows/step-3-session-windows',
            'data-transformation/aggregate-time-windows/step-4-advanced-patterns',
            'data-transformation/aggregate-time-windows/complete-aggregation-pipeline',
            'data-transformation/aggregate-time-windows/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Deduplicate Events',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/deduplicate-events/index',
            'data-transformation/deduplicate-events/explorer',
            'data-transformation/deduplicate-events/setup',
            'data-transformation/deduplicate-events/step-1-hash-based-exact-duplicates',
            'data-transformation/deduplicate-events/step-2-fingerprint-semantic-duplicates',
            'data-transformation/deduplicate-events/step-3-id-based-unique-identifiers',
            'data-transformation/deduplicate-events/step-4-advanced-patterns',
            'data-transformation/deduplicate-events/complete-deduplication-pipeline',
            'data-transformation/deduplicate-events/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Normalize Timestamps',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/normalize-timestamps/index',
            'data-transformation/normalize-timestamps/explorer',
            'data-transformation/normalize-timestamps/setup',
            'data-transformation/normalize-timestamps/step-1-parse-formats',
            'data-transformation/normalize-timestamps/step-2-convert-timezones',
            'data-transformation/normalize-timestamps/step-3-enrich-metadata',
            'data-transformation/normalize-timestamps/step-4-advanced-patterns',
            'data-transformation/normalize-timestamps/complete-pipeline',
            'data-transformation/normalize-timestamps/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Parse Structured Logs',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/parse-logs/index',
            'data-transformation/parse-logs/explorer',
            'data-transformation/parse-logs/setup',
            'data-transformation/parse-logs/step-1-parse-json-logs',
            'data-transformation/parse-logs/step-2-parse-csv-data',
            'data-transformation/parse-logs/step-3-parse-syslog-messages',
            'data-transformation/parse-logs/step-4-multi-format-detection',
            'data-transformation/parse-logs/step-5-advanced-patterns',
            'data-transformation/parse-logs/complete-parser',
            'data-transformation/parse-logs/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Transform Formats',
          collapsible: true,
          collapsed: true,
          items: [
            'data-transformation/transform-formats/index',
            'data-transformation/transform-formats/explorer',
            'data-transformation/transform-formats/setup',
            'data-transformation/transform-formats/step-1-convert-json-avro',
            'data-transformation/transform-formats/step-2-convert-avro-parquet',
            'data-transformation/transform-formats/step-3-convert-json-protobuf',
            'data-transformation/transform-formats/step-4-auto-detect-formats',
            'data-transformation/transform-formats/step-5-advanced-patterns',
            'data-transformation/transform-formats/complete-pipeline',
            'data-transformation/transform-formats/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Log Processing',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Filter by Severity',
          collapsible: true,
          collapsed: true,
          items: [
            'log-processing/filter-severity/index',
            'log-processing/filter-severity/explorer',
            'log-processing/filter-severity/setup',
            'log-processing/filter-severity/step-1-parse-json-add-metadata',
            'log-processing/filter-severity/step-2-filter-by-severity',
            'log-processing/filter-severity/step-3-route-by-severity',
            'log-processing/filter-severity/step-4-advanced-patterns',
            'log-processing/filter-severity/complete-filter-severity',
            'log-processing/filter-severity/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Log Enrichment & S3 Export',
          collapsible: true,
          collapsed: true,
          items: [
            'log-processing/enrich-export/index',
            'log-processing/enrich-export/explorer',
            'log-processing/enrich-export/setup',
            'log-processing/enrich-export/step-1-generate-test-data',
            'log-processing/enrich-export/step-2-add-lineage-metadata',
            'log-processing/enrich-export/step-3-restructure-format',
            'log-processing/enrich-export/step-4-configure-batching',
            'log-processing/enrich-export/step-5-export-s3',
            'log-processing/enrich-export/step-6-advanced-patterns',
            'log-processing/enrich-export/complete-log-enrichment',
            'log-processing/enrich-export/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Production Pipeline',
          collapsible: true,
          collapsed: true,
          items: [
            'log-processing/production-pipeline/index',
            'log-processing/production-pipeline/explorer',
            'log-processing/production-pipeline/setup',
            'log-processing/production-pipeline/step-1-configure-http-input',
            'log-processing/production-pipeline/step-2-parse-validate-logs',
            'log-processing/production-pipeline/step-3-enrich-with-metadata',
            'log-processing/production-pipeline/step-4-filter-score-logs',
            'log-processing/production-pipeline/step-5-redact-sensitive-data',
            'log-processing/production-pipeline/step-6-fan-out-destinations',
            'log-processing/production-pipeline/complete-production-pipeline',
            'log-processing/production-pipeline/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Splunk Edge Processing',
          collapsible: true,
          collapsed: true,
          items: [
            'integrations/splunk-edge-processing/index',
            'integrations/splunk-edge-processing/explorer',
            'integrations/splunk-edge-processing/setup',
            'integrations/splunk-edge-processing/step-1-collect-like-inputs-conf',
            'integrations/splunk-edge-processing/step-2-parse-like-props-conf',
            'integrations/splunk-edge-processing/step-3-filter-before-indexing',
            'integrations/splunk-edge-processing/step-4-route-to-splunk-hec',
            'integrations/splunk-edge-processing/step-5-advanced-splunk-patterns',
            'integrations/splunk-edge-processing/complete-splunk-integration',
          ],
        },
        {
          type: 'category',
          label: 'Medical Device Intelligence',
          collapsible: true,
          collapsed: true,
          items: [
            'integrations/medical-device-intelligence/index',
          ],
        },
        {
          type: 'category',
          label: 'MotherDuck Retail Analytics',
          collapsible: true,
          collapsed: true,
          items: [
            'integrations/motherduck-retail-analytics/index',
            'integrations/motherduck-retail-analytics/setup',
            'integrations/motherduck-retail-analytics/step-1-generate-pos-data',
            'integrations/motherduck-retail-analytics/step-2-enrich-store-metadata',
            'integrations/motherduck-retail-analytics/step-3-validate-transactions',
            'integrations/motherduck-retail-analytics/step-4-batch-parquet-encode',
            'integrations/motherduck-retail-analytics/step-5-ship-to-s3',
            'integrations/motherduck-retail-analytics/step-6-ducklake-query',
            'integrations/motherduck-retail-analytics/complete-pipeline',
          ],
        },
        {
          type: 'category',
          label: 'O-RAN Telco Pipeline',
          collapsible: true,
          collapsed: true,
          items: [
            'integrations/oran-telco-pipeline/index',
            'integrations/oran-telco-pipeline/explorer',
            'integrations/oran-telco-pipeline/setup',
            'integrations/oran-telco-pipeline/step-1-collect-oran-metrics',
            'integrations/oran-telco-pipeline/step-2-transform-and-enrich',
            'integrations/oran-telco-pipeline/step-3-multi-destination-routing',
            'integrations/oran-telco-pipeline/step-4-grafana-dashboards',
            'integrations/oran-telco-pipeline/step-5-parquet-and-cloudera',
            'integrations/oran-telco-pipeline/complete-oran-pipeline',
          ],
        },
        {
          type: 'category',
          label: 'SCADA Energy Edge',
          collapsible: true,
          collapsed: true,
          items: [
            'integrations/scada-energy-edge/index',
            'integrations/scada-energy-edge/explorer',
            'integrations/scada-energy-edge/setup',
            'integrations/scada-energy-edge/step-1-parse-modbus-registers',
            'integrations/scada-energy-edge/step-2-filter-normalize-readings',
            'integrations/scada-energy-edge/step-3-classify-fault-events',
            'integrations/scada-energy-edge/step-4-route-to-destinations',
            'integrations/scada-energy-edge/complete-scada-integration',
            'integrations/scada-energy-edge/troubleshooting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Enterprise Migration',
      collapsible: true,
      collapsed: false,
      items: [
        'enterprise-migration/index',
        {
          type: 'category',
          label: 'DB2 to BigQuery',
          collapsible: true,
          collapsed: true,
          items: [
            'enterprise-migration/db2-to-bigquery/index',
            'enterprise-migration/db2-to-bigquery/setup',
            'enterprise-migration/db2-to-bigquery/step-1-add-lineage-metadata',
            'enterprise-migration/db2-to-bigquery/step-2-normalize-currency',
            'enterprise-migration/db2-to-bigquery/step-3-mask-account-numbers',
            'enterprise-migration/db2-to-bigquery/step-4-categorize-transactions',
            'enterprise-migration/db2-to-bigquery/step-5-standardize-schema',
            'enterprise-migration/db2-to-bigquery/step-6-validate-required-fields',
            'enterprise-migration/db2-to-bigquery/complete-pipeline',
            'enterprise-migration/db2-to-bigquery/troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Nightly Backup',
          collapsible: true,
          collapsed: true,
          items: [
            'enterprise-migration/nightly-backup/index',
            'enterprise-migration/nightly-backup/setup',
            'enterprise-migration/nightly-backup/step-1-extract-tables',
            'enterprise-migration/nightly-backup/step-2-add-metadata',
            'enterprise-migration/nightly-backup/step-3-calculate-checksum',
            'enterprise-migration/nightly-backup/step-4-route-to-storage',
            'enterprise-migration/nightly-backup/complete-pipeline',
            'enterprise-migration/nightly-backup/troubleshooting',
          ],
        },
      ],
    },
  ],
};

export default sidebars;