import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const db2ToBigqueryStages: Stage[] = [
  {
    id: 1,
    slug: 'add-lineage-metadata',
    title: 'Add lineage metadata',
    description:
      'Stamp each DB2 row with the source system, table, pipeline, extraction time, and node id for audit.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"ACCOUNT_NUMBER": "4532-1234-5678-9012",',
        indent: 1,
        key: 'ACCOUNT_NUMBER',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z"',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"ACCOUNT_NUMBER": "4532-1234-5678-9012",',
        indent: 1,
        key: 'ACCOUNT_NUMBER',
        valueType: 'string',
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
        type: 'added',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '}',
        indent: 1,
        type: 'added',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 2,
    slug: 'normalize-currency',
    title: 'Normalize currency',
    description:
      'Keep the original amount and currency, then convert to USD with the example rate table.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"ACCOUNT_NUMBER": "4532-1234-5678-9012",',
        indent: 1,
        key: 'ACCOUNT_NUMBER',
        valueType: 'string',
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 1,
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"ACCOUNT_NUMBER": "4532-1234-5678-9012",',
        indent: 1,
        key: 'ACCOUNT_NUMBER',
        valueType: 'string',
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
        type: 'added',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
        type: 'added',
      },
      {
        content: '"original_currency": "EUR"',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 3,
    slug: 'mask-account-numbers',
    title: 'Mask account numbers',
    description:
      'Replace the account number with a masked suffix and a truncated SHA-256 hash for joins.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"ACCOUNT_NUMBER": "4532-1234-5678-9012",',
        indent: 1,
        key: 'ACCOUNT_NUMBER',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR"',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR"',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 4,
    slug: 'categorize-transactions',
    title: 'Categorize transactions',
    description:
      'Map the merchant category code prefix to a transaction category.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR"',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR",',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_category": "GROCERY"',
        indent: 1,
        key: 'transaction_category',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 5,
    slug: 'standardize-schema',
    title: 'Standardize schema',
    description:
      'Rename the DB2 columns to the BigQuery schema and add the daily partition field.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"AMOUNT": 125.5,',
        indent: 1,
        key: 'AMOUNT',
        valueType: 'number',
        type: 'removed',
      },
      {
        content: '"CREATED_AT": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'CREATED_AT',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"CURRENCY": "EUR",',
        indent: 1,
        key: 'CURRENCY',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"CUSTOMER_ID": "CUST-789012",',
        indent: 1,
        key: 'CUSTOMER_ID',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"MERCHANT_CATEGORY_CODE": "5411",',
        indent: 1,
        key: 'MERCHANT_CATEGORY_CODE',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"MERCHANT_NAME": "ACME Electronics GmbH",',
        indent: 1,
        key: 'MERCHANT_NAME',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"SOURCE_SYSTEM": "CORE_BANKING_EU",',
        indent: 1,
        key: 'SOURCE_SYSTEM',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"TRANSACTION_DATE": "2024-01-15",',
        indent: 1,
        key: 'TRANSACTION_DATE',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"TRANSACTION_ID": "TXN-2024-00123456",',
        indent: 1,
        key: 'TRANSACTION_ID',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"TRANSACTION_TYPE": "PURCHASE",',
        indent: 1,
        key: 'TRANSACTION_TYPE',
        valueType: 'string',
        type: 'removed',
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR",',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '"transaction_category": "GROCERY"',
        indent: 1,
        key: 'transaction_category',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_partition_date": "2024-01-15",',
        indent: 1,
        key: '_partition_date',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"created_at": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"customer_id": "CUST-789012",',
        indent: 1,
        key: 'customer_id',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"merchant_category_code": "5411",',
        indent: 1,
        key: 'merchant_category_code',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"merchant_name": "ACME Electronics GmbH",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR",',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '"source_system": "CORE_BANKING_EU",',
        indent: 1,
        key: 'source_system',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"transaction_category": "GROCERY",',
        indent: 1,
        key: 'transaction_category',
        valueType: 'string',
      },
      {
        content: '"transaction_date": "2024-01-15",',
        indent: 1,
        key: 'transaction_date',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"transaction_id": "TXN-2024-00123456",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"transaction_type": "PURCHASE"',
        indent: 1,
        key: 'transaction_type',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 6,
    slug: 'validate-required-fields',
    title: 'Validate required fields',
    description:
      'Reject any row missing a transaction id, customer id, or USD amount before the load.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_partition_date": "2024-01-15",',
        indent: 1,
        key: '_partition_date',
        valueType: 'string',
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"created_at": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"customer_id": "CUST-789012",',
        indent: 1,
        key: 'customer_id',
        valueType: 'string',
      },
      {
        content: '"merchant_category_code": "5411",',
        indent: 1,
        key: 'merchant_category_code',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "ACME Electronics GmbH",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR",',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '"source_system": "CORE_BANKING_EU",',
        indent: 1,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"transaction_category": "GROCERY",',
        indent: 1,
        key: 'transaction_category',
        valueType: 'string',
      },
      {
        content: '"transaction_date": "2024-01-15",',
        indent: 1,
        key: 'transaction_date',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-2024-00123456",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_type": "PURCHASE"',
        indent: 1,
        key: 'transaction_type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_lineage": {',
        indent: 1,
        key: '_lineage',
        valueType: 'object',
      },
      {
        content: '"extracted_at": "2026-10-05T18:24:41.888949-07:00",',
        indent: 2,
        key: 'extracted_at',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"node_id": "unknown",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "db2-to-bigquery-transactions",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"source_system": "DB2_PROD",',
        indent: 2,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"source_table": "TRANSACTIONS"',
        indent: 2,
        key: 'source_table',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_partition_date": "2024-01-15",',
        indent: 1,
        key: '_partition_date',
        valueType: 'string',
      },
      {
        content: '"account_number_hash": "a14c7c916ce2f1ad",',
        indent: 1,
        key: 'account_number_hash',
        valueType: 'string',
      },
      {
        content: '"account_number_masked": "****-****-9012",',
        indent: 1,
        key: 'account_number_masked',
        valueType: 'string',
      },
      {
        content: '"amount_usd": 135.54,',
        indent: 1,
        key: 'amount_usd',
        valueType: 'number',
      },
      {
        content: '"created_at": "2024-01-15T14:32:17Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"customer_id": "CUST-789012",',
        indent: 1,
        key: 'customer_id',
        valueType: 'string',
      },
      {
        content: '"merchant_category_code": "5411",',
        indent: 1,
        key: 'merchant_category_code',
        valueType: 'string',
      },
      {
        content: '"merchant_name": "ACME Electronics GmbH",',
        indent: 1,
        key: 'merchant_name',
        valueType: 'string',
      },
      {
        content: '"original_amount": 125.5,',
        indent: 1,
        key: 'original_amount',
        valueType: 'number',
      },
      {
        content: '"original_currency": "EUR",',
        indent: 1,
        key: 'original_currency',
        valueType: 'string',
      },
      {
        content: '"source_system": "CORE_BANKING_EU",',
        indent: 1,
        key: 'source_system',
        valueType: 'string',
      },
      {
        content: '"transaction_category": "GROCERY",',
        indent: 1,
        key: 'transaction_category',
        valueType: 'string',
      },
      {
        content: '"transaction_date": "2024-01-15",',
        indent: 1,
        key: 'transaction_date',
        valueType: 'string',
      },
      {
        content: '"transaction_id": "TXN-2024-00123456",',
        indent: 1,
        key: 'transaction_id',
        valueType: 'string',
      },
      {
        content: '"transaction_type": "PURCHASE"',
        indent: 1,
        key: 'transaction_type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
      {
        content: '',
        indent: 0,
      },
      {
        content: '# Required fields present: row accepted for load',
        indent: 0,
        type: 'highlighted',
      },
    ],
  },
];
