import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const nightlyBackupStages: Stage[] = [
  {
    id: 1,
    slug: 'extract-multiple-tables',
    title: 'Extract multiple tables',
    description:
      'Read the orders, inventory, and order_items extracts in sequence and tag each row with its table and backup type.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"customer_id": 4471,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"status": "shipped",',
        indent: 1,
        key: 'status',
        valueType: 'string',
      },
      {
        content: '"total": 189.95,',
        indent: 1,
        key: 'total',
        valueType: 'number',
      },
      {
        content: '"currency": "USD",',
        indent: 1,
        key: 'currency',
        valueType: 'string',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"updated_at": "2024-01-15T08:03:22Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"sku": "SKU-20481",',
        indent: 1,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"warehouse": "WH-NORTH",',
        indent: 1,
        key: 'warehouse',
        valueType: 'string',
      },
      {
        content: '"quantity_on_hand": 312,',
        indent: 1,
        key: 'quantity_on_hand',
        valueType: 'number',
      },
      {
        content: '"reorder_point": 80,',
        indent: 1,
        key: 'reorder_point',
        valueType: 'number',
      },
      {
        content: '"updated_at": "2024-01-15T06:00:00Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"item_id": 550912,',
        indent: 1,
        key: 'item_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-20481",',
        indent: 1,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"quantity": 2,',
        indent: 1,
        key: 'quantity',
        valueType: 'number',
      },
      {
        content: '"unit_price": 89.99,',
        indent: 1,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z"',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_type": "incremental",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"_table": "orders",',
        indent: 1,
        key: '_table',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"currency": "USD",',
        indent: 1,
        key: 'currency',
        valueType: 'string',
      },
      {
        content: '"customer_id": 4471,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"status": "shipped",',
        indent: 1,
        key: 'status',
        valueType: 'string',
      },
      {
        content: '"total": 189.95,',
        indent: 1,
        key: 'total',
        valueType: 'number',
      },
      {
        content: '"updated_at": "2024-01-15T08:03:22Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_type": "full",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"_table": "inventory",',
        indent: 1,
        key: '_table',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"quantity_on_hand": 312,',
        indent: 1,
        key: 'quantity_on_hand',
        valueType: 'number',
      },
      {
        content: '"reorder_point": 80,',
        indent: 1,
        key: 'reorder_point',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-20481",',
        indent: 1,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"updated_at": "2024-01-15T06:00:00Z",',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '"warehouse": "WH-NORTH"',
        indent: 1,
        key: 'warehouse',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_type": "incremental",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"_table": "order_items",',
        indent: 1,
        key: '_table',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"item_id": 550912,',
        indent: 1,
        key: 'item_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"quantity": 2,',
        indent: 1,
        key: 'quantity',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-20481",',
        indent: 1,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 89.99',
        indent: 1,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 2,
    slug: 'add-backup-metadata',
    title: 'Add backup metadata',
    description:
      'Attach the backup date, timestamp, source host, database, pipeline version, and node id to every row.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_type": "incremental",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
      },
      {
        content: '"_table": "orders",',
        indent: 1,
        key: '_table',
        valueType: 'string',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"currency": "USD",',
        indent: 1,
        key: 'currency',
        valueType: 'string',
      },
      {
        content: '"customer_id": 4471,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"status": "shipped",',
        indent: 1,
        key: 'status',
        valueType: 'string',
      },
      {
        content: '"total": 189.95,',
        indent: 1,
        key: 'total',
        valueType: 'number',
      },
      {
        content: '"updated_at": "2024-01-15T08:03:22Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_metadata": {',
        indent: 1,
        key: '_backup_metadata',
        valueType: 'object',
        type: 'added',
      },
      {
        content: '"backup_date": "2026-10-05",',
        indent: 2,
        key: 'backup_date',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"backup_timestamp": "2026-10-05T17:35:16.247802-07:00",',
        indent: 2,
        key: 'backup_timestamp',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"node_id": "backup-node-1",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"pipeline_version": "1.0.0",',
        indent: 2,
        key: 'pipeline_version',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"source_database": "ecommerce",',
        indent: 2,
        key: 'source_database',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"source_host": "postgres.internal.corp"',
        indent: 2,
        key: 'source_host',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '},',
        indent: 1,
        type: 'added',
      },
      {
        content: '"_backup_type": "incremental",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
      },
      {
        content: '"_table": "orders",',
        indent: 1,
        key: '_table',
        valueType: 'string',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"currency": "USD",',
        indent: 1,
        key: 'currency',
        valueType: 'string',
      },
      {
        content: '"customer_id": 4471,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"status": "shipped",',
        indent: 1,
        key: 'status',
        valueType: 'string',
      },
      {
        content: '"total": 189.95,',
        indent: 1,
        key: 'total',
        valueType: 'number',
      },
      {
        content: '"updated_at": "2024-01-15T08:03:22Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 3,
    slug: 'calculate-checksum',
    title: 'Calculate checksum',
    description:
      'Hash the original columns, excluding the backup fields, so a restore can verify each row.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_metadata": {',
        indent: 1,
        key: '_backup_metadata',
        valueType: 'object',
      },
      {
        content: '"backup_date": "2026-10-05",',
        indent: 2,
        key: 'backup_date',
        valueType: 'string',
      },
      {
        content: '"backup_timestamp": "2026-10-05T17:35:16.247802-07:00",',
        indent: 2,
        key: 'backup_timestamp',
        valueType: 'string',
      },
      {
        content: '"node_id": "backup-node-1",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline_version": "1.0.0",',
        indent: 2,
        key: 'pipeline_version',
        valueType: 'string',
      },
      {
        content: '"source_database": "ecommerce",',
        indent: 2,
        key: 'source_database',
        valueType: 'string',
      },
      {
        content: '"source_host": "postgres.internal.corp"',
        indent: 2,
        key: 'source_host',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_backup_type": "incremental",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
      },
      {
        content: '"_table": "orders",',
        indent: 1,
        key: '_table',
        valueType: 'string',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"currency": "USD",',
        indent: 1,
        key: 'currency',
        valueType: 'string',
      },
      {
        content: '"customer_id": 4471,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"status": "shipped",',
        indent: 1,
        key: 'status',
        valueType: 'string',
      },
      {
        content: '"total": 189.95,',
        indent: 1,
        key: 'total',
        valueType: 'number',
      },
      {
        content: '"updated_at": "2024-01-15T08:03:22Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"_backup_metadata": {',
        indent: 1,
        key: '_backup_metadata',
        valueType: 'object',
      },
      {
        content: '"backup_date": "2026-10-05",',
        indent: 2,
        key: 'backup_date',
        valueType: 'string',
      },
      {
        content: '"backup_timestamp": "2026-10-05T17:35:16.274968-07:00",',
        indent: 2,
        key: 'backup_timestamp',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"node_id": "backup-node-1",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline_version": "1.0.0",',
        indent: 2,
        key: 'pipeline_version',
        valueType: 'string',
      },
      {
        content: '"source_database": "ecommerce",',
        indent: 2,
        key: 'source_database',
        valueType: 'string',
      },
      {
        content: '"source_host": "postgres.internal.corp"',
        indent: 2,
        key: 'source_host',
        valueType: 'string',
      },
      {
        content: '},',
        indent: 1,
      },
      {
        content: '"_backup_type": "incremental",',
        indent: 1,
        key: '_backup_type',
        valueType: 'string',
      },
      {
        content: '"_checksum": "de4bd45a0d46a3ac1a2b1a702ad93380",',
        indent: 1,
        key: '_checksum',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"_table": "orders",',
        indent: 1,
        key: '_table',
        valueType: 'string',
      },
      {
        content: '"created_at": "2024-01-14T16:42:10Z",',
        indent: 1,
        key: 'created_at',
        valueType: 'string',
      },
      {
        content: '"currency": "USD",',
        indent: 1,
        key: 'currency',
        valueType: 'string',
      },
      {
        content: '"customer_id": 4471,',
        indent: 1,
        key: 'customer_id',
        valueType: 'number',
      },
      {
        content: '"order_id": 100231,',
        indent: 1,
        key: 'order_id',
        valueType: 'number',
      },
      {
        content: '"status": "shipped",',
        indent: 1,
        key: 'status',
        valueType: 'string',
      },
      {
        content: '"total": 189.95,',
        indent: 1,
        key: 'total',
        valueType: 'number',
      },
      {
        content: '"updated_at": "2024-01-15T08:03:22Z"',
        indent: 1,
        key: 'updated_at',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 4,
    slug: 'route-to-storage',
    title: 'Route to storage',
    description:
      'Switch on the table tag to a dated object path per table. Cloud delivery has not been exercised.',
    inputLines: [
      {
        content: '[Checksummed rows]',
        indent: 0,
        type: 'comment',
      },
      {
        content: '• _table: orders (incremental)',
        indent: 0,
      },
      {
        content: '• _table: inventory (full)',
        indent: 0,
      },
      {
        content: '• _table: order_items (incremental)',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '# Routed object paths from the sample run',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '• backups/inventory/2026-10-05/inventory-full.parquet',
        indent: 0,
      },
      {
        content: '• backups/order_items/2026-10-05/items-1791246916.parquet',
        indent: 0,
      },
      {
        content: '• backups/orders/2026-10-05/orders-1791246916.parquet',
        indent: 0,
      },
      {
        content: '',
        indent: 0,
      },
      {
        content: '# Storage class: NEARLINE, Parquet with SNAPPY compression',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# Batching: 10000 rows or 60s; inventory 50000 rows or 120s',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# Delivery behavior: not assessed',
        indent: 0,
        type: 'highlighted',
      },
    ],
  },
];
