/**
 * Generated by scripts/generate-explorer-stage-configs.ts.
 * Do not edit: provenance is derived from the canonical stage manifest.
 */
import type { ExplorerEvidence } from "./schema";

export const GENERATED_ARCHITECTURE_EXPLORER_EVIDENCE: Readonly<
  Record<string, ExplorerEvidence>
> = {
  "circuit-breakers": {
    exampleId: "circuit-breakers",
    kind: "curated-explanation",
    verificationId: "circuit-breakers-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/circuit-breakers.yaml",
    pipelineSha256:
      "sha256:5dd4ae56184dd5bfd70d5470cdaa8780760fe9a4bff047c8947874b820c83c6c",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-routing/circuit-breakers-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:49ac89a7747e33fb5477d9e92a6fb7b99e6679cc26a7cdbe7e41fda7be9c54f9",
    inputCheckpointPath:
      "examples/explorer-stages/circuit-breakers/01-no-circuit-breakers.yaml",
    inputCheckpointSha256:
      "sha256:83fadd7a12b764bf1515eaa70cae1b36dab417338de5e7a2f04117b0bc59fd70",
    outputCheckpointPath:
      "examples/explorer-stages/circuit-breakers/04-multi-level-fallback.yaml",
    outputCheckpointSha256:
      "sha256:e93b93c9cfd39c37cd82cb8b2280fc2869141f2eccf1a4e771bb9eb16811d4de",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "adversarial-verifier",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "content-routing": {
    exampleId: "content-routing",
    kind: "curated-explanation",
    verificationId: "content-routing-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/content-routing.yaml",
    pipelineSha256:
      "sha256:c595c3b16b9cd8b89f9f435edbba672b7ee6efa18185fcdd76eeed761740504d",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/data-routing/content-routing-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:1a5675a5af6a4409fe981eca02ef3c19f1133bcf42b7578cbf827dcdf319a107",
    inputCheckpointPath:
      "examples/explorer-stages/content-routing/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:8e3d28602e945da4b472dea79f5588d2542e0f7501a4cf63af2bf21445ebfd5e",
    outputCheckpointPath:
      "examples/explorer-stages/content-routing/05-priority-queue-routing.yaml",
    outputCheckpointSha256:
      "sha256:fbca7dac219f536a5a56dd7a402e328f3ba826bd075daa535416b48268cd192d",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "accessibility",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "content-splitting": {
    exampleId: "content-splitting",
    kind: "curated-explanation",
    verificationId: "content-splitting-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/content-splitting.yaml",
    pipelineSha256:
      "sha256:6de04ba60b03612b3da765b104c5fcf5abc72c6aea2d442bd353110dff48bfb5",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-routing/content-splitting-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:4f329c05a9ff1b05dbd115b725d9b2205516c7cbe2dae1e5904ba1dfadf0aba5",
    inputCheckpointPath:
      "examples/explorer-stages/content-splitting/01-original-bundled-message.yaml",
    inputCheckpointSha256:
      "sha256:c12e0555d53f86ceee23792abc38b5abcbb1600475aea8500d45d796637e2c5c",
    outputCheckpointPath:
      "examples/explorer-stages/content-splitting/05-content-based-routing.yaml",
    outputCheckpointSha256:
      "sha256:c9790194e0ae3799eacfaf2f70a916810356f520d7f51e58689c291b64bda153",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "fan-out-pattern": {
    exampleId: "fan-out-pattern",
    kind: "curated-explanation",
    verificationId: "fan-out-pattern-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/fan-out-pattern.yaml",
    pipelineSha256:
      "sha256:41dc3f06790b26c604923974da5548261313ac8224aa74538702c9b1dd0c208b",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/data-routing/fan-out-pattern-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:55c0f26d7556d31ca1c4501d2baa6325d840a5d53f9ddf11a41edff28309be7e",
    inputCheckpointPath:
      "examples/explorer-stages/fan-out-pattern/01-single-destination.yaml",
    inputCheckpointSha256:
      "sha256:32fb86446323d6862c430126475a0130da3ed8cf0c2baa32a7025e22ecd1ec90",
    outputCheckpointPath:
      "examples/explorer-stages/fan-out-pattern/05-elasticsearch-search-analytics.yaml",
    outputCheckpointSha256:
      "sha256:2d4e4d12c18e20babe59f304eac17527456f7a956ce24c75feee34b810de3dda",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "priority-queues": {
    exampleId: "priority-queues",
    kind: "curated-explanation",
    verificationId: "priority-queues-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/priority-queues.yaml",
    pipelineSha256:
      "sha256:d19a7f07daeeff82c39d24110dbc6a35320ac6c52a7af0e4298e62ce3eec8daa",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/data-routing/priority-queues-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:1039005ea5ce6b4dc6c78c930dcd2be75e5fd8e5b3afaed76d6bfb131b66e28e",
    inputCheckpointPath:
      "examples/explorer-stages/priority-queues/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:4d003feaa77e2698c420a5cd0ad81472db125405d2e63aeaf420ca6da1a28a36",
    outputCheckpointPath:
      "examples/explorer-stages/priority-queues/04-multi-criteria-scoring.yaml",
    outputCheckpointSha256:
      "sha256:8722f0a0a35a2c5e8d042a0237a49ab082d23e9c5936508ae2e0319c785c490c",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "smart-buffering": {
    exampleId: "smart-buffering",
    kind: "curated-explanation",
    verificationId: "smart-buffering-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "examples/data-routing/smart-buffering.yaml",
    pipelineSha256:
      "sha256:63c2d06947c77264be9d50c800b7d492c4e0cd385a3ba13db8621dde4b3cd4eb",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/data-routing/smart-buffering-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:db5162e88c98180b4c34c86c0cba5516ec9afe981eab9f2c05387ad161d48616",
    inputCheckpointPath:
      "examples/explorer-stages/smart-buffering/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:472160f35af62c9a892dd0da9ca8afffa2218bca76c7b85b7a0a46e4b2deeed6",
    outputCheckpointPath:
      "examples/explorer-stages/smart-buffering/04-starvation-prevention.yaml",
    outputCheckpointSha256:
      "sha256:7989600c812a859e9d05b30fa5f9de8f8970d046c376f0610c9968ee3c26e511",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "adversarial-verifier",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "encrypt-data": {
    exampleId: "encrypt-data",
    kind: "curated-explanation",
    verificationId: "encrypt-data-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-security/encrypt-data.yaml",
    pipelineSha256:
      "sha256:071495619b7afaee8c7b2a919bbae258ffe99cdc03e031cff2656b855724b321",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/data-security/encrypt-data-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:9ec34d1b46ed0ccc3bcb27dc4914ed3292b823b85d00c138ad193130d2377f5d",
    inputCheckpointPath:
      "examples/explorer-stages/encrypt-data/01-original-payment-data.yaml",
    inputCheckpointSha256:
      "sha256:6743ff1acbce9aaffa1fdd00cc0f41bc6a7f4af988c41152a1f6f6a691063a94",
    outputCheckpointPath:
      "examples/explorer-stages/encrypt-data/06-complete-encrypted-transaction.yaml",
    outputCheckpointSha256:
      "sha256:931b1c14e7de83831f7f2c8a1e31e7b6266b7ed5d3f5126ab4bc28adabe78ffe",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "claims-evidence",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "encryption-patterns": {
    exampleId: "encryption-patterns",
    kind: "curated-explanation",
    verificationId: "encryption-patterns-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-security/encryption-patterns.yaml",
    pipelineSha256:
      "sha256:6168df047594dcf7124294dd4ce43f1f11ff398806a81db01aca955a79f40357",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-security/encryption-patterns-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:6674ea19368255905674b34a86bbf2bff23ded983d8352135ed3db83eb296aa3",
    inputCheckpointPath:
      "examples/explorer-stages/encryption-patterns/01-original-sensitive-data.yaml",
    inputCheckpointSha256:
      "sha256:9bd508ab3242bf1a81767c75899a376b53d75da2e22a00dcb15713459bb5340a",
    outputCheckpointPath:
      "examples/explorer-stages/encryption-patterns/06-illustrative-key-version-metadata.yaml",
    outputCheckpointSha256:
      "sha256:ae63e6792ec785ff61bcab4dff7e4e1dcc84ba73e751fdebbb48be6da19e59d9",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "enforce-schema": {
    exampleId: "enforce-schema",
    kind: "curated-explanation",
    verificationId: "enforce-schema-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-security/enforce-schema.yaml",
    pipelineSha256:
      "sha256:cd6a6cecdccaef3a777ecacfdb242e4a09b68f4cd2fb32ca40880127575f96f6",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/data-security/enforce-schema-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:7820e5ce3703f4b4e2273260df972a7c0e3ce1436078fa88e342ff25c09eb0f9",
    inputCheckpointPath:
      "examples/explorer-stages/enforce-schema/01-no-validation.yaml",
    inputCheckpointSha256:
      "sha256:286745b29627d6f2e008c7ab3200529ef41fc1bab17fdee59b565ee4d11e027b",
    outputCheckpointPath:
      "examples/explorer-stages/enforce-schema/04-monitor-quality.yaml",
    outputCheckpointSha256:
      "sha256:b43e7bc06d37408c757498a2714057f3dcef259431fee5d1e4512d788a47ca15",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "aggregate-time-windows": {
    exampleId: "aggregate-time-windows",
    kind: "curated-explanation",
    verificationId: "aggregate-time-windows-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/aggregate-time-windows.yaml",
    pipelineSha256:
      "sha256:89746470b5a90fc37ad5cb8b4f9655f2a8e482c42117b84851761d29bfcdb7a6",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-transformation/aggregate-time-windows-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:c10f199bc3fb4cec0b0544c74d8aab8f1721b15b3b2252ca82372c3a7abea214",
    inputCheckpointPath:
      "examples/explorer-stages/aggregate-time-windows/01-original-high-frequency-events.yaml",
    inputCheckpointSha256:
      "sha256:ad56f7df1414bb064b9a470a703c18275c7a333bf9ed0ee82490a93a76036916",
    outputCheckpointPath:
      "examples/explorer-stages/aggregate-time-windows/05-multi-level-configuration.yaml",
    outputCheckpointSha256:
      "sha256:98f3b4760cbaa01b56e6de78315655a809ed8962493eca676539cc754d97d6af",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "design",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "deduplicate-events": {
    exampleId: "deduplicate-events",
    kind: "curated-explanation",
    verificationId: "deduplicate-events-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/deduplicate-events.yaml",
    pipelineSha256:
      "sha256:60add2250283bb8db5bbef88de78e7d98eb655b8dd4b7056fdb3b167e5e25f11",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-transformation/deduplicate-events-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:8aadea6f846c55c9a11080b0879168efc80496ad8c21c691c50365f94aef37d5",
    inputCheckpointPath:
      "examples/explorer-stages/deduplicate-events/01-original-events.yaml",
    inputCheckpointSha256:
      "sha256:6de77bb2ce570b57b415631fd8087f2808abd3a8521ef25bd3c72ffb92ec3b8d",
    outputCheckpointPath:
      "examples/explorer-stages/deduplicate-events/05-external-cache-configuration.yaml",
    outputCheckpointSha256:
      "sha256:a9cf67e6229244d95a5ab1ea2b01679073e401e66fa5f103a96c7be58a35b902",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "normalize-timestamps": {
    exampleId: "normalize-timestamps",
    kind: "curated-explanation",
    verificationId: "normalize-timestamps-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/normalize-timestamps.yaml",
    pipelineSha256:
      "sha256:7e324ff69281e22bca0e9633c3b17397fcb3e249382b35d642b4eb7de73bc975",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-transformation/normalize-timestamps-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:d6a39502c1b9045549df8b8e1b870556995918218023e7a6bc0d2128213722d4",
    inputCheckpointPath:
      "examples/explorer-stages/normalize-timestamps/01-mixed-timestamp-formats.yaml",
    inputCheckpointSha256:
      "sha256:7c15e2ab90cb624c3578490e50d650968b1f8377d2663b45345dc9504a9f747a",
    outputCheckpointPath:
      "examples/explorer-stages/normalize-timestamps/03-normalize-to-utc-metadata.yaml",
    outputCheckpointSha256:
      "sha256:3f8427929470a759bb1f5bda31df5fe31f18f3b67fe4a44e85f44543b238ed2b",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 3,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "parse-logs": {
    exampleId: "parse-logs",
    kind: "curated-explanation",
    verificationId: "parse-logs-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-transformation/parse-logs.yaml",
    pipelineSha256:
      "sha256:3f62d7b7baf8a623cf7e866acf29025ccc8077b8956386e7aa94a513f2847340",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-transformation/parse-logs-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:a11089829f4cdcfcf2ac25b39e7f9fa56545f90247c2f1baeb5f4ac2c8f819af",
    inputCheckpointPath:
      "examples/explorer-stages/parse-logs/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:e486bb8b301ec8a2c2f10fcc419b9aab7ded32d32ac6132daeeace1fedd02937",
    outputCheckpointPath:
      "examples/explorer-stages/parse-logs/06-syslog-message-parsing.yaml",
    outputCheckpointSha256:
      "sha256:ddec41600e2a2f5a76d3f2d7f0370ae42bb5541052583ae2caddb68b02ad889d",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "transform-formats": {
    exampleId: "transform-formats",
    kind: "curated-explanation",
    verificationId: "transform-formats-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/transform-formats.yaml",
    pipelineSha256:
      "sha256:e7415053cd173903b675bd86b5b0c0acaadf7ecee1941c2f343794fcdf95e611",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/data-transformation/transform-formats-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:fd0f107f4033326219e02efd810ffc72f63e0d43c06434f5bdba39549ab430cd",
    inputCheckpointPath:
      "examples/explorer-stages/transform-formats/01-json-input.yaml",
    inputCheckpointSha256:
      "sha256:97bf3c31922063b8a4c1e2756d9046874a5ab5f5a3328dc84fb14556fccb9973",
    outputCheckpointPath:
      "examples/explorer-stages/transform-formats/04-auto-detection.yaml",
    outputCheckpointSha256:
      "sha256:a82fdfc35a5a7f2456c9765018e7a5e25664da235822f2ba7c710bc76be68bea",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "oran-telco-pipeline": {
    exampleId: "oran-telco-pipeline",
    kind: "curated-explanation",
    verificationId: "oran-telco-pipeline-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/pipelines/oran-telco-pipeline.yaml",
    pipelineSha256:
      "sha256:86a929ce688db395b9f2125c106a407054c9d9c1e5f8100fd277e04cf2261e0c",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/integrations/oran-telco-pipeline-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:9f1e5c6d76b638203991f0534a8e5c3f04159ae4b47af668f6f13858fa542041",
    inputCheckpointPath:
      "examples/explorer-stages/oran-telco-pipeline/01-adapter-output.yaml",
    inputCheckpointSha256:
      "sha256:594a09342e6810f7ccbfa22ce33b476e10f71a3d6c3ad072f76e09c038e1e47c",
    outputCheckpointPath:
      "examples/explorer-stages/oran-telco-pipeline/05-external-destinations.yaml",
    outputCheckpointSha256:
      "sha256:f6b22ce00a1652bad9fe68eb4a63bc08005ae511917c6755c5f115756f58921d",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "claims-evidence",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "scada-energy-edge": {
    exampleId: "scada-energy-edge",
    kind: "curated-explanation",
    verificationId: "scada-energy-edge-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/integrations/scada-energy-edge/scada-edge-complete.yaml",
    pipelineSha256:
      "sha256:99f04b0a58f6be9534114a4589239eade0b124564669ca883e2893902869fc8d",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/integrations/scada-energy-edge/stages.ts",
    authoredStageModuleSha256:
      "sha256:446bc7bd03a136db8329f0f82c1122363c85e8bda3962a7e539f1284299c814c",
    inputCheckpointPath:
      "examples/explorer-stages/scada-energy-edge/01-adapter-output.yaml",
    inputCheckpointSha256:
      "sha256:9a58a99f3035c80fb49d9eac3c1c46a8ec346ce125438d67ac82f9bf68fd3c90",
    outputCheckpointPath:
      "examples/explorer-stages/scada-energy-edge/04-route-selected-records.yaml",
    outputCheckpointSha256:
      "sha256:60d2e9f3cd55fa42253a7ccd5cd5216a8ebf9a57a6d3506c5df932b39822bb80",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "claims-evidence",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "splunk-edge-processing": {
    exampleId: "splunk-edge-processing",
    kind: "curated-explanation",
    verificationId: "splunk-edge-processing-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/pipelines/splunk-production-pipeline.yaml",
    pipelineSha256:
      "sha256:552f3151ccd533a78640631d64be14d9834a757faeed49ba4678244777917dec",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/integrations/splunk-edge-processing-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:dd1f8a111531a46f65f0c712e04ce4b75305f59b317e377c8749aa6b38966cbc",
    inputCheckpointPath:
      "examples/explorer-stages/splunk-edge-processing/01-authored-log-fixture.yaml",
    inputCheckpointSha256:
      "sha256:ffdb036b4ded462cd7880a385814a5c27888d89482cf268f179fe543c0fb72ff",
    outputCheckpointPath:
      "examples/explorer-stages/splunk-edge-processing/05-route-to-splunk-hec.yaml",
    outputCheckpointSha256:
      "sha256:ed5233456338033dd251802fe305ac08e398c0bb7eb7227caa0434d2e1cd77ad",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "enrich-export": {
    exampleId: "enrich-export",
    kind: "curated-explanation",
    verificationId: "enrich-export-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/log-processing/enrich-export-complete.yaml",
    pipelineSha256:
      "sha256:66db919d9d41eb2a34996f73fb240aebe645a069ed04b11f4336637c539814c8",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath: "docs/log-processing/enrich-export-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:397f4e39cf4ebf3a49f36b11932e3f3b031a4407c11f2b3ae9169c06d983d968",
    inputCheckpointPath:
      "examples/explorer-stages/enrich-export/01-original-log-data.yaml",
    inputCheckpointSha256:
      "sha256:d3771400d8f05e2dde64ad32f3410e261b18d536393011e6abb2c646373ed599",
    outputCheckpointPath:
      "examples/explorer-stages/enrich-export/05-configured-s3-object.yaml",
    outputCheckpointSha256:
      "sha256:86038968fa45f05ab5f6e66cf724388282a76feb8d2cd660d74c2193abb4242c",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "filter-severity": {
    exampleId: "filter-severity",
    kind: "curated-explanation",
    verificationId: "filter-severity-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/log-processing/filter-severity-complete.yaml",
    pipelineSha256:
      "sha256:8418ab291903c1398a008e421c8dde6ae27e9ff12eca630516950a329c879b34",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/log-processing/filter-severity-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:c0b8699d420f2371fabcf229785dfd203e5c4a26b22648be70638839e8cfb489",
    inputCheckpointPath:
      "examples/explorer-stages/filter-severity/01-all-log-levels-mixed.yaml",
    inputCheckpointSha256:
      "sha256:f28f07c239171d3041291ecd7dfad3adce2e47510c8099117d8836abb79eab7d",
    outputCheckpointPath:
      "examples/explorer-stages/filter-severity/03-filter-route.yaml",
    outputCheckpointSha256:
      "sha256:73ba586f4f992a3c7497e329db28e377182ce7704d4f0cca4c2c0b6e43ea7097",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 3,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "production-pipeline": {
    exampleId: "production-pipeline",
    kind: "curated-explanation",
    verificationId: "production-pipeline-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/log-processing/production-pipeline-complete.yaml",
    pipelineSha256:
      "sha256:fbc222f7db1bf8d74ebb6231ac9d1ed76b34eec98852534918096cf03e6e217b",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:3a980e68e8ace35cab469035aaedd8b0cf051d09bdf9e28641c3d38d3f31f9b4",
    authoredStageModulePath:
      "docs/log-processing/production-pipeline-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:9bf9e19abead607427709d177313df3801fedcf7c5b3c8e28f9256951a2d698b",
    inputCheckpointPath:
      "examples/explorer-stages/production-pipeline/01-raw-http-input.yaml",
    inputCheckpointSha256:
      "sha256:2a7d89c43e0c2156a1400755f46990fb66d709bcb8632b90922a62a9db25641b",
    outputCheckpointPath:
      "examples/explorer-stages/production-pipeline/06-fan-out.yaml",
    outputCheckpointSha256:
      "sha256:a80da07c050db7af714a8cbb69e2ea64be9180551238b1aafa181776847664ba",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:aafec92275cabc9d88e35915b567df98b4b9f906c6bbf5dc2d7343660a0e546d",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
};
