/**
 * Generated by scripts/generate-explorer-stage-configs.ts.
 * Do not edit: provenance is derived from the canonical stage manifest.
 */
import type { ExplorerEvidence } from "./schema";

export const GENERATED_ARCHITECTURE_EXPLORER_EVIDENCE: Readonly<
  Record<string, ExplorerEvidence>
> = {
  "circuit-breakers": {
    exampleId: "circuit-breakers",
    kind: "curated-explanation",
    verificationId: "circuit-breakers-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/circuit-breakers.yaml",
    pipelineSha256:
      "sha256:c41a5c65c6795da6ce8996bf428fd517e6ec21fcec6331601ea42ce2e4b29428",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-routing/circuit-breakers-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:49ac89a7747e33fb5477d9e92a6fb7b99e6679cc26a7cdbe7e41fda7be9c54f9",
    inputCheckpointPath:
      "examples/explorer-stages/circuit-breakers/01-no-circuit-breakers.yaml",
    inputCheckpointSha256:
      "sha256:87bcd8413c2e947579b2413d6c8746a4ad3f039044fb81c90aebdc137f5987c3",
    outputCheckpointPath:
      "examples/explorer-stages/circuit-breakers/04-multi-level-fallback.yaml",
    outputCheckpointSha256:
      "sha256:9d6e44e4a092b0e15f067fd99064abc615fe22341f370a9a09f2d16f78ef66fc",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "adversarial-verifier",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "content-routing": {
    exampleId: "content-routing",
    kind: "curated-explanation",
    verificationId: "content-routing-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/content-routing.yaml",
    pipelineSha256:
      "sha256:317ea89a4c86d238dc8505f7ed7b0e8d15007fe47a5248d4ed365fa48bd875c3",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/data-routing/content-routing-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:1a5675a5af6a4409fe981eca02ef3c19f1133bcf42b7578cbf827dcdf319a107",
    inputCheckpointPath:
      "examples/explorer-stages/content-routing/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:36b68efa7184097942c4b885ff2f0d397efce5e2b6f16e77ddfb70a763556ecc",
    outputCheckpointPath:
      "examples/explorer-stages/content-routing/05-priority-queue-routing.yaml",
    outputCheckpointSha256:
      "sha256:11a9f411cee49f5a875ff9bcbed16b0d6f8451175df40fe647855ad7cef83e85",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "accessibility",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "content-splitting": {
    exampleId: "content-splitting",
    kind: "curated-explanation",
    verificationId: "content-splitting-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/content-splitting.yaml",
    pipelineSha256:
      "sha256:a785e677cfd4462da433840d5fc238814f47984eb55202156ae12c3b4b2440ab",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-routing/content-splitting-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:4f329c05a9ff1b05dbd115b725d9b2205516c7cbe2dae1e5904ba1dfadf0aba5",
    inputCheckpointPath:
      "examples/explorer-stages/content-splitting/01-original-bundled-message.yaml",
    inputCheckpointSha256:
      "sha256:c12e0555d53f86ceee23792abc38b5abcbb1600475aea8500d45d796637e2c5c",
    outputCheckpointPath:
      "examples/explorer-stages/content-splitting/05-content-based-routing.yaml",
    outputCheckpointSha256:
      "sha256:aca45819b13d349f7ce9bc09d012537a77d677460a02719d31f4312d1bcad4ca",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "fan-out-pattern": {
    exampleId: "fan-out-pattern",
    kind: "curated-explanation",
    verificationId: "fan-out-pattern-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/fan-out-pattern.yaml",
    pipelineSha256:
      "sha256:c050312ba1ef139845fed559ab94498a8c836006b65dbd9dff1b15c40efda930",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/data-routing/fan-out-pattern-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:55c0f26d7556d31ca1c4501d2baa6325d840a5d53f9ddf11a41edff28309be7e",
    inputCheckpointPath:
      "examples/explorer-stages/fan-out-pattern/01-single-destination.yaml",
    inputCheckpointSha256:
      "sha256:16427fdbeef3193d8adb9585fd99cf6cd00ae2118b7d810e0bc11441e7a4c571",
    outputCheckpointPath:
      "examples/explorer-stages/fan-out-pattern/05-elasticsearch-search-analytics.yaml",
    outputCheckpointSha256:
      "sha256:efa454dcf201fd5045e5c9b616c51ca2a1e58ad77ec5522936e57e2d7f88c8df",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "priority-queues": {
    exampleId: "priority-queues",
    kind: "curated-explanation",
    verificationId: "priority-queues-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-routing/priority-queues.yaml",
    pipelineSha256:
      "sha256:13a4f0871a3d56e27dfa2cecb10cd30121dbe898b431376ef3c00a3334fccd19",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/data-routing/priority-queues-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:1039005ea5ce6b4dc6c78c930dcd2be75e5fd8e5b3afaed76d6bfb131b66e28e",
    inputCheckpointPath:
      "examples/explorer-stages/priority-queues/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:047d94b630260cd66ccbd2b393fae6c44a2ba7598c8bca8ac7f55112c64171d8",
    outputCheckpointPath:
      "examples/explorer-stages/priority-queues/04-multi-criteria-scoring.yaml",
    outputCheckpointSha256:
      "sha256:8722f0a0a35a2c5e8d042a0237a49ab082d23e9c5936508ae2e0319c785c490c",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "smart-buffering": {
    exampleId: "smart-buffering",
    kind: "curated-explanation",
    verificationId: "smart-buffering-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "examples/data-routing/smart-buffering.yaml",
    pipelineSha256:
      "sha256:3353a6bccee138169ec572dc7a84a89ad6803e5f767f8fe381a290baef124b14",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/data-routing/smart-buffering-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:db5162e88c98180b4c34c86c0cba5516ec9afe981eab9f2c05387ad161d48616",
    inputCheckpointPath:
      "examples/explorer-stages/smart-buffering/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:6073d1714683e0a856a12abd27d7b257ed20a960353135151b0a33f4ef651680",
    outputCheckpointPath:
      "examples/explorer-stages/smart-buffering/04-starvation-prevention.yaml",
    outputCheckpointSha256:
      "sha256:7989600c812a859e9d05b30fa5f9de8f8970d046c376f0610c9968ee3c26e511",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "adversarial-verifier",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "cross-border-gdpr": {
    exampleId: "cross-border-gdpr",
    kind: "curated-explanation",
    verificationId: "cross-border-gdpr-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/data-security/cross-border-gdpr/cross-border-gdpr.yaml",
    pipelineSha256:
      "sha256:0858120242a67316f65afe30b12906b695d53b52511a1b39260acfc0df4bba97",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-security/cross-border-gdpr-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:777c33b36c68ce8668098c23b7a98c719c59c565457a6d45d576f6c520d850df",
    inputCheckpointPath:
      "examples/explorer-stages/cross-border-gdpr/01-tag-data-origin.yaml",
    inputCheckpointSha256:
      "sha256:63e16af19ab43dce4da5572b5e7f5404c14fe4b267f19322a757967273c1e47e",
    outputCheckpointPath:
      "examples/explorer-stages/cross-border-gdpr/06-validate-anonymization.yaml",
    outputCheckpointSha256:
      "sha256:f73cdc104f12c3f1f6437a23f738ddd25e597c70a8906652368677bb61a685d6",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "dataset-privacy",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "encrypt-data": {
    exampleId: "encrypt-data",
    kind: "curated-explanation",
    verificationId: "encrypt-data-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-security/encrypt-data.yaml",
    pipelineSha256:
      "sha256:8fe49db68b3a51445e7210f2d6d3a59d6a10f621ae7e85602a642c6bf73fa05c",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/data-security/encrypt-data-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:0e0e3878a1b8c762f50998922be9f069b3a5c2b6a5b03dcaa3e101a044ae375c",
    inputCheckpointPath:
      "examples/explorer-stages/encrypt-data/01-original-payment-data.yaml",
    inputCheckpointSha256:
      "sha256:bf3b0a8fd205711d4de26db7dc4ab806ed377834d874c50edf32b1a2fe1373c3",
    outputCheckpointPath:
      "examples/explorer-stages/encrypt-data/06-complete-encrypted-transaction.yaml",
    outputCheckpointSha256:
      "sha256:b05a6bfa3946d98631737bd2e5e2ed4550edc3e9b09857acf1a873bba8936578",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "claims-evidence",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "encryption-patterns": {
    exampleId: "encryption-patterns",
    kind: "curated-explanation",
    verificationId: "encryption-patterns-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-security/encryption-patterns.yaml",
    pipelineSha256:
      "sha256:3abf8933e922af7aeb4e6ef6155fb44f3572c7112ce6404df3359ddf5954cd30",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-security/encryption-patterns-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:ff293bc383e82a90754f5741ce04c107e94945a2c4e82cb4a0ba518adb80850a",
    inputCheckpointPath:
      "examples/explorer-stages/encryption-patterns/01-original-sensitive-data.yaml",
    inputCheckpointSha256:
      "sha256:5ed51180914b50e295c99b361e027d3a5f9e55d84f74c154bbf8c5221daa370b",
    outputCheckpointPath:
      "examples/explorer-stages/encryption-patterns/06-illustrative-key-version-metadata.yaml",
    outputCheckpointSha256:
      "sha256:16acfe1e07930a67e00a5a7dea62744f6c168d6070c16a8b6c25b493fbce9f13",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "enforce-schema": {
    exampleId: "enforce-schema",
    kind: "curated-explanation",
    verificationId: "enforce-schema-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-security/enforce-schema.yaml",
    pipelineSha256:
      "sha256:c8f8cfff712c002fe5c3525bb6f2ff4dcb6b2866f02c8056df318a056a2d2898",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/data-security/enforce-schema-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:7820e5ce3703f4b4e2273260df972a7c0e3ce1436078fa88e342ff25c09eb0f9",
    inputCheckpointPath:
      "examples/explorer-stages/enforce-schema/01-no-validation.yaml",
    inputCheckpointSha256:
      "sha256:286745b29627d6f2e008c7ab3200529ef41fc1bab17fdee59b565ee4d11e027b",
    outputCheckpointPath:
      "examples/explorer-stages/enforce-schema/04-monitor-quality.yaml",
    outputCheckpointSha256:
      "sha256:b43e7bc06d37408c757498a2714057f3dcef259431fee5d1e4512d788a47ca15",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "aggregate-time-windows": {
    exampleId: "aggregate-time-windows",
    kind: "curated-explanation",
    verificationId: "aggregate-time-windows-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/aggregate-time-windows.yaml",
    pipelineSha256:
      "sha256:d991b50db32425d674e8e88c88ae0109769da0ffcfea4946b4f9e0e74964034c",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-transformation/aggregate-time-windows-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:c10f199bc3fb4cec0b0544c74d8aab8f1721b15b3b2252ca82372c3a7abea214",
    inputCheckpointPath:
      "examples/explorer-stages/aggregate-time-windows/01-original-high-frequency-events.yaml",
    inputCheckpointSha256:
      "sha256:ad56f7df1414bb064b9a470a703c18275c7a333bf9ed0ee82490a93a76036916",
    outputCheckpointPath:
      "examples/explorer-stages/aggregate-time-windows/05-multi-level-configuration.yaml",
    outputCheckpointSha256:
      "sha256:16d7056d087ff735673bedce14c69b570ba9e9bde5ef73d659fb60806bcf8668",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "design",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "deduplicate-events": {
    exampleId: "deduplicate-events",
    kind: "curated-explanation",
    verificationId: "deduplicate-events-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/deduplicate-events.yaml",
    pipelineSha256:
      "sha256:58bac47624cd5a0e496091b7acfb6dae970b56486c1a3f5220a6f249ba4ba568",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-transformation/deduplicate-events-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:8aadea6f846c55c9a11080b0879168efc80496ad8c21c691c50365f94aef37d5",
    inputCheckpointPath:
      "examples/explorer-stages/deduplicate-events/01-original-events.yaml",
    inputCheckpointSha256:
      "sha256:6de77bb2ce570b57b415631fd8087f2808abd3a8521ef25bd3c72ffb92ec3b8d",
    outputCheckpointPath:
      "examples/explorer-stages/deduplicate-events/05-external-cache-configuration.yaml",
    outputCheckpointSha256:
      "sha256:a9cf67e6229244d95a5ab1ea2b01679073e401e66fa5f103a96c7be58a35b902",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "normalize-timestamps": {
    exampleId: "normalize-timestamps",
    kind: "curated-explanation",
    verificationId: "normalize-timestamps-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/normalize-timestamps.yaml",
    pipelineSha256:
      "sha256:54a31a07c21e9b565705fdb3f30deb2c247f63a1ab8d1afa82b6aa5f4026283c",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-transformation/normalize-timestamps-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:d6a39502c1b9045549df8b8e1b870556995918218023e7a6bc0d2128213722d4",
    inputCheckpointPath:
      "examples/explorer-stages/normalize-timestamps/01-mixed-timestamp-formats.yaml",
    inputCheckpointSha256:
      "sha256:7c15e2ab90cb624c3578490e50d650968b1f8377d2663b45345dc9504a9f747a",
    outputCheckpointPath:
      "examples/explorer-stages/normalize-timestamps/03-normalize-to-utc-metadata.yaml",
    outputCheckpointSha256:
      "sha256:3f8427929470a759bb1f5bda31df5fe31f18f3b67fe4a44e85f44543b238ed2b",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 3,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "parse-logs": {
    exampleId: "parse-logs",
    kind: "curated-explanation",
    verificationId: "parse-logs-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/files/data-transformation/parse-logs.yaml",
    pipelineSha256:
      "sha256:9ceb0430dbcc9fd0f89ca5557e109be3ce8874b093c354868b09fa10d564d728",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-transformation/parse-logs-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:a11089829f4cdcfcf2ac25b39e7f9fa56545f90247c2f1baeb5f4ac2c8f819af",
    inputCheckpointPath:
      "examples/explorer-stages/parse-logs/01-original-input.yaml",
    inputCheckpointSha256:
      "sha256:e486bb8b301ec8a2c2f10fcc419b9aab7ded32d32ac6132daeeace1fedd02937",
    outputCheckpointPath:
      "examples/explorer-stages/parse-logs/06-syslog-message-parsing.yaml",
    outputCheckpointSha256:
      "sha256:ddec41600e2a2f5a76d3f2d7f0370ae42bb5541052583ae2caddb68b02ad889d",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "transform-formats": {
    exampleId: "transform-formats",
    kind: "curated-explanation",
    verificationId: "transform-formats-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "static/files/data-transformation/transform-formats.yaml",
    pipelineSha256:
      "sha256:b004c88a9a1529298157b4d8c38faee1cc0512a24d02b010d987a6f40bd14fd3",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/data-transformation/transform-formats-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:fd0f107f4033326219e02efd810ffc72f63e0d43c06434f5bdba39549ab430cd",
    inputCheckpointPath:
      "examples/explorer-stages/transform-formats/01-json-input.yaml",
    inputCheckpointSha256:
      "sha256:97bf3c31922063b8a4c1e2756d9046874a5ab5f5a3328dc84fb14556fccb9973",
    outputCheckpointPath:
      "examples/explorer-stages/transform-formats/04-auto-detection.yaml",
    outputCheckpointSha256:
      "sha256:a82fdfc35a5a7f2456c9765018e7a5e25664da235822f2ba7c710bc76be68bea",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "db2-to-bigquery": {
    exampleId: "db2-to-bigquery",
    kind: "curated-explanation",
    verificationId: "db2-to-bigquery-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/enterprise-migration/db2-to-bigquery/db2-to-bigquery.yaml",
    pipelineSha256:
      "sha256:29cfd18c2f3c4dd4366755e1469ba074f23ee27886f870ce4926324e60673826",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/enterprise-migration/db2-to-bigquery-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:83a5fc8be5da2385d5c75dceb11274d5a68fff12023f417475feda3f68648955",
    inputCheckpointPath:
      "examples/explorer-stages/db2-to-bigquery/01-add-lineage-metadata.yaml",
    inputCheckpointSha256:
      "sha256:2dd8107bad1915f5b1d07c6858942de83d7595d2ee608c9563587d479c2b7089",
    outputCheckpointPath:
      "examples/explorer-stages/db2-to-bigquery/06-validate-required-fields.yaml",
    outputCheckpointSha256:
      "sha256:8c7ea0bcf69830fc2fad1c73640a40e963562256193e6d905c0536b87593cb99",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "nightly-backup": {
    exampleId: "nightly-backup",
    kind: "curated-explanation",
    verificationId: "nightly-backup-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/enterprise-migration/nightly-backup/nightly-backup.yaml",
    pipelineSha256:
      "sha256:0358f688e2b5cb4accae6608b3b7f702635d7004b20115e52272fee5ec351e60",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/enterprise-migration/nightly-backup-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:2a50b026059b583497f34511c025c20c021e2927aa8fdfb0b401bee6276c6deb",
    inputCheckpointPath:
      "examples/explorer-stages/nightly-backup/01-extract-multiple-tables.yaml",
    inputCheckpointSha256:
      "sha256:b319a7f8d9a5ee78eb352ace14d6eec731e2648f2450f28df552b6ba214e3b16",
    outputCheckpointPath:
      "examples/explorer-stages/nightly-backup/04-route-to-storage.yaml",
    outputCheckpointSha256:
      "sha256:fbc9e4dc7c039002a82264bd6ca437e0db3b1378da209396d2f0ab811b16488c",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "medical-device-intelligence": {
    exampleId: "medical-device-intelligence",
    kind: "curated-explanation",
    verificationId: "medical-device-intelligence-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "docs/integrations/medical-device-intelligence/pipeline.yaml",
    pipelineSha256:
      "sha256:a756b96696a420433940a91e3ff6dccb4b1a85c2778c782f2d04ad8c99f0cb16",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/integrations/medical-device-intelligence-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:f127d293cb9740ad767b96738e321ded292e682d7c4b06fe3ddc85a3d61a4e00",
    inputCheckpointPath:
      "examples/explorer-stages/medical-device-intelligence/01-collect-synthetic-fixtures.yaml",
    inputCheckpointSha256:
      "sha256:dc867514440a26ddf9d77fa7e2913a174521b644e6454120ed8dfd9f44f306ba",
    outputCheckpointPath:
      "examples/explorer-stages/medical-device-intelligence/05-fan-out-review-candidates.yaml",
    outputCheckpointSha256:
      "sha256:1d503526e0e582bf6fa2a9902ed499e249c0928c46e08e1475396024d52599be",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "accessibility",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "motherduck-retail-analytics": {
    exampleId: "motherduck-retail-analytics",
    kind: "curated-explanation",
    verificationId: "motherduck-retail-analytics-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/pipelines/motherduck-retail-pipeline.yaml",
    pipelineSha256:
      "sha256:8f89fcb0c4476d35c1cb28b822f919c249cc0282de6c5bb7ea63a0314619bdb6",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/integrations/motherduck-retail-analytics-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:f132da6688c38248793f8950d37b055bfc3a5083e6de555c47b7660b21f575e5",
    inputCheckpointPath:
      "examples/explorer-stages/motherduck-retail-analytics/01-generate-pos-transactions.yaml",
    inputCheckpointSha256:
      "sha256:dd127311688711d7472ef7f0c8c6758b4f425378a9760375c097f6fd10389182",
    outputCheckpointPath:
      "examples/explorer-stages/motherduck-retail-analytics/05-write-partitioned-parquet-to-s3.yaml",
    outputCheckpointSha256:
      "sha256:9b8f9002303fe36e82872484eb3cee12bc99ef820775bf60d43d719b8e3cdc10",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "oran-telco-pipeline": {
    exampleId: "oran-telco-pipeline",
    kind: "curated-explanation",
    verificationId: "oran-telco-pipeline-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/pipelines/oran-telco-pipeline.yaml",
    pipelineSha256:
      "sha256:86a929ce688db395b9f2125c106a407054c9d9c1e5f8100fd277e04cf2261e0c",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/integrations/oran-telco-pipeline-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:9f1e5c6d76b638203991f0534a8e5c3f04159ae4b47af668f6f13858fa542041",
    inputCheckpointPath:
      "examples/explorer-stages/oran-telco-pipeline/01-adapter-output.yaml",
    inputCheckpointSha256:
      "sha256:594a09342e6810f7ccbfa22ce33b476e10f71a3d6c3ad072f76e09c038e1e47c",
    outputCheckpointPath:
      "examples/explorer-stages/oran-telco-pipeline/05-external-destinations.yaml",
    outputCheckpointSha256:
      "sha256:f6b22ce00a1652bad9fe68eb4a63bc08005ae511917c6755c5f115756f58921d",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "claims-evidence",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "scada-energy-edge": {
    exampleId: "scada-energy-edge",
    kind: "curated-explanation",
    verificationId: "scada-energy-edge-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/integrations/scada-energy-edge/scada-edge-complete.yaml",
    pipelineSha256:
      "sha256:b8bc13c1ec92cef29dfe9d306f5bfc9708231315c01499354d4bbe44a007b432",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/integrations/scada-energy-edge/stages.ts",
    authoredStageModuleSha256:
      "sha256:446bc7bd03a136db8329f0f82c1122363c85e8bda3962a7e539f1284299c814c",
    inputCheckpointPath:
      "examples/explorer-stages/scada-energy-edge/01-adapter-output.yaml",
    inputCheckpointSha256:
      "sha256:0597ca71b2e3c57bedf6b183b1ff0139e0fa2a9da967cf09d0c84e35b7f09795",
    outputCheckpointPath:
      "examples/explorer-stages/scada-energy-edge/04-route-selected-records.yaml",
    outputCheckpointSha256:
      "sha256:4d7dad779f78dbae8db9b1dde0f610af4a695f5c8320829aee327fc58bc18a2e",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 4,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "claims-evidence",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "splunk-edge-processing": {
    exampleId: "splunk-edge-processing",
    kind: "curated-explanation",
    verificationId: "splunk-edge-processing-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath: "static/pipelines/splunk-production-pipeline.yaml",
    pipelineSha256:
      "sha256:55d2b3ab74cdcc1fa17a8ee34af372b571b0a1265534582b3d9da8d1ad359e11",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/integrations/splunk-edge-processing-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:dd1f8a111531a46f65f0c712e04ce4b75305f59b317e377c8749aa6b38966cbc",
    inputCheckpointPath:
      "examples/explorer-stages/splunk-edge-processing/01-authored-log-fixture.yaml",
    inputCheckpointSha256:
      "sha256:ffdb036b4ded462cd7880a385814a5c27888d89482cf268f179fe543c0fb72ff",
    outputCheckpointPath:
      "examples/explorer-stages/splunk-edge-processing/05-route-to-splunk-hec.yaml",
    outputCheckpointSha256:
      "sha256:f761db2fc9794a573b82f1cd486f1de6153a10dc6da31ed4ce8e7d5ad6f3f1bc",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "editorial",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "enrich-export": {
    exampleId: "enrich-export",
    kind: "curated-explanation",
    verificationId: "enrich-export-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/log-processing/enrich-export-complete.yaml",
    pipelineSha256:
      "sha256:7559ac3a7b0a8b3044f6a6c57f26e16ca5d6014a161e3c2d4bdf4f9097d231e2",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath: "docs/log-processing/enrich-export-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:397f4e39cf4ebf3a49f36b11932e3f3b031a4407c11f2b3ae9169c06d983d968",
    inputCheckpointPath:
      "examples/explorer-stages/enrich-export/01-original-log-data.yaml",
    inputCheckpointSha256:
      "sha256:d3771400d8f05e2dde64ad32f3410e261b18d536393011e6abb2c646373ed599",
    outputCheckpointPath:
      "examples/explorer-stages/enrich-export/05-configured-s3-object.yaml",
    outputCheckpointSha256:
      "sha256:fba9fe3706f078eb3cc2b1b76f179a08a7232ea68c970e677fc57a0d3473a1a4",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 5,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "filter-severity": {
    exampleId: "filter-severity",
    kind: "curated-explanation",
    verificationId: "filter-severity-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/log-processing/filter-severity-complete.yaml",
    pipelineSha256:
      "sha256:b83a428cf034a1d9798fa1964ee83cf656ddbcd84a98d3a04a7f4cd1c9a9af76",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/log-processing/filter-severity-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:c0b8699d420f2371fabcf229785dfd203e5c4a26b22648be70638839e8cfb489",
    inputCheckpointPath:
      "examples/explorer-stages/filter-severity/01-all-log-levels-mixed.yaml",
    inputCheckpointSha256:
      "sha256:f28f07c239171d3041291ecd7dfad3adce2e47510c8099117d8836abb79eab7d",
    outputCheckpointPath:
      "examples/explorer-stages/filter-severity/03-filter-route.yaml",
    outputCheckpointSha256:
      "sha256:de774126ae45c7137054a38a2f2813c6158445c2fd866989a9c52cf1c77bd4f7",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 3,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "product-semantics",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
  "production-pipeline": {
    exampleId: "production-pipeline",
    kind: "curated-explanation",
    verificationId: "production-pipeline-curated-stage-binding-v1",
    schemaDigest:
      "sha256:7a502149249c39ad27263e9d22eaec485c2287755563b626df423dd47b762a01",
    canonicalPipelinePath:
      "examples/log-processing/production-pipeline-complete.yaml",
    pipelineSha256:
      "sha256:dc30e4c47dc47921b2dfb75f69c5dec6d5e508027222dd29880b1f6334900b84",
    bindingManifestPath: "content/explorer-stage-bindings-v1.json",
    bindingManifestSha256:
      "sha256:1492b77581e6d6ed32ec7aba13e471551d8084c76f913bbd5696dd0f370ef022",
    authoredStageModulePath:
      "docs/log-processing/production-pipeline-full.stages.ts",
    authoredStageModuleSha256:
      "sha256:9bf9e19abead607427709d177313df3801fedcf7c5b3c8e28f9256951a2d698b",
    inputCheckpointPath:
      "examples/explorer-stages/production-pipeline/01-raw-http-input.yaml",
    inputCheckpointSha256:
      "sha256:2a7d89c43e0c2156a1400755f46990fb66d709bcb8632b90922a62a9db25641b",
    outputCheckpointPath:
      "examples/explorer-stages/production-pipeline/06-fan-out.yaml",
    outputCheckpointSha256:
      "sha256:f899c456eb7dbb9a8cda48f7289e42c09ce15b9abe75c3199c918ba0ec91128e",
    fidelityOraclePath: "scripts/generate-explorer-stage-configs.ts",
    fidelityOracleSha256:
      "sha256:a9e8f384017d83b3def41d43ca9fa12f245b2fa9f0d8274e886926b4bed71b82",
    semanticsVerifierPath: "scripts/quality/verify-explorer-provenance.ts",
    semanticsVerifierSha256:
      "sha256:5458ba33de76335c743a700ad91aa6d0b4489776bfbe3a91587468122bc87555",
    stageCount: 6,
    command: "npm run validate-catalog",
    environment: "phase1-foundation-node-20.19.4",
    toolVersions: { docusaurus: "3.9.2", node: "20.19.4" },
    generatedAt: "2026-07-18T00:00:00Z",
    verifierLane: "engineering",
    executionStatus: "architecture-only",
    operationalEvidence: "not-assessed",
  },
};
