import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const aggregateTimeWindowsStages: Stage[] = [
  {
    id: 1,
    slug: 'original-high-frequency-events',
    title: 'Original High-Frequency Events',
    description:
      'A synthetic sensor record before any window key or aggregate field is added.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"temperature": 72.3,',
        indent: 1,
        key: 'temperature',
        valueType: 'number',
      },
      {
        content: '"humidity": 45.2,',
        indent: 1,
        key: 'humidity',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2025-01-15T10:23:45.123Z"',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"temperature": 72.3,',
        indent: 1,
        key: 'temperature',
        valueType: 'number',
      },
      {
        content: '"humidity": 45.2,',
        indent: 1,
        key: 'humidity',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2025-01-15T10:23:45.123Z"',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'tumbling-window-aggregation',
    title: 'Tumbling Window Aggregation',
    description:
      'The authored mapping assigns readings to fixed one-minute buckets and shows summary fields.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"temperature": 72.3,',
        indent: 1,
        key: 'temperature',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2025-01-15T10:23:45.123Z"',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"time_bucket": "2025-01-15T10:23:00Z",',
        indent: 1,
        key: 'time_bucket',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"window_start": "2025-01-15T10:23:00Z",',
        indent: 1,
        key: 'window_start',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"window_end": "2025-01-15T10:24:00Z",',
        indent: 1,
        key: 'window_end',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"event_count": 60,',
        indent: 1,
        key: 'event_count',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"temperature_avg": 73.05,',
        indent: 1,
        key: 'temperature_avg',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"temperature_min": 70.1,',
        indent: 1,
        key: 'temperature_min',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"temperature_max": 76.0',
        indent: 1,
        key: 'temperature_max',
        valueType: 'number',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'sliding-window-trends',
    title: 'Sliding Window Trends',
    description:
      'The authored mapping places a summary into overlapping five-minute lookback windows.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"time_bucket": "2025-01-15T10:20:00Z",',
        indent: 1,
        key: 'time_bucket',
        valueType: 'string',
      },
      {
        content: '"temperature_avg": 72.1',
        indent: 1,
        key: 'temperature_avg',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"window_start": "2025-01-15T10:20:00Z",',
        indent: 1,
        key: 'window_start',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"window_end": "2025-01-15T10:25:00Z",',
        indent: 1,
        key: 'window_end',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"temperature_5min_avg": 73.36,',
        indent: 1,
        key: 'temperature_5min_avg',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"temperature_trend": "increasing",',
        indent: 1,
        key: 'temperature_trend',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"temperature_slope": 0.8,',
        indent: 1,
        key: 'temperature_slope',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"temperature_volatility": 1.76,',
        indent: 1,
        key: 'temperature_volatility',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"anomaly_detected": false',
        indent: 1,
        key: 'anomaly_detected',
        valueType: 'boolean',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'session-based-activity-clustering',
    title: 'Session-Based Activity Clustering',
    description:
      'The authored mapping groups fixture events using a five-minute inactivity threshold.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "motion_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"activity": "detected",',
        indent: 1,
        key: 'activity',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2025-01-15T10:30:00Z"',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "motion_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"session_id": "motion_001_20250115_103000_103030",',
        indent: 1,
        key: 'session_id',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"session_start": "2025-01-15T10:30:00Z",',
        indent: 1,
        key: 'session_start',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"session_end": "2025-01-15T10:30:30Z",',
        indent: 1,
        key: 'session_end',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"session_duration_minutes": 0.5,',
        indent: 1,
        key: 'session_duration_minutes',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"total_events": 3,',
        indent: 1,
        key: 'total_events',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"activity_intensity": "high",',
        indent: 1,
        key: 'activity_intensity',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"activity_pattern": "continuous"',
        indent: 1,
        key: 'activity_pattern',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 5,
    slug: 'multi-level-configuration',
    title: 'Multi-Level Configuration',
    description:
      'A review configuration sketches sensor, location, and global keys with external cache and output dependencies.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"sensor_id": "temp_001",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"location": "warehouse_a",',
        indent: 1,
        key: 'location',
        valueType: 'string',
      },
      {
        content: '"temperature_avg": 72.3,',
        indent: 1,
        key: 'temperature_avg',
        valueType: 'number',
      },
      {
        content: '"event_count": 60',
        indent: 1,
        key: 'event_count',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"aggregation_level": "global",',
        indent: 1,
        key: 'aggregation_level',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"sensor_count": 4,',
        indent: 1,
        key: 'sensor_count',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"location_count": 2,',
        indent: 1,
        key: 'location_count',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"temperature_avg": 72.525,',
        indent: 1,
        key: 'temperature_avg',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"total_events": 239',
        indent: 1,
        key: 'total_events',
        valueType: 'number',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
];
