pipeline:
  processors:
    - mapping: |
        meta source_format = if content().has_prefix("Obj\\x01") {
          "avro"
        } else {
          "json"
        }
        root = content()
    - switch:
        - check: 'meta("source_format") == "json"'
          processors:
            - mapping: root = content().parse_json()
        - check: 'meta("source_format") == "avro"'
          processors:
            - mapping: |
                root = content()
                meta decoder_required = "avro"
        - processors:
            - log:
                message: 'Unknown format: ${!content()}'
