pipeline:
  processors:
    - mapping: |
        root = this
        root.lineage_node_id = env("NODE_ID").or("edge-node-demo")
        root.lineage_pipeline = "log-enrichment-s3-demo"
        root.lineage_timestamp = now()
