pipeline:
  processors:
    - mapping: |
        root = this
        root.metadata.ingestion_time = now()
        root.metadata.correlation_id = uuid_v4()
        root.metadata.pipeline_version = "v2.1"
        root.metadata.edge_node = env("HOSTNAME")
