pipeline:
  processors:
    - mapping: |
        root.event = {
          "id": this.id,
          "timestamp": this.timestamp,
          "level": this.level,
          "service": this.service,
          "message": this.message,
          "user_id": this.user_id,
          "request_id": this.request_id
        }
        root.metadata = {
          "node_id": this.lineage_node_id,
          "pipeline": this.lineage_pipeline,
          "processed_at": this.lineage_timestamp
        }
