import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const priorityQueuesStages: Stage[] = [
  {
    id: 1,
    slug: 'original-input',
    title: 'Original Input',
    description:
      'Start with one processing path before adding authored priority labels and branches.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"urgency": "high",',
        indent: 1,
        key: 'urgency',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"urgency": "high",',
        indent: 1,
        key: 'urgency',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"processed_at": "2024-01-15T14:30:01Z"',
        indent: 1,
        key: 'processed_at',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'severity-based-routing',
    title: 'Severity-Based Routing',
    description:
      'Messages are classified by log severity (CRITICAL, ERROR, WARNING, INFO) and routed to dedicated queues with appropriate batching policies. Critical messages bypass batching entirely.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed"',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"priority": "critical",',
        indent: 1,
        key: 'priority',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"priority_score": 85,',
        indent: 1,
        key: 'priority_score',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"routing_strategy": "severity-based"',
        indent: 1,
        key: 'routing_strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'customer-tier-enhancement',
    title: 'Customer Tier Enhancement',
    description:
      'Add an authored customer-tier field to the example priority score.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"amount": 50000',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"priority": "critical",',
        indent: 1,
        key: 'priority',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"priority_score": 340,',
        indent: 1,
        key: 'priority_score',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"sla_target_ms": 100,',
        indent: 1,
        key: 'sla_target_ms',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"routing_strategy": "tier-enhanced"',
        indent: 1,
        key: 'routing_strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'multi-criteria-scoring',
    title: 'Multi-Criteria Scoring',
    description:
      'Sophisticated scoring algorithm combines severity, customer tier, event type, urgency, and business context into a numerical priority score for precise routing decisions.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"urgency": "high",',
        indent: 1,
        key: 'urgency',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"amount": 50000',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"severity": "CRITICAL",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"customer_tier": "enterprise",',
        indent: 1,
        key: 'customer_tier',
        valueType: 'string',
      },
      {
        content: '"urgency": "high",',
        indent: 1,
        key: 'urgency',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"priority": "critical",',
        indent: 1,
        key: 'priority',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"priority_score": 430,',
        indent: 1,
        key: 'priority_score',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"routing_strategy": "multi-criteria-scoring",',
        indent: 1,
        key: 'routing_strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '"scoring_breakdown": {', indent: 1, type: 'highlighted' },
      {
        content: '"severity_score": 85,',
        indent: 2,
        key: 'severity_score',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"tier_multiplier": 4.0,',
        indent: 2,
        key: 'tier_multiplier',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"event_type_boost": 40,',
        indent: 2,
        key: 'event_type_boost',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"urgency_boost": 15,',
        indent: 2,
        key: 'urgency_boost',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"final_score": 430',
        indent: 2,
        key: 'final_score',
        valueType: 'number',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
];
