import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const smartBufferingStages: Stage[] = [
  {
    id: 1,
    slug: 'original-input',
    title: 'Original Input',
    description:
      'All messages are buffered in FIFO order. Important alerts wait behind debug logs, payment failures queue after bulk analytics. After reconnection, all backlogged messages compete equally.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "critical",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "important",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "critical",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "important",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"buffered_at": "2024-01-15T14:30:01Z"',
        indent: 1,
        key: 'buffered_at',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'priority-classification',
    title: 'Priority Classification',
    description:
      'Messages are classified into three tiers: important (critical alerts, payment failures), regular (standard operations), and archive (debug logs, analytics). Each tier gets a label.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "critical",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "important",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "critical",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "important",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"priority_tier": 1,',
        indent: 1,
        key: 'priority_tier',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"priority_label": "important"',
        indent: 1,
        key: 'priority_label',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'priority-output-routing',
    title: 'Priority Output Routing',
    description:
      "Route each tier to separate outputs with different batching. Important: count=1 (immediate). Regular: count=50. Archive: count=200. New important messages ship immediately—they don't wait for queued regular batches.",
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "critical",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "important",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"priority_tier": 1,',
        indent: 1,
        key: 'priority_tier',
        valueType: 'number',
      },
      {
        content: '"priority_label": "important"',
        indent: 1,
        key: 'priority_label',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      {
        content: '// Routed to important output (count: 1)',
        indent: 0,
        type: 'comment',
      },
      {
        content: '// Ships IMMEDIATELY - no batching delay',
        indent: 0,
        type: 'comment',
      },
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T14:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "critical",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "important",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "payment.failed",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "payment-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Payment processing failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"amount": 50000,',
        indent: 1,
        key: 'amount',
        valueType: 'number',
      },
      {
        content: '"priority_tier": 1,',
        indent: 1,
        key: 'priority_tier',
        valueType: 'number',
      },
      {
        content: '"priority_label": "important",',
        indent: 1,
        key: 'priority_label',
        valueType: 'string',
      },
      {
        content: '"routed_to": "important_output",',
        indent: 1,
        key: 'routed_to',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"batching": "count: 1, period: 0s"',
        indent: 1,
        key: 'batching',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'starvation-prevention',
    title: 'Starvation Prevention',
    description:
      'Add an authored age-based score adjustment. Eventual delivery and starvation behavior require a real queue and worker test.',
    inputLines: [
      { content: '// 3-hour-old archive message', indent: 0, type: 'comment' },
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T11:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "debug",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "archive",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "analytics.pageview",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "web-frontend",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Old debug log"',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      {
        content: '// ESCALATED to important tier!',
        indent: 0,
        type: 'comment',
      },
      {
        content: '// Ships with count: 1 (immediate)',
        indent: 0,
        type: 'comment',
      },
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2024-01-15T11:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"severity": "debug",',
        indent: 1,
        key: 'severity',
        valueType: 'string',
      },
      {
        content: '"category": "archive",',
        indent: 1,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"event_type": "analytics.pageview",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"service": "web-frontend",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Old debug log",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"age_seconds": 10800,',
        indent: 1,
        key: 'age_seconds',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"age_boost": 900,',
        indent: 1,
        key: 'age_boost',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"priority_score": 1000,',
        indent: 1,
        key: 'priority_score',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"priority_tier": 1,',
        indent: 1,
        key: 'priority_tier',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"priority_label": "important",',
        indent: 1,
        key: 'priority_label',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"age_escalated": true',
        indent: 1,
        key: 'age_escalated',
        valueType: 'boolean',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
];
