import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { Resvg } from '@resvg/resvg-js';
import type { PluginModule } from '@docusaurus/types';
import { EXAMPLE_RECORDS } from '../src/catalog/registry';

export const escapeXml = (text: string): string =>
  text.replace(
    /[&<>"']/g,
    (character) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&apos;',
      })[character]!
  );
export function wrap(text: string, length: number): string[] {
  const lines: string[] = [];
  for (const word of text.split(/\s+/)) {
    if (
      !lines.length ||
      lines[lines.length - 1].length + word.length + 1 > length
    )
      lines.push(word);
    else lines[lines.length - 1] += ` ${word}`;
  }
  return lines;
}
export function cardSvg(title: string, summary: string, logo: string): string {
  const titleLines = wrap(title, 32);
  const fontSize = titleLines.length > 3 ? 45 : 56;
  const description = wrap(summary, 83).slice(0, 3);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#f8f5ff"/><rect x="0" width="18" height="630" fill="#9259ed"/><circle cx="1160" cy="50" r="240" fill="#eee5ff"/><image x="64" y="48" width="260" height="48" href="data:image/svg+xml;base64,${logo}"/><text x="64" y="153" fill="#6934aa" font-family="Figtree" font-size="21" letter-spacing="3">PIPELINE EXAMPLES</text>${titleLines.map((line, i) => `<text x="64" y="${222 + i * (fontSize + 10)}" fill="#261044" font-family="Figtree" font-size="${fontSize}" font-weight="700">${escapeXml(line)}</text>`).join('')}${description.map((line, i) => `<text x="64" y="${460 + i * 30}" fill="#564469" font-family="Figtree" font-size="23">${escapeXml(line)}</text>`).join('')}<text x="64" y="590" fill="#6934aa" font-family="Figtree" font-size="20">examples.expanso.io</text></svg>`;
}
const plugin: PluginModule = (context) => {
  const cards = new Map<string, { title: string; summary: string }>();
  return {
    name: 'examples-social-discovery',
    async allContentLoaded({ allContent, actions }) {
      const metadata: Record<string, unknown> = {};
      const docs =
        (
          allContent['docusaurus-plugin-content-docs']?.default as any
        )?.loadedVersions?.flatMap((version: any) => version.docs) || [];
      for (const doc of docs) {
        if (doc.draft || doc.unlisted) continue;
        const pathname = doc.permalink.endsWith('/')
          ? doc.permalink
          : `${doc.permalink}/`;
        const record = EXAMPLE_RECORDS.find((entry) =>
          pathname.startsWith(entry.routes.overview)
        );
        const title =
          doc.title === 'Troubleshooting' && record
            ? `${record.title} Troubleshooting`
            : doc.title;
        const summary = doc.description;
        if (!title || !summary)
          throw new Error(
            `Social metadata requires title and description: ${pathname}`
          );
        const digest = createHash('sha256')
          .update(JSON.stringify([pathname, title, summary]))
          .digest('hex')
          .slice(0, 16);
        const image = `/img/social/${digest}.png`;
        cards.set(image, { title, summary });
        const breadcrumbs = [
          { name: 'Examples', item: 'https://examples.expanso.io/' },
        ];
        if (record && pathname !== record.routes.overview)
          breadcrumbs.push({
            name: record.title,
            item: `https://examples.expanso.io${record.routes.overview}`,
          });
        if (pathname !== '/')
          breadcrumbs.push({
            name: title,
            item: `https://examples.expanso.io${pathname}`,
          });
        metadata[pathname] = {
          title,
          image,
          breadcrumbs: doc.sidebar ? undefined : breadcrumbs,
        };
      }
      // Tag pages are generated by the docs plugin, not authored catalog records.
      const tags = new Map<string, string>();
      for (const doc of docs)
        for (const tag of doc.tags || [])
          tags.set(
            tag.permalink.endsWith('/') ? tag.permalink : `${tag.permalink}/`,
            tag.label
          );
      tags.set('/tags/', 'All topics');
      for (const [pathname, label] of tags) {
        const title = `${label} examples`;
        const summary = `Browse Expanso pipeline examples by ${label === 'All topics' ? 'technology, industry, and processing pattern' : label}.`;
        const digest = createHash('sha256')
          .update(pathname)
          .digest('hex')
          .slice(0, 16);
        const image = `/img/social/${digest}.png`;
        cards.set(image, { title, summary });
        metadata[pathname] = {
          title,
          image,
          breadcrumbs: [
            { name: 'Examples', item: 'https://examples.expanso.io/' },
            { name: 'Topics', item: 'https://examples.expanso.io/tags/' },
            ...(pathname === '/tags/'
              ? []
              : [
                  {
                    name: label,
                    item: `https://examples.expanso.io${pathname}`,
                  },
                ]),
          ],
        };
      }
      actions.setGlobalData(metadata);
    },
    async postBuild({ outDir }) {
      const logo = (
        await readFile(join(context.siteDir, 'static/img/logo.svg'))
      ).toString('base64');
      await mkdir(join(outDir, 'img/social'), { recursive: true });
      for (const [image, card] of cards) {
        const renderer = new Resvg(cardSvg(card.title, card.summary, logo), {
          font: {
            loadSystemFonts: false,
            fontFiles: [
              join(context.siteDir, 'static/fonts/figtree-variable.ttf'),
            ],
            defaultFontFamily: 'Figtree',
          },
        });
        await writeFile(join(outDir, image), renderer.render().asPng());
      }
      console.log(`Social cards generated: ${cards.size}`);
    },
  };
};
export default plugin;
