services:
  # PostgreSQL - Relational database
  postgres:
    image: postgres:16-alpine
    container_name: expanso-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: expanso
      POSTGRES_PASSWORD: expanso
      POSTGRES_DB: expanso_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expanso"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
