services:
  # Redis - In-memory cache and message broker
  redis:
    image: redis:7-alpine
    container_name: expanso-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
