output:
  aws_s3:
    bucket: ${S3_BUCKET_NAME}
    path: logs/demo_${!now().ts_unix()}.jsonl
    batching:
      count: 10
      period: 10s
    region: ${AWS_REGION}
    server_side_encryption: aws:kms
    kms_key_id: ${S3_KMS_KEY_ARN}
