/** Generated by scripts/generate-explorer-stage-configs.ts. */
import type {
  GeneratedExplorerStageConfig,
  GeneratedExplorerStageFamily,
} from "../explorerStageConfigs.generated";

export const GENERATED_EXPLORER_STAGES = [
  {
    id: 1,
    slug: "single-destination",
    title: "Single Destination",
    description:
      "Basic pipeline with single file output - the typical starting point before implementing fan-out pattern.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ file:", indent: 0 },
      { content: "path: /var/data/events.jsonl", indent: 1 },
      { content: "", indent: 0 },
      {
        content: "// Single destination - no redundancy",
        indent: 0,
        type: "comment",
      },
    ],
    yamlFilename: "01-single-destination.yaml",
    yamlCode:
      "name: single-destination-pipeline\ntype: pipeline\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n\n  output:\n    file:\n      path: /var/data/events.jsonl\n      codec: lines\n",
    configSha256:
      "sha256:16427fdbeef3193d8adb9585fd99cf6cd00ae2118b7d810e0bc11441e7a4c571",
  },
  {
    id: 2,
    slug: "broker-fan-out-foundation",
    title: "Broker Fan-Out Foundation",
    description:
      "Introduction of broker output with fan_out pattern enabling concurrent delivery to multiple destinations.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0, type: "highlighted" },
      { content: "", indent: 0 },
      { content: "  → file: realtime.jsonl", indent: 1, type: "added" },
      { content: "    batching: 100 msgs / 5s", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → file: archive.jsonl", indent: 1, type: "added" },
      { content: "    batching: 1000 msgs / 30s", indent: 2 },
    ],
    yamlFilename: "02-broker-fan-out-foundation.yaml",
    yamlCode:
      "name: fan-out-foundation\ntype: pipeline\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - file:\n            path: /var/data/realtime.jsonl\n            batching: {count: 100, period: 5s}\n        - file:\n            path: /var/data/archive.jsonl\n            batching: {count: 1000, period: 30s}\n",
    configSha256:
      "sha256:dd15d5c7c4b6ace7035759458f088cd2dd5f621694cacbcd93844406e07edc9f",
  },
  {
    id: 3,
    slug: "kafka-real-time-streaming",
    title: "Kafka Real-Time Streaming",
    description:
      "Add a Kafka branch with authored batching settings that require environment-specific tuning.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0 },
      { content: "", indent: 0 },
      { content: "  → kafka: sensor-events", indent: 1, type: "added" },
      { content: "    key: temp-sensor-42", indent: 2 },
      { content: "    batching: 100 msgs / 2s", indent: 2 },
      { content: "    compression: snappy", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → file: archive.jsonl", indent: 1 },
      { content: "    batching: 1000 msgs / 30s", indent: 2 },
    ],
    yamlFilename: "03-kafka-real-time-streaming.yaml",
    yamlCode:
      'name: kafka-fan-out\ntype: pipeline\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.edge_node_id = env("NODE_ID")\n          root.processing_timestamp = now()\n\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses: [kafka-1.example.com:9092]\n            topic: sensor-events\n            key: ${!json("sensor_id")}\n            batching: {count: 100, period: 2s}\n            compression: snappy\n        - file:\n            path: /var/data/archive.jsonl\n            batching: {count: 1000, period: 30s}\n',
    configSha256:
      "sha256:3abc67b257bb1cf3beeb060e0086286c2a666310bee016a5d8e9688e9f0209ad",
  },
  {
    id: 4,
    slug: "s3-long-term-archive",
    title: "S3 Long-Term Archive",
    description:
      "Object-storage destination with authored batching and compression settings that require environment-specific review.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0 },
      { content: "", indent: 0 },
      { content: "  → kafka: sensor-events", indent: 1 },
      { content: "    batching: 100 msgs / 2s", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → aws_s3: sensor-data-archive", indent: 1, type: "added" },
      { content: "    path: data/dt=2025-01-20/events.jsonl.gz", indent: 2 },
      { content: "    batching: 10000 msgs / 30m", indent: 2 },
      { content: "    compression: gzip", indent: 2 },
      { content: "    storage: INTELLIGENT_TIERING", indent: 2 },
    ],
    yamlFilename: "04-s3-long-term-archive.yaml",
    yamlCode:
      'name: s3-fan-out\ntype: pipeline\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.edge_node_id = env("NODE_ID")\n          root.processing_timestamp = now()\n\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses: [kafka-1.example.com:9092]\n            topic: sensor-events\n            batching: {count: 100, period: 2s}\n        - aws_s3:\n            bucket: sensor-data-archive\n            path: data/dt=${!timestamp_date("2006-01-02")}/events.jsonl.gz\n            batching: {count: 10000, period: 30m}\n            content_encoding: gzip\n            storage_class: INTELLIGENT_TIERING\n',
    configSha256:
      "sha256:5f479f926373080079460a4f68513f16e3d286af1ed59151b5fb78f468c3a627",
  },
  {
    id: 5,
    slug: "elasticsearch-search-analytics",
    title: "Elasticsearch Search & Analytics",
    description:
      "Search and analytics destination with balanced batching for near real-time indexing and operational monitoring.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2,',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: '"analytics": {', indent: 1, key: "analytics", type: "added" },
      { content: '  "event_hour": 10,', indent: 2 },
      { content: '  "temp_status": "normal"', indent: 2 },
      { content: "}", indent: 1 },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0 },
      { content: "", indent: 0 },
      { content: "  → kafka: sensor-events", indent: 1 },
      { content: "    batching: 100 msgs / 2s", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → aws_s3: sensor-data-archive", indent: 1 },
      { content: "    batching: 10000 msgs / 30m", indent: 2 },
      { content: "", indent: 0 },
      {
        content: "  → elasticsearch: sensor-events-*",
        indent: 1,
        type: "added",
      },
      { content: "    index: sensor-events-2025-01-20", indent: 2 },
      { content: "    id: sensor-001", indent: 2 },
      { content: "    batching: 250 msgs / 10s", indent: 2 },
    ],
    yamlFilename: "05-elasticsearch-search-analytics.yaml",
    yamlCode:
      'name: complete-fan-out\ntype: pipeline\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.edge_node_id = env("NODE_ID")\n          root.processing_timestamp = now()\n          root.analytics = {\n            "event_hour": this.timestamp.ts_hour(),\n            "temp_status": if this.temperature > 35 { "high" } else { "normal" }\n          }\n\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses: [kafka-1.example.com:9092]\n            topic: sensor-events\n            batching: {count: 100, period: 2s}\n        - aws_s3:\n            bucket: sensor-data-archive\n            path: data/dt=${!timestamp_date("2006-01-02")}/events.jsonl.gz\n            batching: {count: 10000, period: 30m}\n        - elasticsearch:\n            urls: [https://es-1.example.com:9200]\n            index: sensor-events-${!timestamp_date("2006-01-02")}\n            id: ${!json("event_id")}\n            batching: {count: 250, period: 10s}\n',
    configSha256:
      "sha256:efa454dcf201fd5045e5c9b616c51ca2a1e58ad77ec5522936e57e2d7f88c8df",
  },
] satisfies readonly GeneratedExplorerStageConfig[];

export const GENERATED_EXPLORER_STAGE_FAMILY = {
  ...{
    binding: {
      exampleId: "fan-out-pattern",
      canonicalPipelinePath: "static/files/data-routing/fan-out-pattern.yaml",
      provenance: "curated-explanation",
      executionStatus: "architecture-only",
      operationalEvidence: "not-assessed",
      fixtureLabel: "01-single-destination.yaml",
      comparisonMode: "highlights",
    },
    canonicalPipelinePath: "static/files/data-routing/fan-out-pattern.yaml",
    pipelineSha256:
      "sha256:c050312ba1ef139845fed559ab94498a8c836006b65dbd9dff1b15c40efda930",
    fullYamlFilename: "fan-out-pattern.yaml",
    fullYaml:
      "name: multi-destination-sensor-data\ndescription: Send sensor data to Kafka, S3, and Elasticsearch\ntype: pipeline\nnamespace: production\nlabels:\n  environment: production\n  data-type: sensor-metrics\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n",
  },
  stages: GENERATED_EXPLORER_STAGES,
} satisfies GeneratedExplorerStageFamily;
