/** Generated by scripts/generate-explorer-stage-configs.ts. */
import type {
  GeneratedExplorerStageConfig,
  GeneratedExplorerStageFamily,
} from "../explorerStageConfigs.generated";

export const GENERATED_EXPLORER_STAGES = [
  {
    id: 1,
    slug: "single-destination",
    title: "Single Destination",
    description:
      "Basic pipeline with single file output - the typical starting point before implementing fan-out pattern.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ file:", indent: 0 },
      { content: "path: /var/data/events.jsonl", indent: 1 },
      { content: "", indent: 0 },
      {
        content: "// Single destination - no redundancy",
        indent: 0,
        type: "comment",
      },
    ],
    yamlFilename: "01-single-destination.yaml",
    yamlCode:
      "name: single-destination-pipeline\ntype: pipeline\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n  output:\n    file:\n      path: /var/data/events.jsonl\n      codec: lines\n",
    configSha256:
      "sha256:32fb86446323d6862c430126475a0130da3ed8cf0c2baa32a7025e22ecd1ec90",
  },
  {
    id: 2,
    slug: "broker-fan-out-foundation",
    title: "Broker Fan-Out Foundation",
    description:
      "Introduction of broker output with fan_out pattern enabling concurrent delivery to multiple destinations.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0, type: "highlighted" },
      { content: "", indent: 0 },
      { content: "  → file: realtime.jsonl", indent: 1, type: "added" },
      { content: "    batching: 100 msgs / 5s", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → file: archive.jsonl", indent: 1, type: "added" },
      { content: "    batching: 1000 msgs / 30s", indent: 2 },
    ],
    yamlFilename: "02-broker-fan-out-foundation.yaml",
    yamlCode:
      "name: fan-out-foundation\ntype: pipeline\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - broker:\n            outputs:\n              - file:\n                  path: /var/data/realtime.jsonl\n            batching:\n              count: 100\n              period: 5s\n        - broker:\n            outputs:\n              - file:\n                  path: /var/data/archive.jsonl\n            batching:\n              count: 1000\n              period: 30s\n",
    configSha256:
      "sha256:b2259847ce3e9da34ea567186bb9d9419a14abd8b4b1d09b97201157e7d50db8",
  },
  {
    id: 3,
    slug: "kafka-real-time-streaming",
    title: "Kafka Real-Time Streaming",
    description:
      "Add a Kafka branch with authored batching settings that require environment-specific tuning.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0 },
      { content: "", indent: 0 },
      { content: "  → kafka: sensor-events", indent: 1, type: "added" },
      { content: "    key: temp-sensor-42", indent: 2 },
      { content: "    batching: 100 msgs / 2s", indent: 2 },
      { content: "    compression: snappy", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → file: archive.jsonl", indent: 1 },
      { content: "    batching: 1000 msgs / 30s", indent: 2 },
    ],
    yamlFilename: "03-kafka-real-time-streaming.yaml",
    yamlCode:
      'name: kafka-fan-out\ntype: pipeline\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.edge_node_id = env("NODE_ID")\n          root.processing_timestamp = now()\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses:\n              - ${KAFKA_TLS_BROKERS}\n            topic: sensor-events\n            key: ${!json("sensor_id")}\n            batching:\n              count: 100\n              period: 2s\n            compression: snappy\n            tls:\n              enabled: true\n              root_cas_file: ${KAFKA_CA_FILE}\n            sasl:\n              mechanism: SCRAM-SHA-512\n              user: ${KAFKA_USERNAME}\n              password: ${KAFKA_PASSWORD}\n        - broker:\n            outputs:\n              - file:\n                  path: /var/data/archive.jsonl\n            batching:\n              count: 1000\n              period: 30s\n',
    configSha256:
      "sha256:d5018d69411029f16ca879c9feabbac165fa96a00a81041e481701e66e452155",
  },
  {
    id: 4,
    slug: "s3-long-term-archive",
    title: "S3 Long-Term Archive",
    description:
      "Object-storage destination with authored batching and compression settings that require environment-specific review.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0 },
      { content: "", indent: 0 },
      { content: "  → kafka: sensor-events", indent: 1 },
      { content: "    batching: 100 msgs / 2s", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → aws_s3: sensor-data-archive", indent: 1, type: "added" },
      { content: "    path: data/dt=2025-01-20/events.jsonl.gz", indent: 2 },
      { content: "    batching: 10000 msgs / 30m", indent: 2 },
      { content: "    compression: gzip", indent: 2 },
      { content: "    storage: INTELLIGENT_TIERING", indent: 2 },
    ],
    yamlFilename: "04-s3-long-term-archive.yaml",
    yamlCode:
      'name: s3-fan-out\ntype: pipeline\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.edge_node_id = env("NODE_ID")\n          root.processing_timestamp = now()\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses:\n              - ${KAFKA_TLS_BROKERS}\n            topic: sensor-events\n            batching:\n              count: 100\n              period: 2s\n            tls:\n              enabled: true\n              root_cas_file: ${KAFKA_CA_FILE}\n            sasl:\n              mechanism: SCRAM-SHA-512\n              user: ${KAFKA_USERNAME}\n              password: ${KAFKA_PASSWORD}\n        - aws_s3:\n            bucket: ${S3_BUCKET}\n            path: data/dt=${!now().ts_format("2006-01-02")}/events.jsonl.gz\n            batching:\n              count: 10000\n              period: 30m\n            content_encoding: gzip\n            storage_class: INTELLIGENT_TIERING\n            region: ${AWS_REGION}\n            server_side_encryption: aws:kms\n            kms_key_id: ${S3_KMS_KEY_ARN}\n',
    configSha256:
      "sha256:809edeb1878c1e41ebe0a9f0377261d4cbb710bbc200bc190ad8436c0563a0a1",
  },
  {
    id: 5,
    slug: "elasticsearch-search-analytics",
    title: "Elasticsearch Search & Analytics",
    description:
      "Search and analytics destination with balanced batching for near real-time indexing and operational monitoring.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"event_id": "sensor-001",',
        indent: 1,
        key: "event_id",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-42",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"timestamp": "2025-01-20T10:30:00Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"temperature": 23.5,',
        indent: 1,
        key: "temperature",
        valueType: "number",
      },
      {
        content: '"humidity": 65.2,',
        indent: 1,
        key: "humidity",
        valueType: "number",
      },
      { content: '"analytics": {', indent: 1, key: "analytics", type: "added" },
      { content: '  "event_hour": 10,', indent: 2 },
      { content: '  "temp_status": "normal"', indent: 2 },
      { content: "}", indent: 1 },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "→ broker (fan_out):", indent: 0 },
      { content: "", indent: 0 },
      { content: "  → kafka: sensor-events", indent: 1 },
      { content: "    batching: 100 msgs / 2s", indent: 2 },
      { content: "", indent: 0 },
      { content: "  → aws_s3: sensor-data-archive", indent: 1 },
      { content: "    batching: 10000 msgs / 30m", indent: 2 },
      { content: "", indent: 0 },
      {
        content: "  → elasticsearch: sensor-events-*",
        indent: 1,
        type: "added",
      },
      { content: "    index: sensor-events-2025-01-20", indent: 2 },
      { content: "    id: sensor-001", indent: 2 },
      { content: "    batching: 250 msgs / 10s", indent: 2 },
    ],
    yamlFilename: "05-elasticsearch-search-analytics.yaml",
    yamlCode:
      'name: complete-fan-out\ntype: pipeline\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.edge_node_id = env("NODE_ID")\n          root.processing_timestamp = now()\n          root.analytics = {\n            "event_hour": this.timestamp.ts_format("15").number(),\n            "temp_status": if this.temperature > 35 { "high" } else { "normal" }\n          }\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses:\n              - ${KAFKA_TLS_BROKERS}\n            topic: sensor-events\n            batching:\n              count: 100\n              period: 2s\n            tls:\n              enabled: true\n              root_cas_file: ${KAFKA_CA_FILE}\n            sasl:\n              mechanism: SCRAM-SHA-512\n              user: ${KAFKA_USERNAME}\n              password: ${KAFKA_PASSWORD}\n        - aws_s3:\n            bucket: ${S3_BUCKET}\n            path: data/dt=${!now().ts_format("2006-01-02")}/events.jsonl.gz\n            batching:\n              count: 10000\n              period: 30m\n              processors:\n                - compress:\n                    algorithm: gzip\n            region: ${AWS_REGION}\n            server_side_encryption: aws:kms\n            kms_key_id: ${S3_KMS_KEY_ARN}\n            content_encoding: gzip\n        - http_client:\n            url: ${ELASTICSEARCH_HTTPS_URL}/sensor-events-${!now().ts_format("2006-01-02")}/_doc/${! this.event_id.or(uuid_v4()) }\n            verb: PUT\n            headers:\n              Authorization: ApiKey ${ELASTICSEARCH_API_KEY}\n              Content-Type: application/json\n            tls:\n              enabled: true\n              root_cas_file: ${ELASTICSEARCH_CA_FILE}\n            batching:\n              count: 250\n              period: 10s\n',
    configSha256:
      "sha256:2d4e4d12c18e20babe59f304eac17527456f7a956ce24c75feee34b810de3dda",
  },
] satisfies readonly GeneratedExplorerStageConfig[];

export const GENERATED_EXPLORER_STAGE_FAMILY = {
  ...{
    binding: {
      exampleId: "fan-out-pattern",
      canonicalPipelinePath: "static/files/data-routing/fan-out-pattern.yaml",
      provenance: "curated-explanation",
      executionStatus: "architecture-only",
      operationalEvidence: "not-assessed",
      fixtureLabel: "01-single-destination.yaml",
      comparisonMode: "highlights",
    },
    canonicalPipelinePath: "static/files/data-routing/fan-out-pattern.yaml",
    pipelineSha256:
      "sha256:23a04374c44a9e020f68736d478bfbc5b1ff0ae347de59f7e30982e02f821af3",
    fullYamlFilename: "fan-out-pattern.yaml",
    fullYaml:
      "name: multi-destination-sensor-data\ndescription: Send sensor data to authenticated Kafka, encrypted S3, and authenticated Elasticsearch\ntype: pipeline\nnamespace: production\nlabels:\n  environment: production\n  data-type: sensor-metrics\n\nconfig:\n  input:\n    http_server:\n      address: 0.0.0.0:8080\n      path: /events\n      allowed_verbs: [POST]\n\n  pipeline:\n    processors:\n      - mapping: |\n          root = this\n          root.processed_at = now()\n          root.node_id = env(\"NODE_ID\").or(\"unknown\")\n\n  output:\n    broker:\n      pattern: fan_out\n      outputs:\n        - kafka:\n            addresses: ['${KAFKA_TLS_BROKERS}']\n            topic: sensor-events\n            key: '${! this.sensor_id }'\n            tls:\n              enabled: true\n              root_cas_file: ${KAFKA_CA_FILE}\n            sasl:\n              mechanism: SCRAM-SHA-512\n              user: '${KAFKA_USERNAME}'\n              password: '${KAFKA_PASSWORD}'\n            ack_replicas: true\n            batching:\n              count: 100\n              period: 5s\n\n        - aws_s3:\n            bucket: '${S3_BUCKET}'\n            region: '${AWS_REGION}'\n            path: 'events/date=${! now().ts_format(\"2006-01-02\") }/${! uuid_v4() }.json'\n            content_type: application/json\n            storage_class: INTELLIGENT_TIERING\n            server_side_encryption: aws:kms\n            kms_key_id: '${S3_KMS_KEY_ARN}'\n            batching:\n              count: 100\n              period: 30s\n\n        - http_client:\n            url: '${ELASTICSEARCH_HTTPS_URL}/sensor-events-${! now().ts_format(\"2006-01-02\") }/_doc/${! this.event_id.or(uuid_v4()) }'\n            verb: PUT\n            headers:\n              Authorization: 'ApiKey ${ELASTICSEARCH_API_KEY}'\n              Content-Type: application/json\n            tls:\n              enabled: true\n              root_cas_file: ${ELASTICSEARCH_CA_FILE}\n",
  },
  stages: GENERATED_EXPLORER_STAGES,
} satisfies GeneratedExplorerStageFamily;
