/** Generated by scripts/generate-explorer-stage-configs.ts. */
import type {
  GeneratedExplorerStageConfig,
  GeneratedExplorerStageFamily,
} from "../explorerStageConfigs.generated";

export const GENERATED_EXPLORER_STAGES = [
  {
    id: 1,
    slug: "original-input",
    title: "Original Input",
    description: "Raw log data from multiple sources in different formats",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: "level",
        valueType: "string",
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: "service",
        valueType: "string",
      },
      {
        content: '"message": "Database connection failed"',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: "level",
        valueType: "string",
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: "service",
        valueType: "string",
      },
      {
        content: '"message": "Database connection failed"',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      { content: "}", indent: 0 },
    ],
    yamlFilename: "01-original-input.yaml",
    yamlCode:
      "pipeline:\n  processors: [] # Raw mixed-format input; no parsing yet\n",
    configSha256:
      "sha256:e486bb8b301ec8a2c2f10fcc419b9aab7ded32d32ac6132daeeace1fedd02937",
  },
  {
    id: 2,
    slug: "format-detection",
    title: "Format Detection",
    description:
      "Apply the authored content checks and add a candidate format label.",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: "level",
        valueType: "string",
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: "service",
        valueType: "string",
      },
      {
        content: '"message": "Database connection failed"',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: "level",
        valueType: "string",
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: "service",
        valueType: "string",
      },
      {
        content: '"message": "Database connection failed",',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      {
        content: '"detected_format": "json"',
        indent: 1,
        key: "detected_format",
        valueType: "string",
        type: "highlighted",
      },
      { content: "}", indent: 0 },
    ],
    yamlFilename: "02-format-detection.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    # Detect log format based on content patterns\n    - mapping: |\n        root = this\n        root.detected_format = if this.string().has_prefix("{") {\n          "json"\n        } else if this.string().has_prefix("<") {\n          "syslog"\n        } else if this.string().contains(" - - [") {\n          "access_log"\n        } else if this.string().contains(",") {\n          "csv"\n        } else {\n          "unknown"\n        }\n        meta log_format = root.detected_format\n',
    configSha256:
      "sha256:b3e809b8dd0cdc53897a077058bad2be1e3b0186953a7a69a65adf7476dfff4b",
  },
  {
    id: 3,
    slug: "json-log-parsing",
    title: "JSON Log Parsing",
    description:
      "Parse JSON application logs with timestamp normalization and field validation",
    inputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: "level",
        valueType: "string",
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: "service",
        valueType: "string",
      },
      {
        content: '"message": "Database connection failed",',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      {
        content: '"detected_format": "json"',
        indent: 1,
        key: "detected_format",
        valueType: "string",
      },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: "timestamp_unix",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"level": "ERROR",',
        indent: 1,
        key: "level",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: "service",
        valueType: "string",
      },
      {
        content: '"message": "Database connection failed",',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      { content: '"metadata": {', indent: 1, type: "highlighted" },
      {
        content: '"parsed_by": "json-parser",',
        indent: 2,
        key: "parsed_by",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"parsed_at": 1729433025,',
        indent: 2,
        key: "parsed_at",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"source_format": "json"',
        indent: 2,
        key: "source_format",
        valueType: "string",
        type: "highlighted",
      },
      { content: "}", indent: 1, type: "highlighted" },
      { content: "}", indent: 0 },
    ],
    yamlFilename: "03-json-log-parsing.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    # Parse JSON documents\n    - json_documents:\n        parts: []\n\n    # Normalize timestamp and add metadata\n    - mapping: |\n        root = this\n        root.timestamp_unix = this.timestamp.parse_timestamp("2006-01-02T15:04:05.999Z07:00").ts_unix()\n        root.level = this.level.or("INFO").uppercase()\n        root.metadata = {\n          "parsed_by": "json-parser",\n          "parsed_at": now().ts_unix(),\n          "source_format": "json"\n        }\n',
    configSha256:
      "sha256:e03eee34bb5b3066a15fbcf5f06c0abfd7e69037d697ab843d988acf3b19af3f",
  },
  {
    id: 4,
    slug: "csv-data-parsing",
    title: "CSV Data Parsing",
    description:
      "Parse CSV sensor data with column mapping, type conversion, and validation rules",
    inputLines: [
      {
        content: "2025-10-20,temperature,temp-sensor-01,35.5,celsius",
        indent: 0,
      },
    ],
    outputLines: [
      { content: "{", indent: 0 },
      {
        content: '"timestamp": "2025-10-20",',
        indent: 1,
        key: "timestamp",
        valueType: "string",
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: "timestamp_unix",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"metric_name": "temperature",',
        indent: 1,
        key: "metric_name",
        valueType: "string",
      },
      {
        content: '"sensor_id": "temp-sensor-01",',
        indent: 1,
        key: "sensor_id",
        valueType: "string",
      },
      {
        content: '"value": "35.5",',
        indent: 1,
        key: "value",
        valueType: "string",
      },
      {
        content: '"value_numeric": 35.5,',
        indent: 1,
        key: "value_numeric",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"unit": "celsius",',
        indent: 1,
        key: "unit",
        valueType: "string",
      },
      { content: '"sensor_metadata": {', indent: 1, type: "highlighted" },
      {
        content: '"type": "temperature",',
        indent: 2,
        key: "type",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"location": "warehouse"',
        indent: 2,
        key: "location",
        valueType: "string",
        type: "highlighted",
      },
      { content: "},", indent: 1, type: "highlighted" },
      { content: '"alert": {', indent: 1, type: "highlighted" },
      {
        content: '"level": "critical",',
        indent: 2,
        key: "level",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"message": "Temperature exceeds threshold"',
        indent: 2,
        key: "message",
        valueType: "string",
        type: "highlighted",
      },
      { content: "}", indent: 1, type: "highlighted" },
      { content: "}", indent: 0 },
    ],
    yamlFilename: "04-csv-data-parsing.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    # Parse CSV with named columns\n    - csv:\n        columns: [timestamp, metric_name, sensor_id, value, unit]\n        delimiter: ","\n\n    # Convert types and add sensor metadata\n    - mapping: |\n        root = this\n        root.timestamp_unix = this.timestamp.parse_timestamp("2006-01-02").ts_unix()\n        root.value_numeric = this.value.number()\n        root.sensor_metadata = if this.sensor_id.has_prefix("temp-") {\n          {"type": "temperature", "location": "warehouse"}\n        } else {\n          {"type": "unknown", "location": "unknown"}\n        }\n        root.alert = if this.metric_name == "temperature" && this.value_numeric > 30 {\n          {"level": "critical", "message": "Temperature exceeds threshold"}\n        }\n',
    configSha256:
      "sha256:36b3cb4b520b2746d03d5177639bb351278f06cb65d71c24280bc46baaabf7e3",
  },
  {
    id: 5,
    slug: "access-log-parsing",
    title: "Access Log Parsing",
    description:
      "Apply one authored access-log pattern and map selected client and request fields.",
    inputLines: [
      {
        content:
          '203.0.113.45 - - [20/Oct/2025:14:23:45 +0000] "GET /api/users HTTP/1.1" 200 1234',
        indent: 0,
      },
    ],
    outputLines: [
      { content: "{", indent: 0 },
      {
        content: '"client_ip_hash": "7b9d4e2f1c8a6e3b",',
        indent: 1,
        key: "client_ip_hash",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: "timestamp_unix",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"method": "GET",',
        indent: 1,
        key: "method",
        valueType: "string",
      },
      {
        content: '"request": "/api/users",',
        indent: 1,
        key: "request",
        valueType: "string",
      },
      {
        content: '"http_version": "1.1",',
        indent: 1,
        key: "http_version",
        valueType: "string",
      },
      {
        content: '"status_code": 200,',
        indent: 1,
        key: "status_code",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"bytes": 1234,',
        indent: 1,
        key: "bytes",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"request_category": "api",',
        indent: 1,
        key: "request_category",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"is_error": false',
        indent: 1,
        key: "is_error",
        valueType: "boolean",
        type: "highlighted",
      },
      { content: "}", indent: 0 },
    ],
    yamlFilename: "05-access-log-parsing.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    # Parse using grok pattern (Apache Combined Format)\n    - grok:\n        expressions:\n          - \'%{IPORHOST:client_ip} %{USER:ident} %{USER:auth} \\[%{HTTPDATE:timestamp}\\] "(?:%{WORD:method} %{NOTSPACE:request}(?: HTTP/%{NUMBER:http_version})?|%{DATA})" %{NUMBER:status_code} (?:%{NUMBER:bytes}|-)\'\n        named_captures_only: true\n\n    # Convert types and classify requests\n    - mapping: |\n        root = this\n        root.timestamp_unix = this.timestamp.parse_timestamp("02/Jan/2006:15:04:05 -0700").ts_unix()\n        root.status_code = this.status_code.number()\n        root.bytes = this.bytes.or("0").number()\n        root.request_category = if this.request.contains("/api/") {\n          "api"\n        } else if this.request.contains("/static/") {\n          "static"\n        } else { "page" }\n        root.is_error = this.status_code >= 400\n        # Hash IP for privacy\n        root.client_ip_hash = (this.client_ip + env("IP_SALT")).hash("sha256").slice(0, 16)\n        root = this.without("client_ip")\n',
    configSha256:
      "sha256:14c296cb297ea4348612958929f2397143ec057eb1fc38a93ebc48e7c41295fb",
  },
  {
    id: 6,
    slug: "syslog-message-parsing",
    title: "Syslog Message Parsing",
    description:
      "Parse RFC3164 syslog messages with priority decomposition and severity classification",
    inputLines: [
      {
        content:
          "<134>Oct 20 14:23:45 edge-node-01 app[12345]: Database connection established",
        indent: 0,
      },
    ],
    outputLines: [
      { content: "{", indent: 0 },
      {
        content: '"priority": 134,',
        indent: 1,
        key: "priority",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"facility": 16,',
        indent: 1,
        key: "facility",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"severity": 6,',
        indent: 1,
        key: "severity",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"severity_name": "Informational",',
        indent: 1,
        key: "severity_name",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: "timestamp_unix",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"hostname": "edge-node-01",',
        indent: 1,
        key: "hostname",
        valueType: "string",
      },
      { content: '"tag": "app",', indent: 1, key: "tag", valueType: "string" },
      {
        content: '"process_id": 12345,',
        indent: 1,
        key: "process_id",
        valueType: "number",
        type: "highlighted",
      },
      {
        content: '"application": "app",',
        indent: 1,
        key: "application",
        valueType: "string",
        type: "highlighted",
      },
      {
        content: '"message": "Database connection established"',
        indent: 1,
        key: "message",
        valueType: "string",
      },
      { content: "}", indent: 0 },
    ],
    yamlFilename: "06-syslog-message-parsing.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    # Parse syslog format (RFC3164)\n    - grok:\n        expressions:\n          - \'<%{POSINT:priority}>%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:hostname} %{DATA:tag}(?:\\[%{POSINT:pid}\\])?: %{GREEDYDATA:message}\'\n        named_captures_only: true\n\n    # Parse priority to facility and severity\n    - mapping: |\n        root = this\n        let pri = this.priority.number()\n        root.facility = (pri / 8).floor()\n        root.severity = pri % 8\n        root.severity_name = if this.severity == 0 {\n          "Emergency"\n        } else if this.severity <= 2 {\n          "Critical"\n        } else if this.severity <= 4 {\n          "Warning"\n        } else {\n          "Informational"\n        }\n        # Parse timestamp (add current year)\n        let year = now().ts_format("2006")\n        root.timestamp_unix = (year + " " + this.timestamp).parse_timestamp("2006 Jan 02 15:04:05").ts_unix()\n        root.application = this.tag\n        root.process_id = this.pid.or("").number()\n',
    configSha256:
      "sha256:ddec41600e2a2f5a76d3f2d7f0370ae42bb5541052583ae2caddb68b02ad889d",
  },
] satisfies readonly GeneratedExplorerStageConfig[];

export const GENERATED_EXPLORER_STAGE_FAMILY = {
  ...{
    binding: {
      exampleId: "parse-logs",
      canonicalPipelinePath: "static/files/data-transformation/parse-logs.yaml",
      provenance: "curated-explanation",
      executionStatus: "architecture-only",
      operationalEvidence: "not-assessed",
      fixtureLabel: "01-original-input.yaml",
      comparisonMode: "highlights",
    },
    canonicalPipelinePath: "static/files/data-transformation/parse-logs.yaml",
    pipelineSha256:
      "sha256:9ceb0430dbcc9fd0f89ca5557e109be3ce8874b093c354868b09fa10d564d728",
    fullYamlFilename: "parse-logs.yaml",
    fullYaml:
      'name: json-log-parser\ndescription: Parse and normalize JSON application logs\ntype: pipeline\nnamespace: default\n\nconfig:\n  input:\n    file:\n      paths:\n        - /var/log/app/*.jsonl\n      codec: lines\n\n  pipeline:\n    processors:\n      # Parse JSON\n      - json_documents:\n          parts: []\n\n      # Parse and normalize timestamp\n      - mapping: |\n          root = this\n          root.timestamp_unix = this.timestamp.parse_timestamp("2006-01-02T15:04:05.999Z07:00").ts_unix()\n          root.timestamp_iso = this.timestamp\n\n      # Normalize log level\n      - mapping: |\n          root = this\n          root.level = this.level.uppercase()\n\n      # Extract error details\n      - mapping: |\n          root = this\n          root.error_details = if this.error.exists() {\n            {\n              "message": this.error,\n              "stack_trace": this.stack_trace.or(""),\n              "error_code": this.error_code.or(""),\n              "timestamp": this.timestamp_unix\n            }\n          }\n\n      # Add metadata\n      - mapping: |\n          root = this\n          root.metadata = {\n            "parsed_by": "json-parser",\n            "parsed_at": now().ts_unix(),\n            "source_node": env("NODE_ID").or("unknown")\n          }\n\n      # Remove debug fields\n      - mapping: |\n          root = this.without("debug_info", "internal_state", "raw_request")\n\n      # Filter by log level (only WARN, ERROR, FATAL)\n      - mapping: |\n          root = if this.level.or("INFO") in ["WARN", "ERROR", "FATAL"] {\n            this\n          } else {\n            deleted()\n          }\n\n  output:\n    http_client:\n      url: "${LOG_ENDPOINT}/logs"\n      verb: POST\n      batching:\n        count: 100\n        period: 10s\n      max_retries: 3\n',
  },
  stages: GENERATED_EXPLORER_STAGES,
} satisfies GeneratedExplorerStageFamily;
