/** Generated by scripts/generate-explorer-stage-configs.ts. */
import type {
  GeneratedExplorerStageConfig,
  GeneratedExplorerStageFamily,
} from "../explorerStageConfigs.generated";

export const GENERATED_EXPLORER_STAGES = [
  {
    id: 1,
    slug: "json-input",
    title: "JSON Input",
    description:
      "A representative JSON record before a schema-backed encoding is selected.",
    inputLines: [
      { content: "{", indent: 0 },
      { content: '"sensor_id": "sensor-42",', indent: 1 },
      { content: '"temperature_celsius": 23.5,', indent: 1 },
      { content: '"humidity_percent": 45.2,', indent: 1 },
      { content: '"timestamp": "2024-01-15T10:30:00Z"', indent: 1 },
      { content: "}", indent: 0 },
    ],
    outputLines: [
      { content: "JSON review points:", indent: 0, type: "highlighted" },
      { content: "Field names and numeric types are explicit", indent: 1 },
      { content: "No schema artifact is attached to this record", indent: 1 },
    ],
    yamlFilename: "01-json-input.yaml",
    yamlCode:
      "pipeline:\n  processors: [] # JSON input; no format conversion yet\n",
    configSha256:
      "sha256:97bf3c31922063b8a4c1e2756d9046874a5ab5f5a3328dc84fb14556fccb9973",
  },
  {
    id: 2,
    slug: "json-avro",
    title: "JSON → Avro",
    description:
      "Attach a representative Avro record schema and review writer-reader compatibility separately.",
    inputLines: [
      { content: '{"sensor_id":"sensor-42",', indent: 0 },
      { content: '"temperature_celsius":23.5,', indent: 0 },
      { content: '"humidity_percent":45.2,', indent: 0 },
      { content: '"timestamp":"2024-01-15T10:30:00Z"}', indent: 0 },
    ],
    outputLines: [
      { content: "Avro review points:", indent: 0, type: "highlighted" },
      { content: "Schema: enforced at write", indent: 1 },
      {
        content: "Reader compatibility requires a versioned schema policy",
        indent: 1,
      },
    ],
    yamlFilename: "02-json-avro.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    - avro:\n        operator: to_json\n        schema: |\n          {\n            "type": "record",\n            "name": "SensorReading",\n            "fields": [\n              {"name": "sensor_id", "type": "string"},\n              {"name": "temperature_celsius", "type": "double"},\n              {"name": "humidity_percent", "type": "double"},\n              {"name": "timestamp", "type": "string"}\n            ]\n          }\n',
    configSha256:
      "sha256:b149935884be5c3dbd96fa9cafcfd9087e197b53425e7115b32f754b8a8fe2b5",
  },
  {
    id: 3,
    slug: "avro-parquet",
    title: "Avro → Parquet",
    description:
      "Configure a representative Parquet object output and review column types and partitioning.",
    inputLines: [
      { content: '{"sensor_id":"sensor-42",', indent: 0 },
      { content: '"temperature_celsius":23.5,', indent: 0 },
      { content: '"humidity_percent":45.2}', indent: 0 },
    ],
    outputLines: [
      { content: "Parquet review points:", indent: 0, type: "highlighted" },
      { content: "Column types come from the configured writer", indent: 1 },
      {
        content: "Object partitioning remains a destination decision",
        indent: 1,
      },
    ],
    yamlFilename: "03-avro-parquet.yaml",
    yamlCode:
      "output:\n  aws_s3:\n    bucket: sensor-data-lake\n    path: readings/${!timestamp_unix()}.parquet\n    codec: parquet\n    compression: snappy\n    # Columnar storage for fast analytics\n",
    configSha256:
      "sha256:268ec86ef676344f3e9306d95e133fa3fa2591dc132b0c4cf73b6288179f903e",
  },
  {
    id: 4,
    slug: "auto-detection",
    title: "Auto-Detection",
    description:
      "Apply the two authored checks for JSON objects and an Avro prefix, then report an unknown format.",
    inputLines: [
      { content: "Representative inputs:", indent: 0 },
      { content: '{"sensor_id":"sensor-42"}  (JSON)', indent: 1 },
      { content: "Obj\\x01\\x02... (Avro)", indent: 1 },
      { content: "\\x08\\x12... (unknown to this mapping)", indent: 1 },
    ],
    outputLines: [
      { content: "Authored branch labels:", indent: 0, type: "highlighted" },
      { content: "JSON object: pass through mapping", indent: 1 },
      { content: "Avro prefix: enter Avro branch", indent: 1 },
      { content: "Other bytes: log unknown format", indent: 1 },
    ],
    yamlFilename: "04-auto-detection.yaml",
    yamlCode:
      'pipeline:\n  processors:\n    - switch:\n        - check: this.type() == "object"\n          processors:\n            - mapping: \'root = this # JSON detected\'\n        - check: content().has_prefix("Obj\\x01")\n          processors:\n            - avro: {operator: from_json} # Avro detected\n        - processors:\n            - log:\n                message: "Unknown format: ${!content()}"\n',
    configSha256:
      "sha256:a82fdfc35a5a7f2456c9765018e7a5e25664da235822f2ba7c710bc76be68bea",
  },
] satisfies readonly GeneratedExplorerStageConfig[];

export const GENERATED_EXPLORER_STAGE_FAMILY = {
  ...{
    binding: {
      exampleId: "transform-formats",
      canonicalPipelinePath:
        "static/files/data-transformation/transform-formats.yaml",
      provenance: "curated-explanation",
      executionStatus: "architecture-only",
      operationalEvidence: "not-assessed",
      fixtureLabel: "01-json-input.yaml",
      comparisonMode: "highlights",
    },
    canonicalPipelinePath:
      "static/files/data-transformation/transform-formats.yaml",
    pipelineSha256:
      "sha256:983f1ed9ebda30eed6cdcfa5631449e2a657448d6cb5f98e17d46600a19895be",
    fullYamlFilename: "transform-formats.yaml",
    fullYaml:
      "config:\n  input:\n    http_server:\n      address: '0.0.0.0:8080'\n      path: /sensors/ingest\n\n  pipeline:\n    processors:\n      # Parse JSON\n      - mapping: root = content().parse_json()\n      # Validate and flatten\n      - mapping: |\n          root.sensor_id = this.sensor_id\n          root.location = this.location\n          root.temperature = this.temperature\n          root.humidity = this.humidity\n          root.timestamp = this.timestamp\n          root.device_type = this.metadata.device_type\n          root.firmware_version = this.metadata.firmware_version\n      - subprocess:\n          name: node\n          args:\n            - -e\n            - |-\n              const fields=[['sensor_id','string'],['location','string'],['temperature','double'],['humidity','double'],['timestamp','string'],['device_type','string'],['firmware_version','string']];\n              const encode=(value,type)=>{if(type==='double'){if(typeof value!=='number'||!Number.isFinite(value))throw Error('Invalid double');const b=Buffer.alloc(8);b.writeDoubleLE(value);return b;}if(typeof value!=='string')throw Error('Invalid string');const b=Buffer.from(value,'utf8');let n=BigInt(b.length)*2n;const size=[];do{let x=Number(n&127n);n>>=7n;if(n)x|=128;size.push(x);}while(n);return Buffer.concat([Buffer.from(size),b]);};\n              require('node:readline').createInterface({input:process.stdin}).on('line',line=>{try{const r=JSON.parse(line);const data=Buffer.concat(fields.map(([name,type])=>encode(r[name],type)));const prefix=Buffer.alloc(4);prefix.writeUInt32BE(data.length);process.stdout.write(Buffer.concat([prefix,data]));}catch(e){process.stderr.write(e.message+'\\n');process.exitCode=1;}});\n          codec_recv: length_prefixed_uint32_be\n\n  output:\n    kafka:\n      addresses: [ '${KAFKA_BROKER}' ]\n      topic: sensor-readings-avro\n      compression: snappy\ndescription: Encode SensorReading records as binary Avro; requires Node.js on each edge node.\n",
  },
  stages: GENERATED_EXPLORER_STAGES,
} satisfies GeneratedExplorerStageFamily;
