import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const enrichExportStages: Stage[] = [
  {
    id: 1,
    slug: 'original-log-data',
    title: 'Original Log Data',
    description:
      'A synthetic application log before processing fields are added or regrouped.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 1,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "INFO",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "demo-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"user_id": "user_123",',
        indent: 1,
        key: 'user_id',
        valueType: 'string',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"',
        indent: 1,
        key: 'request_id',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 1,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "INFO",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "demo-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"user_id": "user_123",',
        indent: 1,
        key: 'user_id',
        valueType: 'string',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"',
        indent: 1,
        key: 'request_id',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'add-lineage-metadata',
    title: 'Add Lineage Metadata',
    description:
      'Add configured node, pipeline, and processing-time fields to the synthetic record.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 1,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "INFO",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "demo-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"user_id": "user_123",',
        indent: 1,
        key: 'user_id',
        valueType: 'string',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"',
        indent: 1,
        key: 'request_id',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 1,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "INFO",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "demo-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"user_id": "user_123",',
        indent: 1,
        key: 'user_id',
        valueType: 'string',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",',
        indent: 1,
        key: 'request_id',
        valueType: 'string',
      },
      {
        content: '"lineage_node_id": "edge-node-01",',
        indent: 1,
        key: 'lineage_node_id',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"lineage_pipeline": "log-enrichment-s3-demo",',
        indent: 1,
        key: 'lineage_pipeline',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"lineage_timestamp": "2024-01-15T10:30:00.123Z"',
        indent: 1,
        key: 'lineage_timestamp',
        valueType: 'string',
        type: 'added',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'restructure-to-event-metadata',
    title: 'Restructure to Event/Metadata',
    description:
      'Regroup the authored fields under event and processing-metadata objects.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 1,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "INFO",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "demo-service",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"user_id": "user_123",',
        indent: 1,
        key: 'user_id',
        valueType: 'string',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",',
        indent: 1,
        key: 'request_id',
        valueType: 'string',
      },
      {
        content: '"lineage_node_id": "edge-node-01",',
        indent: 1,
        key: 'lineage_node_id',
        valueType: 'string',
      },
      {
        content: '"lineage_pipeline": "log-enrichment-s3-demo",',
        indent: 1,
        key: 'lineage_pipeline',
        valueType: 'string',
      },
      {
        content: '"lineage_timestamp": "2024-01-15T10:30:00.123Z"',
        indent: 1,
        key: 'lineage_timestamp',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      { content: '"event": {', indent: 1, type: 'highlighted' },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 2,
        key: 'id',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 2,
        key: 'timestamp',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"level": "INFO",',
        indent: 2,
        key: 'level',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"service": "demo-service",',
        indent: 2,
        key: 'service',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 2,
        key: 'message',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"user_id": "user_123",',
        indent: 2,
        key: 'user_id',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"',
        indent: 2,
        key: 'request_id',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '},', indent: 1, type: 'highlighted' },
      { content: '"metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"node_id": "edge-node-01",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"pipeline": "log-enrichment-s3-demo",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"processed_at": "2024-01-15T10:30:00.123Z"',
        indent: 2,
        key: 'processed_at',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'configure-batching',
    title: 'Configure Batching',
    description: 'Configure a batch boundary of ten messages or ten seconds.',
    inputLines: [
      { content: '{', indent: 0 },
      { content: '"event": {', indent: 1 },
      {
        content: '"id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2024-01-15T10:30:00Z",',
        indent: 2,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "INFO",',
        indent: 2,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "demo-service",',
        indent: 2,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Demo log message from edge",',
        indent: 2,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"user_id": "user_123",',
        indent: 2,
        key: 'user_id',
        valueType: 'string',
      },
      {
        content: '"request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"',
        indent: 2,
        key: 'request_id',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"metadata": {', indent: 1 },
      {
        content: '"node_id": "edge-node-01",',
        indent: 2,
        key: 'node_id',
        valueType: 'string',
      },
      {
        content: '"pipeline": "log-enrichment-s3-demo",',
        indent: 2,
        key: 'pipeline',
        valueType: 'string',
      },
      {
        content: '"processed_at": "2024-01-15T10:30:00.123Z"',
        indent: 2,
        key: 'processed_at',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '# Batching: 10 messages or 10 seconds', indent: 0 },
      {
        content: '# Output: s3://expanso-demo-logs/logs/demo_1705315800.jsonl',
        indent: 0,
      },
      { content: '', indent: 0 },
      { content: '[10 messages batched]', indent: 0, type: 'highlighted' },
    ],
  },
  {
    id: 5,
    slug: 'configured-s3-object',
    title: 'Configured S3 Object',
    description:
      'Show the authored JSON Lines object key and record shape for the configured S3 output.',
    inputLines: [{ content: '[Batch of 10 messages]', indent: 0 }],
    outputLines: [
      {
        content:
          '# S3 Location: s3://expanso-demo-logs/logs/demo_1705315800.jsonl',
        indent: 0,
        type: 'highlighted',
      },
      { content: '# Format: JSON Lines', indent: 0, type: 'highlighted' },
      { content: '# Messages: 10', indent: 0, type: 'highlighted' },
      {
        content: '# Batch Policy Enabled: true',
        indent: 0,
        type: 'highlighted',
      },
      { content: '# Analytics Ready: true', indent: 0, type: 'highlighted' },
    ],
  },
];
