import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const enrichExportStages: Stage[] = [
  {
    title: "Original Log Data",
    description: "Raw application logs generated by your services with basic event information.",
    yamlCode: `input:
  generate:
    interval: 2s
    mapping: |
      root.id = uuid_v4()
      root.timestamp = now()
      root.level = "INFO"
      root.service = "demo-service"
      root.message = "Demo log message from edge"
      root.user_id = "user_123"
      root.request_id = uuid_v4()`,
    inputData: null,
    outputData: {
      "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "timestamp": "2024-01-15T10:30:00Z",
      "level": "INFO",
      "service": "demo-service",
      "message": "Demo log message from edge",
      "user_id": "user_123",
      "request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"
    }
  },
  {
    title: "Add Lineage Metadata",
    description: "Enhanced with processing metadata including node ID, pipeline name, and processing timestamp for complete audit trails.",
    yamlCode: `pipeline:
  processors:
    - mapping: |
        root = this
        root.lineage_node_id = env("NODE_ID").or("edge-node-demo")
        root.lineage_pipeline = "log-enrichment-s3-demo"
        root.lineage_timestamp = now()`,
    inputData: {
      "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "timestamp": "2024-01-15T10:30:00Z",
      "level": "INFO",
      "service": "demo-service",
      "message": "Demo log message from edge",
      "user_id": "user_123",
      "request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"
    },
    outputData: {
      "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "timestamp": "2024-01-15T10:30:00Z",
      "level": "INFO",
      "service": "demo-service",
      "message": "Demo log message from edge",
      "user_id": "user_123",
      "request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      "lineage_node_id": "edge-node-01",
      "lineage_pipeline": "log-enrichment-s3-demo",
      "lineage_timestamp": "2024-01-15T10:30:00.123Z"
    }
  },
  {
    title: "Restructure to Event/Metadata",
    description: "Reorganized into clean separation between business event data and operational metadata for analytics optimization.",
    yamlCode: `    - mapping: |
        root.event = {
          "id": this.id,
          "timestamp": this.timestamp,
          "level": this.level,
          "service": this.service,
          "message": this.message,
          "user_id": this.user_id,
          "request_id": this.request_id
        }
        root.metadata = {
          "node_id": this.lineage_node_id,
          "pipeline": this.lineage_pipeline,
          "processed_at": this.lineage_timestamp
        }`,
    inputData: {
      "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      "timestamp": "2024-01-15T10:30:00Z",
      "level": "INFO",
      "service": "demo-service",
      "message": "Demo log message from edge",
      "user_id": "user_123",
      "request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      "lineage_node_id": "edge-node-01",
      "lineage_pipeline": "log-enrichment-s3-demo",
      "lineage_timestamp": "2024-01-15T10:30:00.123Z"
    },
    outputData: {
      "event": {
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "timestamp": "2024-01-15T10:30:00Z",
        "level": "INFO",
        "service": "demo-service",
        "message": "Demo log message from edge",
        "user_id": "user_123",
        "request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"
      },
      "metadata": {
        "node_id": "edge-node-01",
        "pipeline": "log-enrichment-s3-demo",
        "processed_at": "2024-01-15T10:30:00.123Z"
      }
    }
  },
  {
    title: "Configure Batching",
    description: "Messages grouped efficiently (10 messages or 10 seconds) to minimize S3 API calls and storage costs.",
    yamlCode: `output:
  aws_s3:
    bucket: expanso-demo-logs
    path: logs/demo_\${!timestamp_unix()}.jsonl
    batching:
      count: 10
      period: 10s
    credentials:
      profile: expanso-demo`,
    inputData: {
      "event": {
        "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "timestamp": "2024-01-15T10:30:00Z",
        "level": "INFO",
        "service": "demo-service",
        "message": "Demo log message from edge",
        "user_id": "user_123",
        "request_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901"
      },
      "metadata": {
        "node_id": "edge-node-01",
        "pipeline": "log-enrichment-s3-demo",
        "processed_at": "2024-01-15T10:30:00.123Z"
      }
    },
    outputData: "Batch of 10 messages ready for S3 upload:\nlogs/demo_1705315800.jsonl"
  },
  {
    title: "Ready for S3 Export",
    description: "Final JSON Lines format optimized for S3 storage with proper partitioning and metadata organization.",
    yamlCode: `# S3 File: logs/demo_1705315800.jsonl
{"event":{"id":"...","timestamp":"...","level":"INFO",...},"metadata":{"node_id":"edge-node-01",...}}
{"event":{"id":"...","timestamp":"...","level":"ERROR",...},"metadata":{"node_id":"edge-node-01",...}}
{"event":{"id":"...","timestamp":"...","level":"WARN",...},"metadata":{"node_id":"edge-node-01",...}}
...`,
    inputData: "Batch of 10 messages ready for S3 upload:\nlogs/demo_1705315800.jsonl",
    outputData: {
      "s3_location": "s3://expanso-demo-logs/logs/demo_1705315800.jsonl",
      "format": "JSON Lines",
      "messages_count": 10,
      "file_size": "2.3 KB",
      "analytics_ready": true,
      "cost_optimized": true
    }
  }
];
