pipeline:
  processors:
    - mapping: |
        root.billing_address.street_encrypted = crypto.encrypt_aes256_gcm(this.billing_address.street, env("ADDRESS_ENCRYPTION_KEY"))
        root.billing_address.zip_encrypted = crypto.encrypt_aes256_gcm(this.billing_address.zip, env("ADDRESS_ENCRYPTION_KEY"))
        root.billing_address.city = this.billing_address.city
        root.billing_address.state = this.billing_address.state
        root.billing_address.country = this.billing_address.country
