pipeline:
  processors:
    - mapping: |
        root = this
        
        # Remove both high-risk fields
        root.payment_method = this.payment_method.without(
          "full_number",
          "expiry"
        )
