pipeline:
  processors:
    - mapping: |
        root.customer.ssn_encrypted = crypto.encrypt_aes256_gcm(this.customer.ssn, env("PII_ENCRYPTION_KEY"))
        root.customer.email_encrypted = crypto.encrypt_aes256_gcm(this.customer.email, env("PII_ENCRYPTION_KEY"))
        root.customer.phone_encrypted = crypto.encrypt_aes256_gcm(this.customer.phone, env("PII_ENCRYPTION_KEY"))
        root.customer.date_of_birth_encrypted = crypto.encrypt_aes256_gcm(this.customer.date_of_birth, env("PII_ENCRYPTION_KEY"))
        root.customer.ssn_last_four = this.customer.ssn.re_replace_all("[^0-9]", "").slice(-4)
        root.customer.email_domain = this.customer.email.split("@")[1]
        root.customer.phone_area_code = this.customer.phone.re_find("\\+1-([0-9]{3})-.*")[0][1]
        root.customer.birth_year = this.customer.date_of_birth.parse_timestamp("2006-01-02").format_timestamp("2006")
