pipeline:
  processors:
    # Steps 1-4 from previous stages...

    # Step 5: Generalize location data
    - mapping: |
        root = this

        # Keep only city and country
        # Remove precise lat/long coordinates
        root.location = {
          "city": this.location.city,
          "country": this.location.country,
          "region": this.location.country  # For analytics
        }

# ✅ PII-FREE OUTPUT!
# All PII removed or transformed:
# ✓ Credit card deleted
# ✓ IP hashed
# ✓ Email hashed (domain extracted)
# ✓ User name pseudonymized
# ✓ Location generalized
