pipeline:
  processors:
    - mapping: |
        root = this
        root.encryption_metadata = {
          "encrypted": true,
          "encryption_timestamp": now(),
          "encryption_version": "1.0",
          "key_version": env("KEY_VERSION").or("v1"),
          "algorithm": "AES-256-GCM",
          "node_id": env("NODE_ID").or("edge-001"),
          "pipeline": "payment-field-encryption"
        }
