pipeline:
  processors:
    - mapping: |
        root = this
        root.customer.ssn_encrypted = this.customer.ssn.encrypt_aes_gcm(env("PII_KEY"))
        root.customer.email_encrypted = this.customer.email.encrypt_aes_gcm(env("PII_KEY"))
        root.customer.phone_encrypted = this.customer.phone.encrypt_aes_gcm(env("PII_KEY"))
        root.customer.dob_encrypted = this.customer.date_of_birth.encrypt_aes_gcm(env("PII_KEY"))
        root.customer.ssn_last_four = this.customer.ssn.re_replace_all("[^0-9]", "").slice(-4)
        root.customer.email_domain = this.customer.email.split("@")[1]
        root.customer.phone_area_code = this.customer.phone.re_find("\\\\+1-(\\\\d{3})-")[1]
        root.customer = root.customer.without("ssn", "email", "phone", "date_of_birth")
