import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const deduplicateEventsStages: Stage[] = [
  {
    id: 1,
    slug: 'original-events',
    title: 'Original Events',
    description:
      'Multiple events arrive with potential duplicates from network retries, load balancer failovers, and eventual consistency delays.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "evt_signup_001",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "user_signup",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2025-01-15T10:30:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_12345",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"email": "alice@example.com"',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "evt_signup_001",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "user_signup",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2025-01-15T10:30:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_12345",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"email": "alice@example.com"',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'hash-based-deduplication',
    title: 'Hash-Based Deduplication',
    description:
      'Generate SHA-256 hash of entire event content and cache it. Identical events (same JSON structure) are detected and filtered.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "evt_signup_001",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "user_signup",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_12345",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"email": "alice@example.com"',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "evt_signup_001",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "user_signup",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_12345",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"email": "alice@example.com"',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      {
        content: '"dedup_hash": "a1b2c3d4e5f6...",',
        indent: 1,
        key: 'dedup_hash',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '"dedup_metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"strategy": "hash-based",',
        indent: 2,
        key: 'strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"processed_at": "2025-01-15T10:30:45.150Z"',
        indent: 2,
        key: 'processed_at',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'fingerprint-based-deduplication',
    title: 'Fingerprint-Based Deduplication',
    description:
      'Build a comparison key from the selected user ID, email, and action-type fields.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "evt_signup_002",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "user_signup",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      {
        content: '"timestamp": "2025-01-15T10:30:47.892Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_12345",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"email": "alice@example.com"',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "evt_signup_001",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "user_signup",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_12345",',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      {
        content: '"email": "alice@example.com"',
        indent: 2,
        key: 'email',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      {
        content: '"business_fingerprint": "fp_a1b2c3d4...",',
        indent: 1,
        key: 'business_fingerprint',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '"fingerprint_metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"strategy": "fingerprint-based",',
        indent: 2,
        key: 'strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"business_fields": ["user.id", "user.email", "event_type"],',
        indent: 2,
        key: 'business_fields',
        valueType: 'array',
        type: 'highlighted',
      },
      {
        content: '"generated_at": "2025-01-15T10:30:45.150Z"',
        indent: 2,
        key: 'generated_at',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'id-based-deduplication',
    title: 'ID-Based Deduplication',
    description:
      'Use a source-supplied event ID as the cache key when its producer contract defines uniqueness.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "550e8400-e29b-41d4-a716-446655440000",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "purchase",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_456"',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"purchase": {', indent: 1 },
      {
        content: '"amount_cents": 9999',
        indent: 2,
        key: 'amount_cents',
        valueType: 'number',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "550e8400-e29b-41d4-a716-446655440000",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "purchase",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_456"',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"purchase": {', indent: 1 },
      {
        content: '"amount_cents": 9999',
        indent: 2,
        key: 'amount_cents',
        valueType: 'number',
      },
      { content: '},', indent: 1 },
      { content: '"dedup_metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"strategy": "id-based",',
        indent: 2,
        key: 'strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"unique_id": "550e8400-e29b-41d4-a716-446655440000",',
        indent: 2,
        key: 'unique_id',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"id_type": "uuid4",',
        indent: 2,
        key: 'id_type',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"processed_at": "2025-01-15T10:31:22.500Z"',
        indent: 2,
        key: 'processed_at',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 5,
    slug: 'external-cache-configuration',
    title: 'External Cache Configuration',
    description:
      'A review configuration sketches Redis, local fallback, metrics, and error-handling dependencies.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "550e8400-e29b-41d4-a716-446655440000",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "purchase",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_456"',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      { content: '}', indent: 1 },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"event_id": "550e8400-e29b-41d4-a716-446655440000",',
        indent: 1,
        key: 'event_id',
        valueType: 'string',
      },
      {
        content: '"event_type": "purchase",',
        indent: 1,
        key: 'event_type',
        valueType: 'string',
      },
      { content: '"user": {', indent: 1 },
      {
        content: '"id": "user_456"',
        indent: 2,
        key: 'id',
        valueType: 'string',
      },
      { content: '},', indent: 1 },
      { content: '"production_metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"deduplication_verified": true,',
        indent: 2,
        key: 'deduplication_verified',
        valueType: 'boolean',
        type: 'highlighted',
      },
      {
        content: '"processing_node": "edge-node-01",',
        indent: 2,
        key: 'processing_node',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"cluster_region": "us-east-1",',
        indent: 2,
        key: 'cluster_region',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"dedup_strategy": "id-based",',
        indent: 2,
        key: 'dedup_strategy',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"global_uniqueness_confirmed": true,',
        indent: 2,
        key: 'global_uniqueness_confirmed',
        valueType: 'boolean',
        type: 'highlighted',
      },
      {
        content: '"processing_latency_ms": 2.3',
        indent: 2,
        key: 'processing_latency_ms',
        valueType: 'number',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
];
