import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const parseLogsStages: Stage[] = [
  {
    id: 1,
    slug: 'original-input',
    title: 'Original Input',
    description: 'Raw log data from multiple sources in different formats',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Database connection failed"',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Database connection failed"',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 2,
    slug: 'format-detection',
    title: 'Format Detection',
    description:
      'Apply the authored content checks and add a candidate format label.',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Database connection failed"',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Database connection failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"detected_format": "json"',
        indent: 1,
        key: 'detected_format',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 3,
    slug: 'json-log-parsing',
    title: 'JSON Log Parsing',
    description:
      'Parse JSON application logs with timestamp normalization and field validation',
    inputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"level": "error",',
        indent: 1,
        key: 'level',
        valueType: 'string',
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Database connection failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      {
        content: '"detected_format": "json"',
        indent: 1,
        key: 'detected_format',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20T14:23:45.123Z",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: 'timestamp_unix',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"level": "ERROR",',
        indent: 1,
        key: 'level',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"service": "api",',
        indent: 1,
        key: 'service',
        valueType: 'string',
      },
      {
        content: '"message": "Database connection failed",',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '"metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"parsed_by": "json-parser",',
        indent: 2,
        key: 'parsed_by',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"parsed_at": 1729433025,',
        indent: 2,
        key: 'parsed_at',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"source_format": "json"',
        indent: 2,
        key: 'source_format',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 4,
    slug: 'csv-data-parsing',
    title: 'CSV Data Parsing',
    description:
      'Parse CSV sensor data with column mapping, type conversion, and validation rules',
    inputLines: [
      {
        content: '2025-10-20,temperature,temp-sensor-01,35.5,celsius',
        indent: 0,
      },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"timestamp": "2025-10-20",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: 'timestamp_unix',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"metric_name": "temperature",',
        indent: 1,
        key: 'metric_name',
        valueType: 'string',
      },
      {
        content: '"sensor_id": "temp-sensor-01",',
        indent: 1,
        key: 'sensor_id',
        valueType: 'string',
      },
      {
        content: '"value": "35.5",',
        indent: 1,
        key: 'value',
        valueType: 'string',
      },
      {
        content: '"value_numeric": 35.5,',
        indent: 1,
        key: 'value_numeric',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"unit": "celsius",',
        indent: 1,
        key: 'unit',
        valueType: 'string',
      },
      { content: '"sensor_metadata": {', indent: 1, type: 'highlighted' },
      {
        content: '"type": "temperature",',
        indent: 2,
        key: 'type',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"location": "warehouse"',
        indent: 2,
        key: 'location',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '},', indent: 1, type: 'highlighted' },
      { content: '"alert": {', indent: 1, type: 'highlighted' },
      {
        content: '"level": "critical",',
        indent: 2,
        key: 'level',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"message": "Temperature exceeds threshold"',
        indent: 2,
        key: 'message',
        valueType: 'string',
        type: 'highlighted',
      },
      { content: '}', indent: 1, type: 'highlighted' },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 5,
    slug: 'access-log-parsing',
    title: 'Access Log Parsing',
    description:
      'Apply one authored access-log pattern and map selected client and request fields.',
    inputLines: [
      {
        content:
          '203.0.113.45 - - [20/Oct/2025:14:23:45 +0000] "GET /api/users HTTP/1.1" 200 1234',
        indent: 0,
      },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"client_ip_hash": "7b9d4e2f1c8a6e3b",',
        indent: 1,
        key: 'client_ip_hash',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: 'timestamp_unix',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"method": "GET",',
        indent: 1,
        key: 'method',
        valueType: 'string',
      },
      {
        content: '"request": "/api/users",',
        indent: 1,
        key: 'request',
        valueType: 'string',
      },
      {
        content: '"http_version": "1.1",',
        indent: 1,
        key: 'http_version',
        valueType: 'string',
      },
      {
        content: '"status_code": 200,',
        indent: 1,
        key: 'status_code',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"bytes": 1234,',
        indent: 1,
        key: 'bytes',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"request_category": "api",',
        indent: 1,
        key: 'request_category',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"is_error": false',
        indent: 1,
        key: 'is_error',
        valueType: 'boolean',
        type: 'highlighted',
      },
      { content: '}', indent: 0 },
    ],
  },
  {
    id: 6,
    slug: 'syslog-message-parsing',
    title: 'Syslog Message Parsing',
    description:
      'Parse RFC3164 syslog messages with priority decomposition and severity classification',
    inputLines: [
      {
        content:
          '<134>Oct 20 14:23:45 edge-node-01 app[12345]: Database connection established',
        indent: 0,
      },
    ],
    outputLines: [
      { content: '{', indent: 0 },
      {
        content: '"priority": 134,',
        indent: 1,
        key: 'priority',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"facility": 16,',
        indent: 1,
        key: 'facility',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"severity": 6,',
        indent: 1,
        key: 'severity',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"severity_name": "Informational",',
        indent: 1,
        key: 'severity_name',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"timestamp_unix": 1729433025,',
        indent: 1,
        key: 'timestamp_unix',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"hostname": "edge-node-01",',
        indent: 1,
        key: 'hostname',
        valueType: 'string',
      },
      { content: '"tag": "app",', indent: 1, key: 'tag', valueType: 'string' },
      {
        content: '"process_id": 12345,',
        indent: 1,
        key: 'process_id',
        valueType: 'number',
        type: 'highlighted',
      },
      {
        content: '"application": "app",',
        indent: 1,
        key: 'application',
        valueType: 'string',
        type: 'highlighted',
      },
      {
        content: '"message": "Database connection established"',
        indent: 1,
        key: 'message',
        valueType: 'string',
      },
      { content: '}', indent: 0 },
    ],
  },
];
