import type { Stage } from '@site/src/components/DataPipelineExplorer/types';

export const motherduckRetailAnalyticsStages: Stage[] = [
  {
    id: 1,
    slug: 'generate-pos-transactions',
    title: 'Generate POS transactions',
    description:
      'Synthesize a point-of-sale event with items, totals, and a payment method on a 100ms timer.',
    inputLines: [
      {
        content: '[generate input: one synthetic POS event every 100ms]',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"employee_id": "EMP-8152",',
        indent: 1,
        key: 'employee_id',
        valueType: 'string',
      },
      {
        content: '"items": [',
        indent: 1,
        key: 'items',
        valueType: 'array',
      },
      {
        content: '{',
        indent: 2,
      },
      {
        content: '"category": "bakery",',
        indent: 3,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"name": "Item 154",',
        indent: 3,
        key: 'name',
        valueType: 'string',
      },
      {
        content: '"qty": 2,',
        indent: 3,
        key: 'qty',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-40153",',
        indent: 3,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 36.49',
        indent: 3,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 2,
      },
      {
        content: '],',
        indent: 1,
      },
      {
        content: '"payment_method": "card",',
        indent: 1,
        key: 'payment_method',
        valueType: 'string',
      },
      {
        content: '"store_id": 3,',
        indent: 1,
        key: 'store_id',
        valueType: 'number',
      },
      {
        content: '"subtotal": 72.98,',
        indent: 1,
        key: 'subtotal',
        valueType: 'number',
      },
      {
        content: '"tax_amount": 6.39,',
        indent: 1,
        key: 'tax_amount',
        valueType: 'number',
      },
      {
        content: '"tax_rate": 0.0875,',
        indent: 1,
        key: 'tax_rate',
        valueType: 'number',
      },
      {
        content: '"terminal_id": 3,',
        indent: 1,
        key: 'terminal_id',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2026-10-05T17:39:21.355365-07:00",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"total_amount": 79.37,',
        indent: 1,
        key: 'total_amount',
        valueType: 'number',
      },
      {
        content: '"txn_id": "b44d442c-8839-4cb0-b885-a76d573def6b",',
        indent: 1,
        key: 'txn_id',
        valueType: 'string',
      },
      {
        content: '"type": "sale"',
        indent: 1,
        key: 'type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 2,
    slug: 'enrich-with-store-metadata',
    title: 'Enrich with store metadata',
    description:
      'Look up the region, format, city, and size for the store and derive time and basket features.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"employee_id": "EMP-8152",',
        indent: 1,
        key: 'employee_id',
        valueType: 'string',
      },
      {
        content: '"items": [',
        indent: 1,
        key: 'items',
        valueType: 'array',
      },
      {
        content: '{',
        indent: 2,
      },
      {
        content: '"category": "bakery",',
        indent: 3,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"name": "Item 154",',
        indent: 3,
        key: 'name',
        valueType: 'string',
      },
      {
        content: '"qty": 2,',
        indent: 3,
        key: 'qty',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-40153",',
        indent: 3,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 36.49',
        indent: 3,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 2,
      },
      {
        content: '],',
        indent: 1,
      },
      {
        content: '"payment_method": "card",',
        indent: 1,
        key: 'payment_method',
        valueType: 'string',
      },
      {
        content: '"store_id": 3,',
        indent: 1,
        key: 'store_id',
        valueType: 'number',
      },
      {
        content: '"subtotal": 72.98,',
        indent: 1,
        key: 'subtotal',
        valueType: 'number',
      },
      {
        content: '"tax_amount": 6.39,',
        indent: 1,
        key: 'tax_amount',
        valueType: 'number',
      },
      {
        content: '"tax_rate": 0.0875,',
        indent: 1,
        key: 'tax_rate',
        valueType: 'number',
      },
      {
        content: '"terminal_id": 3,',
        indent: 1,
        key: 'terminal_id',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2026-10-05T17:39:21.355365-07:00",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"total_amount": 79.37,',
        indent: 1,
        key: 'total_amount',
        valueType: 'number',
      },
      {
        content: '"txn_id": "b44d442c-8839-4cb0-b885-a76d573def6b",',
        indent: 1,
        key: 'txn_id',
        valueType: 'string',
      },
      {
        content: '"type": "sale"',
        indent: 1,
        key: 'type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"avg_item_price": 72.98,',
        indent: 1,
        key: 'avg_item_price',
        valueType: 'number',
        type: 'added',
      },
      {
        content: '"basket_size": 1,',
        indent: 1,
        key: 'basket_size',
        valueType: 'number',
        type: 'added',
      },
      {
        content: '"day_of_week": "Monday",',
        indent: 1,
        key: 'day_of_week',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"employee_id": "EMP-8152",',
        indent: 1,
        key: 'employee_id',
        valueType: 'string',
      },
      {
        content: '"hour_of_day": 17,',
        indent: 1,
        key: 'hour_of_day',
        valueType: 'number',
        type: 'added',
      },
      {
        content: '"is_weekend": false,',
        indent: 1,
        key: 'is_weekend',
        valueType: 'boolean',
        type: 'added',
      },
      {
        content: '"items": [',
        indent: 1,
        key: 'items',
        valueType: 'array',
      },
      {
        content: '{',
        indent: 2,
      },
      {
        content: '"category": "bakery",',
        indent: 3,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"name": "Item 154",',
        indent: 3,
        key: 'name',
        valueType: 'string',
      },
      {
        content: '"qty": 2,',
        indent: 3,
        key: 'qty',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-40153",',
        indent: 3,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 36.49',
        indent: 3,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 2,
      },
      {
        content: '],',
        indent: 1,
      },
      {
        content: '"payment_method": "card",',
        indent: 1,
        key: 'payment_method',
        valueType: 'string',
      },
      {
        content: '"store_city": "Boise",',
        indent: 1,
        key: 'store_city',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"store_format": "express",',
        indent: 1,
        key: 'store_format',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"store_id": 3,',
        indent: 1,
        key: 'store_id',
        valueType: 'number',
      },
      {
        content: '"store_region": "NW",',
        indent: 1,
        key: 'store_region',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"store_sqft": 12000,',
        indent: 1,
        key: 'store_sqft',
        valueType: 'number',
        type: 'added',
      },
      {
        content: '"store_state": "ID",',
        indent: 1,
        key: 'store_state',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"subtotal": 72.98,',
        indent: 1,
        key: 'subtotal',
        valueType: 'number',
      },
      {
        content: '"tax_amount": 6.39,',
        indent: 1,
        key: 'tax_amount',
        valueType: 'number',
      },
      {
        content: '"tax_rate": 0.0875,',
        indent: 1,
        key: 'tax_rate',
        valueType: 'number',
      },
      {
        content: '"terminal_id": 3,',
        indent: 1,
        key: 'terminal_id',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2026-10-05T17:39:21.355365-07:00",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"total_amount": 79.37,',
        indent: 1,
        key: 'total_amount',
        valueType: 'number',
      },
      {
        content: '"txn_id": "b44d442c-8839-4cb0-b885-a76d573def6b",',
        indent: 1,
        key: 'txn_id',
        valueType: 'string',
      },
      {
        content: '"type": "sale"',
        indent: 1,
        key: 'type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 3,
    slug: 'validate-and-flag-transactions',
    title: 'Validate and flag transactions',
    description:
      'Apply the anomaly checks and attach the flags, an anomaly bit, and a quality score.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"avg_item_price": 72.98,',
        indent: 1,
        key: 'avg_item_price',
        valueType: 'number',
      },
      {
        content: '"basket_size": 1,',
        indent: 1,
        key: 'basket_size',
        valueType: 'number',
      },
      {
        content: '"day_of_week": "Monday",',
        indent: 1,
        key: 'day_of_week',
        valueType: 'string',
      },
      {
        content: '"employee_id": "EMP-8152",',
        indent: 1,
        key: 'employee_id',
        valueType: 'string',
      },
      {
        content: '"hour_of_day": 17,',
        indent: 1,
        key: 'hour_of_day',
        valueType: 'number',
      },
      {
        content: '"is_weekend": false,',
        indent: 1,
        key: 'is_weekend',
        valueType: 'boolean',
      },
      {
        content: '"items": [',
        indent: 1,
        key: 'items',
        valueType: 'array',
      },
      {
        content: '{',
        indent: 2,
      },
      {
        content: '"category": "bakery",',
        indent: 3,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"name": "Item 154",',
        indent: 3,
        key: 'name',
        valueType: 'string',
      },
      {
        content: '"qty": 2,',
        indent: 3,
        key: 'qty',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-40153",',
        indent: 3,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 36.49',
        indent: 3,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 2,
      },
      {
        content: '],',
        indent: 1,
      },
      {
        content: '"payment_method": "card",',
        indent: 1,
        key: 'payment_method',
        valueType: 'string',
      },
      {
        content: '"store_city": "Boise",',
        indent: 1,
        key: 'store_city',
        valueType: 'string',
      },
      {
        content: '"store_format": "express",',
        indent: 1,
        key: 'store_format',
        valueType: 'string',
      },
      {
        content: '"store_id": 3,',
        indent: 1,
        key: 'store_id',
        valueType: 'number',
      },
      {
        content: '"store_region": "NW",',
        indent: 1,
        key: 'store_region',
        valueType: 'string',
      },
      {
        content: '"store_sqft": 12000,',
        indent: 1,
        key: 'store_sqft',
        valueType: 'number',
      },
      {
        content: '"store_state": "ID",',
        indent: 1,
        key: 'store_state',
        valueType: 'string',
      },
      {
        content: '"subtotal": 72.98,',
        indent: 1,
        key: 'subtotal',
        valueType: 'number',
      },
      {
        content: '"tax_amount": 6.39,',
        indent: 1,
        key: 'tax_amount',
        valueType: 'number',
      },
      {
        content: '"tax_rate": 0.0875,',
        indent: 1,
        key: 'tax_rate',
        valueType: 'number',
      },
      {
        content: '"terminal_id": 3,',
        indent: 1,
        key: 'terminal_id',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2026-10-05T17:39:21.355365-07:00",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"total_amount": 79.37,',
        indent: 1,
        key: 'total_amount',
        valueType: 'number',
      },
      {
        content: '"txn_id": "b44d442c-8839-4cb0-b885-a76d573def6b",',
        indent: 1,
        key: 'txn_id',
        valueType: 'string',
      },
      {
        content: '"type": "sale"',
        indent: 1,
        key: 'type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"anomaly_flags": [],',
        indent: 1,
        key: 'anomaly_flags',
        valueType: 'array',
        type: 'added',
      },
      {
        content: '"avg_item_price": 72.98,',
        indent: 1,
        key: 'avg_item_price',
        valueType: 'number',
      },
      {
        content: '"basket_size": 1,',
        indent: 1,
        key: 'basket_size',
        valueType: 'number',
      },
      {
        content: '"day_of_week": "Monday",',
        indent: 1,
        key: 'day_of_week',
        valueType: 'string',
      },
      {
        content: '"employee_id": "EMP-8152",',
        indent: 1,
        key: 'employee_id',
        valueType: 'string',
      },
      {
        content: '"hour_of_day": 17,',
        indent: 1,
        key: 'hour_of_day',
        valueType: 'number',
      },
      {
        content: '"is_anomaly": false,',
        indent: 1,
        key: 'is_anomaly',
        valueType: 'boolean',
        type: 'added',
      },
      {
        content: '"is_weekend": false,',
        indent: 1,
        key: 'is_weekend',
        valueType: 'boolean',
      },
      {
        content: '"items": [',
        indent: 1,
        key: 'items',
        valueType: 'array',
      },
      {
        content: '{',
        indent: 2,
      },
      {
        content: '"category": "bakery",',
        indent: 3,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"name": "Item 154",',
        indent: 3,
        key: 'name',
        valueType: 'string',
      },
      {
        content: '"qty": 2,',
        indent: 3,
        key: 'qty',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-40153",',
        indent: 3,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 36.49',
        indent: 3,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 2,
      },
      {
        content: '],',
        indent: 1,
      },
      {
        content: '"payment_method": "card",',
        indent: 1,
        key: 'payment_method',
        valueType: 'string',
      },
      {
        content: '"quality_score": "clean",',
        indent: 1,
        key: 'quality_score',
        valueType: 'string',
        type: 'added',
      },
      {
        content: '"store_city": "Boise",',
        indent: 1,
        key: 'store_city',
        valueType: 'string',
      },
      {
        content: '"store_format": "express",',
        indent: 1,
        key: 'store_format',
        valueType: 'string',
      },
      {
        content: '"store_id": 3,',
        indent: 1,
        key: 'store_id',
        valueType: 'number',
      },
      {
        content: '"store_region": "NW",',
        indent: 1,
        key: 'store_region',
        valueType: 'string',
      },
      {
        content: '"store_sqft": 12000,',
        indent: 1,
        key: 'store_sqft',
        valueType: 'number',
      },
      {
        content: '"store_state": "ID",',
        indent: 1,
        key: 'store_state',
        valueType: 'string',
      },
      {
        content: '"subtotal": 72.98,',
        indent: 1,
        key: 'subtotal',
        valueType: 'number',
      },
      {
        content: '"tax_amount": 6.39,',
        indent: 1,
        key: 'tax_amount',
        valueType: 'number',
      },
      {
        content: '"tax_rate": 0.0875,',
        indent: 1,
        key: 'tax_rate',
        valueType: 'number',
      },
      {
        content: '"terminal_id": 3,',
        indent: 1,
        key: 'terminal_id',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2026-10-05T17:39:21.355365-07:00",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"total_amount": 79.37,',
        indent: 1,
        key: 'total_amount',
        valueType: 'number',
      },
      {
        content: '"txn_id": "b44d442c-8839-4cb0-b885-a76d573def6b",',
        indent: 1,
        key: 'txn_id',
        valueType: 'string',
      },
      {
        content: '"type": "sale"',
        indent: 1,
        key: 'type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
  },
  {
    id: 4,
    slug: 'batch-and-encode-to-parquet',
    title: 'Batch and encode to Parquet',
    description:
      'Flatten items to JSON text, batch 1000 events or 10 seconds, and encode each batch as one Parquet object.',
    inputLines: [
      {
        content: '{',
        indent: 0,
      },
      {
        content: '"anomaly_flags": [],',
        indent: 1,
        key: 'anomaly_flags',
        valueType: 'array',
      },
      {
        content: '"avg_item_price": 72.98,',
        indent: 1,
        key: 'avg_item_price',
        valueType: 'number',
      },
      {
        content: '"basket_size": 1,',
        indent: 1,
        key: 'basket_size',
        valueType: 'number',
      },
      {
        content: '"day_of_week": "Monday",',
        indent: 1,
        key: 'day_of_week',
        valueType: 'string',
      },
      {
        content: '"employee_id": "EMP-8152",',
        indent: 1,
        key: 'employee_id',
        valueType: 'string',
      },
      {
        content: '"hour_of_day": 17,',
        indent: 1,
        key: 'hour_of_day',
        valueType: 'number',
      },
      {
        content: '"is_anomaly": false,',
        indent: 1,
        key: 'is_anomaly',
        valueType: 'boolean',
      },
      {
        content: '"is_weekend": false,',
        indent: 1,
        key: 'is_weekend',
        valueType: 'boolean',
      },
      {
        content: '"items": [',
        indent: 1,
        key: 'items',
        valueType: 'array',
      },
      {
        content: '{',
        indent: 2,
      },
      {
        content: '"category": "bakery",',
        indent: 3,
        key: 'category',
        valueType: 'string',
      },
      {
        content: '"name": "Item 154",',
        indent: 3,
        key: 'name',
        valueType: 'string',
      },
      {
        content: '"qty": 2,',
        indent: 3,
        key: 'qty',
        valueType: 'number',
      },
      {
        content: '"sku": "SKU-40153",',
        indent: 3,
        key: 'sku',
        valueType: 'string',
      },
      {
        content: '"unit_price": 36.49',
        indent: 3,
        key: 'unit_price',
        valueType: 'number',
      },
      {
        content: '}',
        indent: 2,
      },
      {
        content: '],',
        indent: 1,
      },
      {
        content: '"payment_method": "card",',
        indent: 1,
        key: 'payment_method',
        valueType: 'string',
      },
      {
        content: '"quality_score": "clean",',
        indent: 1,
        key: 'quality_score',
        valueType: 'string',
      },
      {
        content: '"store_city": "Boise",',
        indent: 1,
        key: 'store_city',
        valueType: 'string',
      },
      {
        content: '"store_format": "express",',
        indent: 1,
        key: 'store_format',
        valueType: 'string',
      },
      {
        content: '"store_id": 3,',
        indent: 1,
        key: 'store_id',
        valueType: 'number',
      },
      {
        content: '"store_region": "NW",',
        indent: 1,
        key: 'store_region',
        valueType: 'string',
      },
      {
        content: '"store_sqft": 12000,',
        indent: 1,
        key: 'store_sqft',
        valueType: 'number',
      },
      {
        content: '"store_state": "ID",',
        indent: 1,
        key: 'store_state',
        valueType: 'string',
      },
      {
        content: '"subtotal": 72.98,',
        indent: 1,
        key: 'subtotal',
        valueType: 'number',
      },
      {
        content: '"tax_amount": 6.39,',
        indent: 1,
        key: 'tax_amount',
        valueType: 'number',
      },
      {
        content: '"tax_rate": 0.0875,',
        indent: 1,
        key: 'tax_rate',
        valueType: 'number',
      },
      {
        content: '"terminal_id": 3,',
        indent: 1,
        key: 'terminal_id',
        valueType: 'number',
      },
      {
        content: '"timestamp": "2026-10-05T17:39:21.355365-07:00",',
        indent: 1,
        key: 'timestamp',
        valueType: 'string',
      },
      {
        content: '"total_amount": 79.37,',
        indent: 1,
        key: 'total_amount',
        valueType: 'number',
      },
      {
        content: '"txn_id": "b44d442c-8839-4cb0-b885-a76d573def6b",',
        indent: 1,
        key: 'txn_id',
        valueType: 'string',
      },
      {
        content: '"type": "sale"',
        indent: 1,
        key: 'type',
        valueType: 'string',
      },
      {
        content: '}',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '[Parquet batch from the sample run]',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# rows: 3 events (pipeline batches 1000 or 10s)',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# bytes: 9988 with zstd compression',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# items flattened to items_json; anomaly_flags serialized',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# magic: PAR1 ... PAR1',
        indent: 0,
        type: 'highlighted',
      },
    ],
  },
  {
    id: 5,
    slug: 'write-partitioned-parquet-to-s3',
    title: 'Write partitioned Parquet to S3',
    description:
      'Upload each Parquet batch under region and date partitions that DuckLake can discover. Delivery has not been exercised.',
    inputLines: [
      {
        content: '[Parquet batches]',
        indent: 0,
      },
    ],
    outputLines: [
      {
        content: '# Bucket: ${S3_BUCKET}',
        indent: 0,
        type: 'highlighted',
      },
      {
        content:
          '# Key: transactions/region=NW/date=<yyyy-mm-dd>/batch_<unix>_<n>.parquet',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# Partitions: store_region and date, Hive style',
        indent: 0,
        type: 'highlighted',
      },
      {
        content: '# Delivery behavior: not assessed',
        indent: 0,
        type: 'highlighted',
      },
    ],
  },
];
