pipeline:
  processors:
    - try:
        - json_schema:
            schema: '{"type":"object","required":["sensor_id"]}'
        - mapping: 'root = this.with("status", "valid")'
    - catch:
        - mapping: |
            root = this.with("status", "invalid")
            root.error = error()

output:
  switch:
    cases:
      - check: this.status == "valid"
        output:
          kafka:
            addresses: [localhost:9092]
            topic: sensor-data-valid

      - check: this.status == "invalid"
        output:
          kafka:
            addresses: [localhost:9092]
            topic: sensor-data-dlq
